-- Auto-generated from Bible Baseball Questions.xlsx
-- Total: 404 questions

-- Wipe existing baseball uses so we can reseed cleanly.
delete from question_game_uses where game_type='bible_baseball';
delete from questions where id in (select question_id from question_game_uses where game_type='bible_baseball');

with inserted as (
  insert into questions (text, correct_answer, difficulty, format, choices) values
  ('What sign did Rahab place in her window to protect her family?', 'A scarlet cord', 'single', 'multiple_choice', '["A) An olive branch","B) A scarlet cord","C) A red lamp","D) A white cloth"]'),
  ('Why was Daniel thrown into the lions’ den?', 'He prayed to God', 'single', 'multiple_choice', '["A) He refused to bow to the king","B) He prayed to God","C) He stole from the palace","D) He challenged the king"]'),
  ('What job did Nehemiah have before rebuilding Jerusalem’s wall?', 'Cupbearer', 'single', 'multiple_choice', '["A) Priest","B) Cupbearer","C) Soldier","D) Shepherd"]'),
  ('What did Esau sell for a bowl of stew?', 'His birthright', 'single', 'multiple_choice', '["A) His blessing","B) His birthright","C) His inheritance","D) His flock"]'),
  ('What animal did God provide instead of Isaac?', 'A ram', 'single', 'multiple_choice', '["A) A lamb","B) A goat","C) A ram","D) A dove"]'),
  ('What tribe was Moses from?', 'Levi', 'single', 'multiple_choice', '["A) Judah","B) Benjamin","C) Levi","D) Ephraim"]'),
  ('What did Israel make while Moses was on Mount Sinai?', 'A golden calf', 'single', 'multiple_choice', '["A) A bronze serpent","B) A golden calf","C) An ark","D) A stone altar"]'),
  ('How many men did Nebuchadnezzar see walking in the fiery furnace?', 'Four', 'single', 'multiple_choice', '["A) Three","B) Four","C) Five","D) Six"]'),
  ('Which prophet challenged the prophets of Baal on Mount Carmel?', 'Elijah', 'single', 'multiple_choice', '["A) Elisha","B) Isaiah","C) Elijah","D) Jeremiah"]'),
  ('How was Elijah taken to heaven?', 'In a whirlwind', 'single', 'multiple_choice', '["A) By a chariot into the sea","B) In a whirlwind","C) By an angel","D) On a cloud"]'),
  ('What disease was Naaman healed from after washing in the Jordan?', 'Leprosy', 'single', 'multiple_choice', '["A) Blindness","B) Leprosy","C) Paralysis","D) Fever"]'),
  ('What did Pharaoh dream about that Joseph interpreted?', 'Cows and grain', 'single', 'multiple_choice', '["A) Sheep and goats","B) Cows and grain","C) Stars and moons","D) Rivers and fish"]'),
  ('What position did Joseph eventually hold in Egypt?', 'Second in command', 'single', 'multiple_choice', '["A) High priest","B) Army general","C) Second in command","D) Chief judge"]'),
  ('What was Jacob’s new name after he wrestled with God?', 'Israel', 'single', 'multiple_choice', '["A) Judah","B) Israel","C) Benjamin","D) Levi"]'),
  ('What city did Jonah preach to after the fish released him?', 'Nineveh', 'single', 'multiple_choice', '["A) Jericho","B) Nineveh","C) Bethlehem","D) Damascus"]'),
  ('What was kept inside the Ark of the Covenant?', 'The Ten Commandments', 'single', 'multiple_choice', '["A) David’s harp","B) The Ten Commandments","C) Solomon’s crown","D) Aaron’s robe"]'),
  ('Who anointed David as king?', 'Samuel', 'single', 'multiple_choice', '["A) Nathan","B) Samuel","C) Elijah","D) Gad"]'),
  ('Which king built the first temple in Jerusalem?', 'Solomon', 'single', 'multiple_choice', '["A) Saul","B) David","C) Solomon","D) Rehoboam"]'),
  ('What river did Israel cross to enter the Promised Land?', 'Jordan', 'single', 'multiple_choice', '["A) Nile","B) Euphrates","C) Jordan","D) Tigris"]'),
  ('Who advised Esther to approach the king?', 'Mordecai', 'single', 'multiple_choice', '["A) Ezra","B) Daniel","C) Mordecai","D) Nehemiah"]'),
  ('What happened at the Tower of Babel?', 'God confused languages', 'single', 'multiple_choice', '["A) God sent a flood","B) God confused languages","C) Fire fell from heaven","D) A wall collapsed"]'),
  ('Which judge defeated Midian with only 300 men?', 'Gideon', 'single', 'multiple_choice', '["A) Samson","B) Gideon","C) Deborah","D) Jephthah"]'),
  ('Which prophet confronted David about Bathsheba?', 'Nathan', 'single', 'multiple_choice', '["A) Nathan","B) Samuel","C) Elijah","D) Isaiah"]'),
  ('Which king threw Daniel into the lions’ den?', 'Darius', 'single', 'multiple_choice', '["A) Nebuchadnezzar","B) Darius","C) Cyrus","D) Ahab"]'),
  ('What was Samuel’s mother’s name?', 'Hannah', 'single', 'multiple_choice', '["A) Sarah","B) Hannah","C) Rachel","D) Naomi"]'),
  ('What was David’s closest friend’s name?', 'Jonathan', 'single', 'multiple_choice', '["A) Abner","B) Jonathan","C) Joab","D) Nathan"]'),
  ('What book tells the story of Israel leaving Egypt?', 'Exodus', 'single', 'multiple_choice', '["A) Genesis","B) Exodus","C) Leviticus","D) Numbers"]'),
  ('What did God place in the sky as a covenant sign after the flood?', 'A rainbow', 'single', 'multiple_choice', '["A) A star","B) A dove","C) A rainbow","D) A cloud"]'),
  ('What city’s walls fell after Israel marched around them?', 'Jericho', 'single', 'multiple_choice', '["A) Ai","B) Jerusalem","C) Jericho","D) Nineveh"]'),
  ('Who followed Elijah as prophet?', 'Elisha', 'single', 'multiple_choice', '["A) Isaiah","B) Elisha","C) Jeremiah","D) Ezekiel"]'),
  ('Which angel announced Jesus’ birth to Mary?', 'Gabriel', 'single', 'multiple_choice', '["A) Michael","B) Raphael","C) Gabriel","D) Uriel"]'),
  ('What was Jesus’ first recorded miracle?', 'Turning water into wine', 'single', 'multiple_choice', '["A) Feeding 5,000","B) Walking on water","C) Turning water into wine","D) Healing a blind man"]'),
  ('In what town did Jesus perform His first recorded miracle?', 'Cana', 'single', 'multiple_choice', '["A) Nazareth","B) Bethlehem","C) Cana","D) Capernaum"]'),
  ('What garden did Jesus pray in before His arrest?', 'Gethsemane', 'single', 'multiple_choice', '["A) Eden","B) Gethsemane","C) Carmel","D) Jericho"]'),
  ('What was written above Jesus on the cross?', 'King of the Jews', 'single', 'multiple_choice', '["A) Son of David","B) King of Israel","C) King of the Jews","D) Messiah"]'),
  ('Who carried Jesus’ cross for part of the journey?', 'Simon of Cyrene', 'single', 'multiple_choice', '["A) Peter","B) John","C) Simon of Cyrene","D) Joseph of Arimathea"]'),
  ('Who asked Pilate for Jesus’ body after the crucifixion?', 'Joseph of Arimathea', 'single', 'multiple_choice', '["A) Nicodemus","B) Joseph of Arimathea","C) Mary Magdalene","D) John"]'),
  ('Which disciple doubted Jesus’ resurrection until he saw Him?', 'Thomas', 'single', 'multiple_choice', '["A) Philip","B) Thomas","C) Andrew","D) Matthew"]'),
  ('On what mountain did Jesus ascend into heaven?', 'Mount of Olives', 'single', 'multiple_choice', '["A) Mount Sinai","B) Mount Carmel","C) Mount of Olives","D) Mount Ararat"]'),
  ('What event occurred fifty days after Passover?', 'Pentecost', 'single', 'multiple_choice', '["A) Purim","B) Pentecost","C) Hanukkah","D) Passover"]'),
  ('On what road did Saul encounter Jesus?', 'Damascus Road', 'single', 'multiple_choice', '["A) Jericho Road","B) Damascus Road","C) Emmaus Road","D) Roman Road"]'),
  ('What trade did Paul work in?', 'Tentmaking', 'single', 'multiple_choice', '["A) Carpentry","B) Tentmaking","C) Fishing","D) Blacksmithing"]'),
  ('Who traveled with Paul on his first missionary journey?', 'Barnabas', 'single', 'multiple_choice', '["A) Timothy","B) Barnabas","C) Peter","D) Luke"]'),
  ('On what island was John when he received Revelation?', 'Patmos', 'single', 'multiple_choice', '["A) Crete","B) Cyprus","C) Malta","D) Patmos"]'),
  ('Which Gospel was written by a doctor?', 'Luke', 'single', 'multiple_choice', '["A) Matthew","B) Mark","C) Luke","D) John"]'),
  ('Who replaced Judas Iscariot among the apostles?', 'Matthias', 'single', 'multiple_choice', '["A) Barnabas","B) Matthias","C) Silas","D) Timothy"]'),
  ('Who was the first Christian martyr?', 'Stephen', 'single', 'multiple_choice', '["A) Stephen","B) James","C) Peter","D) Paul"]'),
  ('Who appeared with Jesus at the Transfiguration?', 'Moses and Elijah', 'single', 'multiple_choice', '["A) Abraham and David","B) Moses and Elijah","C) Peter and John","D) Samuel and Isaiah"]'),
  ('What chapter is often called the “Love Chapter”?', '1 Corinthians 13', 'single', 'multiple_choice', '["A) Romans 8","B) Psalm 23","C) 1 Corinthians 13","D) Hebrews 11"]'),
  ('What chapter contains the Fruit of the Spirit?', 'Galatians 5', 'single', 'multiple_choice', '["A) Galatians 5","B) Ephesians 6","C) Romans 12","D) James 1"]'),
  ('Which disciple was a tax collector before following Jesus?', 'Matthew', 'single', 'multiple_choice', '["A) Peter","B) Matthew","C) Thomas","D) Andrew"]'),
  ('Who was the Roman governor who sentenced Jesus?', 'Pontius Pilate', 'single', 'multiple_choice', '["A) Herod","B) Caesar Augustus","C) Pontius Pilate","D) Felix"]'),
  ('What was Paul’s name before he became known as Paul?', 'Saul', 'single', 'multiple_choice', '["A) Silas","B) Saul","C) Simon","D) Stephen"]'),
  ('Who was Paul’s young helper and pastor?', 'Timothy', 'single', 'multiple_choice', '["A) Titus","B) Timothy","C) Barnabas","D) Luke"]'),
  ('What happened to Saul after he encountered Jesus on the Damascus Road?', 'He was blinded', 'single', 'multiple_choice', '["A) He became sick","B) He was blinded","C) He was arrested","D) He ran away"]'),
  ('Who wrote the book of Acts?', 'Luke', 'single', 'multiple_choice', '["A) Paul","B) Peter","C) Luke","D) John"]'),
  ('What was the name of the high priest who questioned Jesus?', 'Caiaphas', 'single', 'multiple_choice', '["A) Annas","B) Caiaphas","C) Gamaliel","D) Herod"]'),
  ('What does the word “gospel” mean?', 'Good news', 'single', 'multiple_choice', '["A) Law","B) Good news","C) Wisdom","D) Promise"]'),
  ('What is the second greatest commandment?', 'Love your neighbor', 'single', 'multiple_choice', '["A) Honor your parents","B) Love your neighbor","C) Keep the Sabbath","D) Pray always"]'),
  ('What chapter is called the “Hall of Faith”?', 'Hebrews 11', 'single', 'multiple_choice', '["A) Romans 8","B) Hebrews 11","C) James 2","D) 1 Corinthians 13"]'),
  ('What feast remembers God passing over Israel’s homes?', 'Passover', 'single', 'multiple_choice', '["A) Joseph","B) David","C) Passover","D) Aaron"]'),
  ('What did Israel follow by day in the wilderness?', 'A pillar of cloud', 'single', 'multiple_choice', '["A) A pillar of cloud","B) Nineveh","C) Bethlehem","D) Nazareth"]'),
  ('What did Israel follow by night in the wilderness?', 'A pillar of fire', 'single', 'multiple_choice', '["A) A pillar of fire","B) Nineveh","C) Egypt","D) Jerusalem"]'),
  ('What did God give Israel to drink from?', 'A rock', 'single', 'multiple_choice', '["A) A rock","B) Peter","C) David","D) Joshua"]'),
  ('What river did Israel cross into the Promised Land?', 'The Jordan River', 'single', 'multiple_choice', '["A) The Jordan River","B) Joshua","C) Moses","D) Jacob"]'),
  ('Who was Rahab?', 'A woman who helped Israel’s spies', 'single', 'multiple_choice', '["A) A woman who helped Israel’s spies","B) Nazareth","C) Bethlehem","D) Cana"]'),
  ('What sign did Rahab hang in her window?', 'A scarlet cord', 'single', 'multiple_choice', '["A) Aaron","B) Joseph","C) Abraham","D) A scarlet cord"]'),
  ('Who said, “As for me and my house, we will serve the Lord”?', 'Joshua', 'single', 'multiple_choice', '["A) Joshua","B) Noah","C) John","D) Aaron"]'),
  ('Who was the shepherd boy who became king?', 'David', 'single', 'multiple_choice', '["A) Joshua","B) David","C) Abraham","D) Aaron"]'),
  ('What instrument did David play?', 'The harp', 'single', 'multiple_choice', '["A) Peter","B) Aaron","C) The harp","D) Jacob"]'),
  ('Who was David’s best friend?', 'Jonathan', 'single', 'multiple_choice', '["A) Jonathan","B) Elijah","C) Samuel","D) David"]'),
  ('Who was Jonathan’s father?', 'Saul', 'single', 'multiple_choice', '["A) Jacob","B) Saul","C) Paul","D) Aaron"]'),
  ('Who wrote many of the Psalms?', 'David', 'single', 'multiple_choice', '["A) Joshua","B) Noah","C) Aaron","D) David"]'),
  ('What book comes after Psalms?', 'Proverbs', 'single', 'multiple_choice', '["A) Paul","B) Proverbs","C) Abraham","D) John"]'),
  ('What book comes before Exodus?', 'Genesis', 'single', 'multiple_choice', '["A) John","B) Genesis","C) David","D) Elijah"]'),
  ('What is the first book of the Bible?', 'Genesis', 'single', 'multiple_choice', '["A) Genesis","B) Noah","C) Jacob","D) Joshua"]'),
  ('What is the last book of the Bible?', 'Revelation', 'single', 'multiple_choice', '["A) Revelation","B) Elijah","C) Moses","D) John"]'),
  ('What is the first book of the New Testament?', 'Matthew', 'single', 'multiple_choice', '["A) Elijah","B) Moses","C) David","D) Matthew"]'),
  ('What is the first book of the Old Testament?', 'Genesis', 'single', 'multiple_choice', '["A) Genesis","B) Peter","C) Jacob","D) David"]'),
  ('How many books are in the Bible?', 'Sixty-six', 'single', 'multiple_choice', '["A) Moses","B) John","C) Sixty-six","D) Aaron"]'),
  ('How many books are in the New Testament?', 'Twenty-seven', 'single', 'multiple_choice', '["A) Noah","B) Moses","C) Joseph","D) Twenty-seven"]'),
  ('How many books are in the Old Testament?', 'Thirty-nine', 'single', 'multiple_choice', '["A) Thirty-nine","B) Daniel","C) Noah","D) Moses"]'),
  ('Who is the Son of God?', 'Jesus', 'single', 'multiple_choice', '["A) Noah","B) Moses","C) David","D) Jesus"]'),
  ('Where was Jesus born?', 'Bethlehem', 'single', 'multiple_choice', '["A) Paul","B) Moses","C) Bethlehem","D) Noah"]'),
  ('Who was Jesus’ mother?', 'Mary', 'single', 'multiple_choice', '["A) Abraham","B) Elijah","C) Paul","D) Mary"]'),
  ('Who was Mary’s husband?', 'Joseph', 'single', 'multiple_choice', '["A) Elijah","B) Samuel","C) Aaron","D) Joseph"]'),
  ('Who announced Jesus’ birth to Mary?', 'An angel', 'single', 'multiple_choice', '["A) Joshua","B) Jacob","C) Peter","D) An angel"]'),
  ('What angel spoke to Mary?', 'Gabriel', 'single', 'multiple_choice', '["A) Joshua","B) Joseph","C) Gabriel","D) Peter"]'),
  ('Who visited Jesus after seeing the star?', 'The wise men', 'single', 'multiple_choice', '["A) David","B) The wise men","C) John","D) Joseph"]'),
  ('Who heard the angels announce Jesus’ birth?', 'Shepherds', 'single', 'multiple_choice', '["A) Abraham","B) Noah","C) Joseph","D) Shepherds"]'),
  ('What did Jesus sleep in as a baby?', 'A manger', 'single', 'multiple_choice', '["A) John","B) A manger","C) Joshua","D) David"]'),
  ('Who baptized Jesus?', 'John the Baptist', 'single', 'multiple_choice', '["A) Peter","B) Paul","C) John the Baptist","D) Elijah"]'),
  ('What river was Jesus baptized in?', 'The Jordan River', 'single', 'multiple_choice', '["A) Samuel","B) The Jordan River","C) Abraham","D) Elijah"]'),
  ('What came down like a dove when Jesus was baptized?', 'The Holy Spirit', 'single', 'multiple_choice', '["A) Moses","B) Peter","C) Jacob","D) The Holy Spirit"]'),
  ('Who tempted Jesus in the wilderness?', 'Satan', 'single', 'multiple_choice', '["A) John","B) Satan","C) Noah","D) Samuel"]'),
  ('How long was Jesus tempted in the wilderness?', 'Forty days', 'single', 'multiple_choice', '["A) Forty days","B) Aaron","C) Moses","D) Noah"]'),
  ('What did Jesus turn water into?', 'Wine', 'single', 'multiple_choice', '["A) Joseph","B) Paul","C) Wine","D) Aaron"]'),
  ('Where did Jesus turn water into wine?', 'Cana', 'single', 'multiple_choice', '["A) Daniel","B) Noah","C) Cana","D) Elijah"]'),
  ('Who walked on water?', 'Jesus', 'single', 'multiple_choice', '["A) Moses","B) Samuel","C) Jesus","D) Joseph"]'),
  ('Which disciple walked on water toward Jesus?', 'Peter', 'single', 'multiple_choice', '["A) David","B) Aaron","C) Elijah","D) Peter"]'),
  ('Who did Jesus raise from the dead after four days?', 'Lazarus', 'single', 'multiple_choice', '["A) John","B) Lazarus","C) Elijah","D) David"]'),
  ('Who were Lazarus’ sisters?', 'Mary and Martha', 'single', 'multiple_choice', '["A) Samuel","B) Mary and Martha","C) Moses","D) Joseph"]'),
  ('What did Jesus feed the 5,000 with?', 'Five loaves and two fish', 'single', 'multiple_choice', '["A) Five loaves and two fish","B) Jerusalem","C) Jericho","D) Nineveh"]'),
  ('Who betrayed Jesus?', 'Judas Iscariot', 'single', 'multiple_choice', '["A) Judas Iscariot","B) Jacob","C) Elijah","D) Joshua"]'),
  ('How many disciples did Jesus choose?', 'Twelve', 'single', 'multiple_choice', '["A) John","B) Samuel","C) Elijah","D) Twelve"]'),
  ('Which disciple denied Jesus three times?', 'Peter', 'single', 'multiple_choice', '["A) Daniel","B) Paul","C) Peter","D) Abraham"]'),
  ('What meal did Jesus share before His arrest?', 'The Last Supper', 'single', 'multiple_choice', '["A) Elijah","B) John","C) The Last Supper","D) David"]'),
  ('What did Jesus die on?', 'A cross', 'single', 'multiple_choice', '["A) John","B) A cross","C) Abraham","D) Paul"]'),
  ('What happened on the third day after Jesus died?', 'He rose from the dead', 'single', 'multiple_choice', '["A) Nineveh","B) He rose from the dead","C) Patmos","D) Cana"]'),
  ('Who was the first to see the risen Jesus?', 'Mary Magdalene', 'single', 'multiple_choice', '["A) Abraham","B) Moses","C) Aaron","D) Mary Magdalene"]'),
  ('What did the stone cover?', 'Jesus’ tomb', 'single', 'multiple_choice', '["A) Abraham","B) Elijah","C) Jesus’ tomb","D) Joseph"]'),
  ('Who rolled away the stone?', 'An angel', 'single', 'multiple_choice', '["A) Joshua","B) Noah","C) Samuel","D) An angel"]'),
  ('Where did Jesus ascend after rising from the dead?', 'Heaven', 'single', 'multiple_choice', '["A) Heaven","B) Samuel","C) John","D) Joshua"]'),
  ('Who is called the Comforter or Helper?', 'The Holy Spirit', 'single', 'multiple_choice', '["A) Samuel","B) The Holy Spirit","C) Daniel","D) Peter"]'),
  ('What happened at Pentecost?', 'The Holy Spirit came', 'single', 'multiple_choice', '["A) Egypt","B) Nineveh","C) Patmos","D) The Holy Spirit came"]'),
  ('Who preached at Pentecost?', 'Peter', 'single', 'multiple_choice', '["A) Peter","B) Joseph","C) Paul","D) Samuel"]'),
  ('Who was blinded on the road to Damascus?', 'Saul', 'single', 'multiple_choice', '["A) Daniel","B) Joseph","C) Saul","D) Peter"]'),
  ('What was Saul’s name changed to?', 'Paul', 'single', 'multiple_choice', '["A) David","B) Noah","C) Samuel","D) Paul"]'),
  ('Who traveled and preached to the Gentiles?', 'Paul', 'single', 'multiple_choice', '["A) Moses","B) Paul","C) Noah","D) David"]'),
  ('Who was Paul’s young helper?', 'Timothy', 'single', 'multiple_choice', '["A) Joseph","B) Abraham","C) John","D) Timothy"]'),
  ('Who wrote many letters in the New Testament?', 'Paul', 'single', 'multiple_choice', '["A) Joseph","B) Joshua","C) Samuel","D) Paul"]'),
  ('Who was a doctor and wrote a Gospel?', 'Luke', 'single', 'multiple_choice', '["A) Samuel","B) Luke","C) Jacob","D) Peter"]'),
  ('Who wrote Revelation?', 'John', 'single', 'multiple_choice', '["A) Joseph","B) Elijah","C) Samuel","D) John"]'),
  ('Where was John when he wrote Revelation?', 'Patmos', 'single', 'multiple_choice', '["A) Patmos","B) John","C) Moses","D) Elijah"]'),
  ('Who was the tax collector Jesus called?', 'Matthew', 'single', 'multiple_choice', '["A) Joseph","B) Jacob","C) Moses","D) Matthew"]'),
  ('Who climbed a tree to see Jesus?', 'Zacchaeus', 'single', 'multiple_choice', '["A) Daniel","B) Peter","C) Aaron","D) Zacchaeus"]'),
  ('What kind of tree did Zacchaeus climb?', 'A sycamore tree', 'single', 'multiple_choice', '["A) John","B) A sycamore tree","C) Samuel","D) Joshua"]'),
  ('Who helped Jesus carry His cross?', 'Simon of Cyrene', 'single', 'multiple_choice', '["A) Paul","B) Jacob","C) Simon of Cyrene","D) Abraham"]'),
  ('Who doubted Jesus had risen until he saw Him?', 'Thomas', 'single', 'multiple_choice', '["A) Jacob","B) Thomas","C) Noah","D) Paul"]'),
  ('Who asked for Jesus’ body after the crucifixion?', 'Joseph of Arimathea', 'single', 'multiple_choice', '["A) Joseph of Arimathea","B) David","C) Noah","D) Paul"]'),
  ('Who was released instead of Jesus?', 'Barabbas', 'single', 'multiple_choice', '["A) Joseph","B) David","C) Aaron","D) Barabbas"]'),
  ('What is sin?', 'Disobedience against God', 'single', 'multiple_choice', '["A) Moses","B) Elijah","C) Disobedience against God","D) Peter"]'),
  ('What is prayer?', 'Talking to God', 'single', 'multiple_choice', '["A) Abraham","B) Talking to God","C) Aaron","D) Joseph"]'),
  ('What is worship?', 'Honoring and praising God', 'single', 'multiple_choice', '["A) Egypt","B) Nineveh","C) Patmos","D) Honoring and praising God"]'),
  ('What is the gospel?', 'The good news about Jesus', 'single', 'multiple_choice', '["A) The good news about Jesus","B) Nineveh","C) Cana","D) Nazareth"]'),
  ('What does “repent” mean?', 'Turn away from sin', 'single', 'multiple_choice', '["A) Turn away from sin","B) Patmos","C) Nineveh","D) Cana"]'),
  ('What does “amen” mean?', 'So be it', 'single', 'multiple_choice', '["A) Abraham","B) Peter","C) Joseph","D) So be it"]'),
  ('What does “disciple” mean?', 'A follower of Jesus', 'single', 'multiple_choice', '["A) Nineveh","B) Jerusalem","C) A follower of Jesus","D) Egypt"]'),
  ('What does “faith” mean?', 'Trust in God', 'single', 'multiple_choice', '["A) Peter","B) Trust in God","C) Moses","D) Paul"]'),
  ('What does “grace” mean?', 'God’s undeserved favor', 'single', 'multiple_choice', '["A) Abraham","B) John","C) God’s undeserved favor","D) Paul"]'),
  ('What does “mercy” mean?', 'God not giving us the punishment we deserve', 'single', 'multiple_choice', '["A) Egypt","B) Jerusalem","C) God not giving us the punishment we deserve","D) Patmos"]'),
  ('What is baptism a picture of?', 'New life in Christ', 'single', 'multiple_choice', '["A) Bethlehem","B) New life in Christ","C) Jericho","D) Nineveh"]'),
  ('What is the church?', 'God’s people', 'single', 'multiple_choice', '["A) God’s people","B) Peter","C) Daniel","D) Jacob"]'),
  ('Who should Christians love?', 'God and others', 'single', 'multiple_choice', '["A) Samuel","B) God and others","C) Peter","D) Jacob"]'),
  ('What is the greatest commandment?', 'Love God', 'single', 'multiple_choice', '["A) Love God","B) Noah","C) Daniel","D) Aaron"]'),
  ('Who is our neighbor?', 'Anyone God calls us to love', 'single', 'multiple_choice', '["A) Nineveh","B) Jericho","C) Anyone God calls us to love","D) Jerusalem"]'),
  ('What fruit did Adam and Eve eat?', 'The forbidden fruit', 'single', 'multiple_choice', '["A) Samuel","B) Joseph","C) The forbidden fruit","D) Aaron"]'),
  ('What is the wages of sin?', 'Death', 'single', 'multiple_choice', '["A) Paul","B) Aaron","C) Abraham","D) Death"]'),
  ('What is the gift of God?', 'Eternal life in Christ Jesus', 'single', 'multiple_choice', '["A) Egypt","B) Eternal life in Christ Jesus","C) Nineveh","D) Patmos"]'),
  ('What did Jesus say we should do for our enemies?', 'Love them', 'single', 'multiple_choice', '["A) Joseph","B) Elijah","C) Love them","D) Samuel"]'),
  ('What should we do when we sin?', 'Confess and repent', 'single', 'multiple_choice', '["A) Peter","B) Paul","C) David","D) Confess and repent"]'),
  ('What does God look at: appearance or heart?', 'The heart', 'single', 'multiple_choice', '["A) Paul","B) Elijah","C) Moses","D) The heart"]'),
  ('What is the golden rule?', 'Treat others the way you want to be treated', 'single', 'multiple_choice', '["A) Jerusalem","B) Treat others the way you want to be treated","C) Patmos","D) Cana"]'),
  ('What did Jesus say to do with your light?', 'Let it shine', 'single', 'multiple_choice', '["A) John","B) Peter","C) Let it shine","D) Jacob"]'),
  ('What are Christians called to be: salt and what?', 'Light', 'single', 'multiple_choice', '["A) Light","B) Daniel","C) Noah","D) John"]'),
  ('What animal did Jesus ride into Jerusalem?', 'A donkey', 'single', 'multiple_choice', '["A) Noah","B) Peter","C) A donkey","D) John"]'),
  ('What did people wave when Jesus entered Jerusalem?', 'Palm branches', 'single', 'multiple_choice', '["A) Joshua","B) Palm branches","C) David","D) Paul"]'),
  ('What is the day Jesus rose called?', 'Easter or Resurrection Sunday', 'single', 'multiple_choice', '["A) Easter or Resurrection Sunday","B) Patmos","C) Nazareth","D) Egypt"]'),
  ('What is the day Jesus died often called?', 'Good Friday', 'single', 'multiple_choice', '["A) Moses","B) Good Friday","C) Paul","D) Elijah"]'),
  ('What is the first commandment about?', 'Having no other gods before God', 'single', 'multiple_choice', '["A) Cana","B) Nazareth","C) Having no other gods before God","D) Jerusalem"]'),
  ('What commandment says not to steal?', 'You shall not steal', 'single', 'multiple_choice', '["A) Bethlehem","B) Cana","C) You shall not steal","D) Patmos"]'),
  ('What commandment says not to lie?', 'You shall not bear false witness', 'single', 'multiple_choice', '["A) Bethlehem","B) You shall not bear false witness","C) Nineveh","D) Cana"]'),
  ('What commandment says to honor your parents?', 'Honor your father and mother', 'single', 'multiple_choice', '["A) Nineveh","B) Patmos","C) Cana","D) Honor your father and mother"]'),
  ('What is an idol?', 'Anything worshiped instead of God', 'single', 'multiple_choice', '["A) Anything worshiped instead of God","B) Jerusalem","C) Jericho","D) Nineveh"]'),
  ('What did God put in the sky after the flood?', 'A rainbow', 'single', 'multiple_choice', '["A) Noah","B) John","C) Joseph","D) A rainbow"]'),
  ('What did the rainbow remind Noah of?', 'God’s promise', 'single', 'multiple_choice', '["A) Moses","B) Paul","C) Aaron","D) God’s promise"]'),
  ('What was the tower people built to make a name for themselves?', 'The Tower of Babel', 'single', 'multiple_choice', '["A) Cana","B) Jerusalem","C) Nineveh","D) The Tower of Babel"]'),
  ('What happened at Babel?', 'God confused their languages', 'single', 'multiple_choice', '["A) God confused their languages","B) Patmos","C) Nineveh","D) Egypt"]'),
  ('Who was the oldest man in the Bible?', 'Methuselah', 'single', 'multiple_choice', '["A) Aaron","B) Methuselah","C) Peter","D) Daniel"]'),
  ('Who was Abraham’s wife?', 'Sarah', 'single', 'multiple_choice', '["A) John","B) Elijah","C) David","D) Sarah"]'),
  ('Who was Abraham’s nephew?', 'Lot', 'single', 'multiple_choice', '["A) Jacob","B) Peter","C) Aaron","D) Lot"]'),
  ('What city did God destroy in Abraham’s time?', 'Sodom', 'single', 'multiple_choice', '["A) Noah","B) Sodom","C) Joshua","D) Moses"]'),
  ('Who became a pillar of salt?', 'Lot’s wife', 'single', 'multiple_choice', '["A) Elijah","B) Abraham","C) Lot’s wife","D) Samuel"]'),
  ('Who was Isaac’s son who had twelve sons?', 'Jacob', 'single', 'multiple_choice', '["A) John","B) Abraham","C) Jacob","D) Peter"]'),
  ('What did Jacob dream about?', 'A ladder reaching to heaven', 'single', 'multiple_choice', '["A) Bethlehem","B) Patmos","C) Jerusalem","D) A ladder reaching to heaven"]'),
  ('Who was Joseph’s younger brother?', 'Benjamin', 'single', 'multiple_choice', '["A) Paul","B) Benjamin","C) Joseph","D) Aaron"]'),
  ('What did Pharaoh make the Israelites do?', 'Work as slaves', 'single', 'multiple_choice', '["A) Daniel","B) Jacob","C) Work as slaves","D) Aaron"]'),
  ('What did Moses’ staff turn into?', 'A snake', 'single', 'multiple_choice', '["A) Moses","B) A snake","C) Jacob","D) John"]'),
  ('Who spoke for Moses before Pharaoh?', 'Aaron', 'single', 'multiple_choice', '["A) Paul","B) John","C) Moses","D) Aaron"]'),
  ('What did God write the Ten Commandments on?', 'Stone tablets', 'single', 'multiple_choice', '["A) Joshua","B) Abraham","C) Paul","D) Stone tablets"]'),
  ('What was the golden calf?', 'An idol', 'single', 'multiple_choice', '["A) Samuel","B) John","C) Joshua","D) An idol"]'),
  ('What did Israel carry that represented God’s presence?', 'The Ark of the Covenant', 'single', 'multiple_choice', '["A) The Ark of the Covenant","B) Nineveh","C) Nazareth","D) Cana"]'),
  ('Who was the first high priest of Israel?', 'Aaron', 'single', 'multiple_choice', '["A) Abraham","B) Aaron","C) Moses","D) Samuel"]'),
  ('What book tells about Israel leaving Egypt?', 'Exodus', 'single', 'multiple_choice', '["A) Paul","B) Exodus","C) Noah","D) Moses"]'),
  ('What book tells about creation?', 'Genesis', 'single', 'multiple_choice', '["A) Elijah","B) Genesis","C) Aaron","D) Moses"]'),
  ('What were the names of Noah’s three sons?', 'Shem, Ham, Japheth', 'double', 'multiple_choice', '["A) Cain, Abel, Seth","B) Shem, Ham, Japheth","C) Abraham, Isaac, Jacob","D) Peter, James, John"]'),
  ('What city was Abraham originally told to leave?', 'Ur', 'double', 'multiple_choice', '["A) Haran","B) Ur","C) Bethlehem","D) Jericho"]'),
  ('On what mountain was Abraham told to sacrifice Isaac?', 'Moriah', 'double', 'multiple_choice', '["A) Sinai","B) Carmel","C) Moriah","D) Ararat"]'),
  ('How many pieces of silver was Joseph sold for?', 'Twenty', 'double', 'multiple_choice', '["A) Ten","B) Twenty","C) Thirty","D) Forty"]'),
  ('How many years of plenty did Joseph say Egypt would have before famine?', 'Seven', 'double', 'multiple_choice', '["A) Three","B) Five","C) Seven","D) Ten"]'),
  ('What was Moses’ excuse for not wanting to speak for God?', 'He was slow of speech', 'double', 'multiple_choice', '["A) He was too young","B) He was slow of speech","C) He did not know Hebrew","D) He was afraid of water"]'),
  ('What feast began the night Israel left Egypt?', 'Passover', 'double', 'multiple_choice', '["A) Pentecost","B) Purim","C) Passover","D) Tabernacles"]'),
  ('How many times did Israel march around Jericho on the seventh day?', 'Seven times', 'double', 'multiple_choice', '["A) One time","B) Three times","C) Seven times","D) Twelve times"]'),
  ('What was the sign Rahab gave the spies that her family would be protected?', 'A scarlet cord', 'double', 'multiple_choice', '["A) A white cloth","B) A scarlet cord","C) A lamp in the window","D) A branch over the door"]'),
  ('Which judge made a vow that led to tragedy involving his daughter?', 'Jephthah', 'double', 'multiple_choice', '["A) Gideon","B) Samson","C) Jephthah","D) Deborah"]'),
  ('What did Hannah promise to do if God gave her a son?', 'Dedicate him to the Lord', 'double', 'multiple_choice', '["A) Make him king","B) Dedicate him to the Lord","C) Send him to Egypt","D) Give him to Eli as a servant"]'),
  ('What did Solomon ask God for instead of riches and long life?', 'Wisdom', 'double', 'multiple_choice', '["A) Military power","B) Wisdom","C) More land","D) A larger army"]'),
  ('What did Elijah pour over the altar before God sent fire from heaven?', 'Water', 'double', 'multiple_choice', '["A) Oil","B) Wine","C) Water","D) Blood"]'),
  ('How many times did Naaman wash in the Jordan River to be healed?', 'Seven', 'double', 'multiple_choice', '["A) Three","B) Five","C) Seven","D) Ten"]'),
  ('Why was Daniel thrown into the lions’ den?', 'He prayed to God instead of the king', 'double', 'multiple_choice', '["A) He refused to fight in the army","B) He prayed to God instead of the king","C) He would not eat the king’s food","D) He refused to interpret a dream"]'),
  ('What did King Nebuchadnezzar see in the fiery furnace besides the three men?', 'A fourth man walking with them', 'double', 'multiple_choice', '["A) An angel with a sword","B) A fourth man walking with them","C) A pillar of fire","D) A dove above them"]'),
  ('What was Esther’s cousin’s name?', 'Mordecai', 'double', 'multiple_choice', '["A) Ezra","B) Mordecai","C) Nehemiah","D) Zerubbabel"]'),
  ('What job did Nehemiah have before he rebuilt Jerusalem’s wall?', 'Cupbearer', 'double', 'multiple_choice', '["A) Priest","B) Cupbearer","C) Soldier","D) Merchant"]'),
  ('What did Jonah do after God told him to preach to Nineveh?', 'He ran toward Tarshish', 'double', 'multiple_choice', '["A) He went immediately","B) He ran toward Tarshish","C) He asked Elijah for help","D) He hid in Jerusalem"]'),
  ('What did God use to prepare Jonah for preaching to Nineveh?', 'A great fish', 'double', 'multiple_choice', '["A) A burning bush","B) A great fish","C) A pillar of cloud","D) An angel army"]'),
  ('What book of the Bible comes immediately after Judges?', 'Ruth', 'double', 'multiple_choice', '["A) Joshua","B) Ruth","C) 1 Samuel","D) 1 Kings"]'),
  ('Which prophet confronted King David over his sin with Bathsheba?', 'Nathan', 'double', 'multiple_choice', '["A) Samuel","B) Nathan","C) Elijah","D) Isaiah"]'),
  ('What was Jacob’s name changed to after wrestling with God?', 'Israel', 'double', 'multiple_choice', '["A) Judah","B) Israel","C) Benjamin","D) Levi"]'),
  ('What was the name of the Babylonian king who threw Daniel’s friends into the fiery furnace?', 'Nebuchadnezzar', 'double', 'multiple_choice', '["A) Darius","B) Nebuchadnezzar","C) Cyrus","D) Ahasuerus"]'),
  ('What prophet was known as the “weeping prophet”?', 'Jeremiah', 'double', 'multiple_choice', '["A) Isaiah","B) Jeremiah","C) Ezekiel","D) Hosea"]'),
  ('What did the angel tell Joseph to name Mary’s child?', 'Jesus', 'double', 'multiple_choice', '["A) Emmanuel","B) Jesus","C) John","D) Joshua"]'),
  ('What did the wise men follow to find Jesus?', 'A star', 'double', 'multiple_choice', '["A) A pillar of fire","B) A star","C) An angel","D) A cloud"]'),
  ('You of little faith, why did you doubt?', 'false', 'double', 'open_answer', null),
  ('What did Zacchaeus promise to do after meeting Jesus?', 'Give half his possessions to the poor and repay people', 'double', 'multiple_choice', '["A) Become a disciple","B) Give half his possessions to the poor and repay people","C) Leave Jericho forever","D) Sell his house to the temple"]'),
  ('Which disciple cut off the servant’s ear when Jesus was arrested?', 'Peter', 'double', 'multiple_choice', '["A) John","B) Peter","C) James","D) Andrew"]'),
  ('Who was released instead of Jesus?', 'Barabbas', 'double', 'multiple_choice', '["A) Nicodemus","B) Barabbas","C) Simon of Cyrene","D) Joseph of Arimathea"]'),
  ('What did Thomas say he needed to see before he would believe Jesus had risen?', 'Jesus’ wounds', 'double', 'multiple_choice', '["A) Jesus’ crown","B) Jesus’ wounds","C) Jesus’ tomb","D) Jesus’ robe"]'),
  ('Who preached the sermon at Pentecost?', 'Peter', 'double', 'multiple_choice', '["A) Paul","B) Peter","C) John","D) James"]'),
  ('What appeared over the believers at Pentecost?', 'Tongues of fire', 'double', 'multiple_choice', '["A) A rainbow","B) Tongues of fire","C) A dove","D) A bright star"]'),
  ('Who was sent to pray for Saul so he could regain his sight?', 'Ananias', 'double', 'multiple_choice', '["A) Barnabas","B) Ananias","C) Timothy","D) Silas"]'),
  ('What happened to Paul and Silas while they were praying and singing in prison?', 'An earthquake opened the doors', 'double', 'multiple_choice', '["A) An angel opened the prison","B) An earthquake opened the doors","C) The guards released them","D) The governor pardoned them"]'),
  ('What was the name of the woman who sold purple cloth and helped Paul in Philippi?', 'Lydia', 'double', 'multiple_choice', '["A) Priscilla","B) Lydia","C) Dorcas","D) Martha"]'),
  ('On what island did John receive the vision recorded in Revelation?', 'Patmos', 'double', 'multiple_choice', '["A) Crete","B) Patmos","C) Cyprus","D) Malta"]'),
  ('What was the name of the young man who fell from a window while Paul was preaching?', 'Eutychus', 'double', 'multiple_choice', '["A) Eutychus","B) Timothy","C) Tychicus","D) Onesimus"]'),
  ('What did the Ethiopian official ask Philip to explain to him?', 'A passage from Isaiah', 'double', 'multiple_choice', '["A) The Ten Commandments","B) A passage from Isaiah","C) The book of Genesis","D) The story of David"]'),
  ('Who was Cornelius?', 'A Roman centurion', 'double', 'multiple_choice', '["A) A Jewish priest","B) A Roman centurion","C) A Pharisee","D) A governor"]'),
  ('What did Peter see in his vision before visiting Cornelius?', 'A sheet with animals', 'double', 'multiple_choice', '["A) A burning bush","B) A sheet with animals","C) A ladder to heaven","D) A bowl of manna"]'),
  ('What book comes immediately after the four Gospels?', 'Acts', 'double', 'multiple_choice', '["A) Romans","B) Acts","C) Revelation","D) Hebrews"]'),
  ('Which Gospel records the story of the Good Samaritan?', 'Luke', 'double', 'multiple_choice', '["A) Matthew","B) Mark","C) Luke","D) John"]'),
  ('Which Gospel records the raising of Lazarus?', 'John', 'double', 'multiple_choice', '["A) Matthew","B) Mark","C) Luke","D) John"]'),
  ('What city was Paul in when he gave a speech about the “unknown god”?', 'Athens', 'double', 'multiple_choice', '["A) Corinth","B) Athens","C) Ephesus","D) Philippi"]'),
  ('Who was the Roman governor who kept Paul in custody and listened to him?', 'Felix', 'double', 'multiple_choice', '["A) Felix","B) Pilate","C) Festus","D) Herod"]'),
  ('What was the name of the runaway slave Paul wrote about in Philemon?', 'Onesimus', 'double', 'multiple_choice', '["A) Onesimus","B) Tychicus","C) Demas","D) Titus"]'),
  ('Which church received Paul’s letter about the armor of God?', 'Ephesians', 'double', 'multiple_choice', '["A) Philippians","B) Ephesians","C) Galatians","D) Colossians"]'),
  ('What did Jesus say was the greatest commandment?', 'Love the Lord your God with all your heart', 'double', 'multiple_choice', '["A) Love your neighbor as yourself","B) Love the Lord your God with all your heart","C) Keep the Sabbath holy","D) Honor your father and mother"]'),
  ('Where did Jesus ascend to after His resurrection?', 'Heaven', 'double', 'multiple_choice', '["A) Jerusalem","B) Mount Sinai","C) Heaven","D) Galilee"]'),
  ('What event happened fifty days after Passover?', 'Pentecost', 'double', 'multiple_choice', '["A) Pentecost","B) Passover","C) Purim","D) Hanukkah"]'),
  ('Who preached the first sermon at Pentecost?', 'Peter', 'double', 'multiple_choice', '["A) John","B) Peter","C) Paul","D) James"]'),
  ('What came upon the believers at Pentecost?', 'The Holy Spirit', 'double', 'multiple_choice', '["A) Fire from heaven","B) Angels","C) The Holy Spirit","D) A cloud"]'),
  ('What was Saul''s new name after becoming a Christian?', 'Paul', 'double', 'multiple_choice', '["A) Peter","B) Silas","C) Paul","D) Barnabas"]'),
  ('On what road did Jesus appear to Saul?', 'Damascus Road', 'double', 'multiple_choice', '["A) Jericho Road","B) Damascus Road","C) Roman Road","D) Emmaus Road"]'),
  ('Who traveled with Paul on many missionary journeys?', 'Barnabas', 'double', 'multiple_choice', '["A) Timothy","B) Barnabas","C) Peter","D) Luke"]'),
  ('What was Paul''s occupation before following Jesus?', 'Pharisee', 'double', 'multiple_choice', '["A) Fisherman","B) Tax collector","C) Pharisee","D) Carpenter"]'),
  ('What was Paul''s occupation for work?', 'Tentmaker', 'double', 'multiple_choice', '["A) Blacksmith","B) Shepherd","C) Tentmaker","D) Carpenter"]'),
  ('What was the name of the jailer who believed after the earthquake?', 'The Philippian jailer', 'double', 'multiple_choice', '["A) Cornelius","B) Felix","C) The Philippian jailer","D) Crispus"]'),
  ('Who wrote the book of Revelation?', 'John', 'double', 'multiple_choice', '["A) Peter","B) Paul","C) John","D) Luke"]'),
  ('On what island was John when he received Revelation?', 'Patmos', 'double', 'multiple_choice', '["A) Crete","B) Cyprus","C) Malta","D) Patmos"]'),
  ('What city walls fell after Israel marched around them?', 'Jericho', 'double', 'multiple_choice', '["A) Jerusalem","B) Ai","C) Jericho","D) Nineveh"]'),
  ('How many days did Israel march around Jericho before the walls fell?', 'Seven days', 'double', 'multiple_choice', '["A) Three","B) Five","C) Seven","D) Ten"]'),
  ('Who helped the Israelite spies in Jericho?', 'Rahab', 'double', 'multiple_choice', '["A) Esther","B) Ruth","C) Rahab","D) Deborah"]'),
  ('What sign did Rahab place in her window?', 'Scarlet cord', 'double', 'multiple_choice', '["A) White cloth","B) Scarlet cord","C) Olive branch","D) Lamp"]'),
  ('What did Moses see burning but not consumed?', 'A bush', 'double', 'multiple_choice', '["A) A tree","B) An altar","C) A bush","D) A scroll"]'),
  ('What sea did God part through Moses?', 'Red Sea', 'double', 'multiple_choice', '["A) Dead Sea","B) Mediterranean Sea","C) Sea of Galilee","D) Red Sea"]'),
  ('What food fell from heaven for Israel?', 'Manna', 'double', 'multiple_choice', '["A) Quail","B) Bread","C) Manna","D) Figs"]'),
  ('What did Moses strike to bring out water?', 'A rock', 'double', 'multiple_choice', '["A) A tree","B) A rock","C) A well","D) A mountain"]'),
  ('Where did Moses receive the Ten Commandments?', 'Mount Sinai', 'double', 'multiple_choice', '["A) Mount Carmel","B) Mount Zion","C) Mount Sinai","D) Mount Ararat"]'),
  ('What idol did Israel make while Moses was on the mountain?', 'Golden calf', 'double', 'multiple_choice', '["A) Golden calf","B) Golden eagle","C) Silver serpent","D) Bronze sheep"]'),
  ('What was kept inside the Ark of the Covenant?', 'The Ten Commandments', 'double', 'multiple_choice', '["A) Aaron''s robe","B) The Ten Commandments","C) David''s harp","D) Solomon''s crown"]'),
  ('Who was the first king of Israel?', 'Saul', 'double', 'multiple_choice', '["A) David","B) Solomon","C) Saul","D) Samuel"]'),
  ('Who became king after Saul?', 'David', 'double', 'multiple_choice', '["A) Samuel","B) David","C) Solomon","D) Jonathan"]'),
  ('Who became king after David?', 'Solomon', 'double', 'multiple_choice', '["A) Saul","B) Rehoboam","C) Solomon","D) Absalom"]'),
  ('What did Solomon ask God for?', 'Wisdom', 'double', 'multiple_choice', '["A) Riches","B) Power","C) Wisdom","D) Long life"]'),
  ('Who built the first temple in Jerusalem?', 'Solomon', 'double', 'multiple_choice', '["A) David","B) Saul","C) Solomon","D) Zerubbabel"]'),
  ('Who challenged the prophets of Baal on Mount Carmel?', 'Elijah', 'double', 'multiple_choice', '["A) Elisha","B) Isaiah","C) Elijah","D) Jeremiah"]'),
  ('How did God take Elijah to heaven?', 'Whirlwind', 'double', 'multiple_choice', '["A) Chariot of fire","B) Whirlwind","C) Angel","D) Cloud"]'),
  ('Who became prophet after Elijah?', 'Elisha', 'double', 'multiple_choice', '["A) Isaiah","B) Elisha","C) Ezekiel","D) Amos"]'),
  ('What happened when Elisha prayed for Naaman?', 'He was healed of leprosy', 'double', 'multiple_choice', '["A) He became rich","B) He became king","C) He was healed of leprosy","D) He crossed the Jordan"]'),
  ('Who was thrown into a lions'' den?', 'Daniel', 'double', 'multiple_choice', '["A) Jeremiah","B) Daniel","C) Ezekiel","D) Nehemiah"]'),
  ('Why was Daniel thrown into the lions'' den?', 'He prayed to God', 'double', 'multiple_choice', '["A) He stole from the king","B) He refused to bow","C) He prayed to God","D) He fought soldiers"]'),
  ('Who were thrown into the fiery furnace?', 'Shadrach, Meshach, and Abednego', 'double', 'multiple_choice', '["A) Peter, James, John","B) Cain, Abel, Seth","C) Shadrach, Meshach, Abednego","D) Moses, Aaron, Miriam"]'),
  ('How many men did the king see walking in the furnace?', 'Four', 'double', 'multiple_choice', '["A) Three","B) Four","C) Five","D) Six"]'),
  ('Who became queen and saved the Jewish people?', 'Esther', 'double', 'multiple_choice', '["A) Ruth","B) Deborah","C) Esther","D) Hannah"]'),
  ('Who advised Esther to help her people?', 'Mordecai', 'double', 'multiple_choice', '["A) Ezra","B) Daniel","C) Mordecai","D) Nehemiah"]'),
  ('Who rebuilt Jerusalem''s wall?', 'Nehemiah', 'double', 'multiple_choice', '["A) Ezra","B) Nehemiah","C) Zerubbabel","D) Joshua"]'),
  ('What job did Nehemiah have before rebuilding the wall?', 'Cupbearer', 'double', 'multiple_choice', '["A) Shepherd","B) Priest","C) Cupbearer","D) Soldier"]'),
  ('Who was Samuel''s mother?', 'Hannah', 'double', 'multiple_choice', '["A) Sarah","B) Hannah","C) Rachel","D) Naomi"]'),
  ('What did Hannah pray for?', 'A son', 'double', 'multiple_choice', '["A) Wealth","B) A husband","C) A son","D) Land"]'),
  ('Who anointed David as king?', 'Samuel', 'double', 'multiple_choice', '["A) Nathan","B) Elijah","C) Samuel","D) Gad"]'),
  ('What instrument did David play for Saul?', 'Harp', 'double', 'multiple_choice', '["A) Flute","B) Harp","C) Trumpet","D) Drum"]'),
  ('Who was David''s best friend?', 'Jonathan', 'double', 'multiple_choice', '["A) Samuel","B) Jonathan","C) Abner","D) Joab"]'),
  ('What relationship was Jonathan to Saul?', 'His son', 'double', 'multiple_choice', '["A) Brother","B) Cousin","C) Son","D) Servant"]'),
  ('What did Joseph''s brothers do to him?', 'Sold him into slavery', 'double', 'multiple_choice', '["A) Made him king","B) Sold him into slavery","C) Sent him home","D) Made him ruler"]'),
  ('What country was Joseph taken to?', 'Egypt', 'double', 'multiple_choice', '["A) Babylon","B) Assyria","C) Egypt","D) Moab"]'),
  ('What position did Joseph eventually hold in Egypt?', 'Second in command', 'double', 'multiple_choice', '["A) Pharaoh","B) High Priest","C) Second in command","D) General"]'),
  ('What gift did Joseph have from God?', 'Interpreting dreams', 'double', 'multiple_choice', '["A) Healing","B) Interpreting dreams","C) Prophecy","D) Music"]'),
  ('What did Pharaoh dream about that Joseph interpreted?', 'Cows and grain', 'double', 'multiple_choice', '["A) Stars and moons","B) Sheep and goats","C) Cows and grain","D) Rivers and fish"]'),
  ('Who wrestled with God and had his name changed?', 'Jacob', 'double', 'multiple_choice', '["A) Isaac","B) Abraham","C) Jacob","D) Joseph"]'),
  ('What was Jacob''s new name?', 'Israel', 'double', 'multiple_choice', '["A) Judah","B) Israel","C) Benjamin","D) Levi"]'),
  ('What did Esau sell for a bowl of stew?', 'His birthright', 'double', 'multiple_choice', '["A) His inheritance","B) His birthright","C) His flock","D) His blessing"]'),
  ('What was Abraham willing to sacrifice?', 'Isaac', 'double', 'multiple_choice', '["A) Jacob","B) Joseph","C) Isaac","D) Ishmael"]'),
  ('What animal did God provide instead?', 'A ram', 'double', 'multiple_choice', '["A) Lamb","B) Goat","C) Ram","D) Dove"]'),
  ('What promise did God make to Abraham?', 'He would become a great nation', 'double', 'multiple_choice', '["A) He would become a king","B) He would become a great nation","C) He would build a temple","D) He would rule Egypt"]'),
  ('What happened at the Tower of Babel?', 'God confused the languages', 'double', 'multiple_choice', '["A) A flood came","B) God confused the languages","C) Fire fell from heaven","D) A wall collapsed"]'),
  ('Why did God send the flood in Noah''s day?', 'Wickedness filled the earth', 'double', 'multiple_choice', '["A) Drought","B) Wickedness filled the earth","C) Famine","D) Idolatry in Egypt"]'),
  ('What did Noah build?', 'An ark', 'double', 'multiple_choice', '["A) Temple","B) Tower","C) Ark","D) Altar"]'),
  ('How many of most animals entered the ark?', 'Two', 'double', 'multiple_choice', '["A) One","B) Two","C) Seven","D) Twelve"]'),
  ('What bird returned with an olive leaf?', 'A dove', 'double', 'multiple_choice', '["A) Raven","B) Sparrow","C) Dove","D) Eagle"]'),
  ('What is the greatest commandment according to Jesus?', 'Love God', 'double', 'multiple_choice', '["A) Love your neighbor","B) Honor your parents","C) Love God","D) Do not steal"]'),
  ('What is the second greatest commandment?', 'Love your neighbor', 'double', 'multiple_choice', '["A) Pray always","B) Love your neighbor","C) Honor your parents","D) Keep the Sabbath"]'),
  ('What is the shortest verse in the Bible?', 'Jesus wept', 'double', 'multiple_choice', '["A) Pray without ceasing","B) God is love","C) Jesus wept","D) Rejoice always"]'),
  ('What book contains the Ten Commandments?', 'Exodus', 'double', 'multiple_choice', '["A) Genesis","B) Exodus","C) Leviticus","D) Numbers"]'),
  ('Which book comes immediately after Genesis?', 'Exodus', 'double', 'multiple_choice', '["A) Leviticus","B) Numbers","C) Exodus","D) Deuteronomy"]'),
  ('Which Gospel was written by a doctor?', 'Luke', 'double', 'multiple_choice', '["A) Matthew","B) Mark","C) Luke","D) John"]'),
  ('Who climbed a sycamore tree to see Jesus?', 'Zacchaeus', 'double', 'multiple_choice', '["A) Matthew","B) Nicodemus","C) Zacchaeus","D) Bartimaeus"]'),
  ('What was the occupation of Peter before following Jesus?', 'Fisherman', 'double', 'multiple_choice', '["A) Carpenter","B) Fisherman","C) Tax collector","D) Shepherd"]'),
  ('What was the name of the high priest who questioned Jesus?', 'Caiaphas', 'double', 'multiple_choice', '["A) Caiaphas","B) Annas","C) Herod","D) Gamaliel"]'),
  ('What was written above Jesus on the cross?', 'King of the Jews', 'double', 'multiple_choice', '["A) King of Israel","B) Son of David","C) King of the Jews","D) Messiah"]'),
  ('What was the name of Abraham’s nephew who lived in Sodom?', 'Lot', 'triple', 'open_answer', null),
  ('What did Jacob use as a pillow when he dreamed of a stairway to heaven?', 'A stone', 'triple', 'open_answer', null),
  ('What was the name of Joseph’s younger brother?', 'Benjamin', 'triple', 'open_answer', null),
  ('What did Joseph’s brothers dip his coat in to deceive Jacob?', 'Goat’s blood', 'triple', 'open_answer', null),
  ('What object did Pharaoh’s daughter use to find Moses as a baby?', 'A basket', 'triple', 'open_answer', null),
  ('What was the first plague God sent on Egypt?', 'Water turned to blood', 'triple', 'open_answer', null),
  ('What did God provide for Israel to eat in the wilderness besides manna?', 'Quail', 'triple', 'open_answer', null),
  ('What did Moses lift up in the wilderness so the Israelites could be healed from snake bites?', 'A bronze serpent', 'triple', 'open_answer', null),
  ('What city did Joshua send spies into before Israel attacked it after Jericho?', 'Ai', 'triple', 'open_answer', null),
  ('What judge led Israel before Barak fought Sisera?', 'Deborah', 'triple', 'open_answer', null),
  ('What was the name of the woman who killed Sisera with a tent peg?', 'Jael', 'triple', 'open_answer', null),
  ('What food did Ruth gather in Boaz’s fields?', 'Grain', 'triple', 'open_answer', null),
  ('What was the name of Ruth’s husband after she married into Israel?', 'Boaz', 'triple', 'open_answer', null),
  ('What did Saul lose after he disobeyed God by not fully destroying the Amalekites?', 'His kingdom', 'triple', 'open_answer', null),
  ('What prophet confronted King Ahab over Naboth’s vineyard?', 'Elijah', 'triple', 'open_answer', null),
  ('What did Elisha make float for a man who lost it in the water?', 'An axe head', 'triple', 'open_answer', null),
  ('What king found the Book of the Law while the temple was being repaired?', 'Josiah', 'triple', 'open_answer', null),
  ('What city was destroyed after Jonah warned its people and they repented?', 'Nineveh was spared', 'triple', 'open_answer', null),
  ('What king ordered the rebuilding of the temple after the exile?', 'Cyrus', 'triple', 'open_answer', null),
  ('What prophet saw a valley of dry bones come to life?', 'Ezekiel', 'triple', 'open_answer', null),
  ('What Old Testament prophet wrote, “The righteous shall live by faith”?', 'Habakkuk', 'triple', 'open_answer', null),
  ('What book comes immediately after 2 Kings?', '1 Chronicles', 'triple', 'open_answer', null),
  ('What book comes immediately before Psalms?', 'Job', 'triple', 'open_answer', null),
  ('What is the shortest book in the Old Testament?', 'Obadiah', 'triple', 'open_answer', null),
  ('What is the final book of the Old Testament?', 'Malachi', 'triple', 'open_answer', null),
  ('What elderly man recognized Jesus in the temple and said he had seen God’s salvation?', 'Simeon', 'triple', 'open_answer', null),
  ('What prophetess spoke about Jesus after seeing Him as a baby in the temple?', 'Anna', 'triple', 'open_answer', null),
  ('What was the name of the ruler whose daughter Jesus raised from the dead?', 'Jairus', 'triple', 'open_answer', null),
  ('What blind man shouted for Jesus near Jericho?', 'Bartimaeus', 'triple', 'open_answer', null),
  ('What did Jesus tell the rich young ruler he still lacked?', 'To sell what he had, give to the poor, and follow Jesus', 'triple', 'open_answer', null),
  ('What did Jesus use to wash His disciples’ feet at the Last Supper?', 'A towel and basin of water', 'triple', 'open_answer', null),
  ('Which disciple was known as “the twin”?', 'Thomas', 'triple', 'open_answer', null),
  ('What was the name of the servant whose ear Jesus healed after Peter cut it off?', 'Malchus', 'triple', 'open_answer', null),
  ('What prisoner was crucified beside Jesus and asked Him to remember him?', 'The repentant thief', 'triple', 'open_answer', null),
  ('What did Jesus tell Mary Magdalene outside the empty tomb that made her recognize Him?', 'Her name, “Mary”', 'triple', 'open_answer', null),
  ('What town were two disciples walking toward when Jesus joined them after the resurrection?', 'Emmaus', 'triple', 'open_answer', null),
  ('Who was chosen to replace Judas after the apostles prayed and cast lots?', 'Matthias', 'triple', 'open_answer', null),
  ('What couple lied about money from a land sale and died?', 'Ananias and Sapphira', 'triple', 'open_answer', null),
  ('What deacon explained Scripture to the Ethiopian official?', 'Philip', 'triple', 'open_answer', null),
  ('What city were believers first called Christians?', 'Antioch', 'triple', 'open_answer', null),
  ('What was the name of the sorcerer who tried to buy the power of the Holy Spirit?', 'Simon', 'triple', 'open_answer', null),
  ('What city did Paul and Barnabas first travel to on their missionary work after leaving Antioch?', 'Seleucia', 'triple', 'open_answer', null),
  ('What was the name of the man Paul healed in Lystra who had never walked?', 'A man lame from birth', 'triple', 'open_answer', null),
  ('What was the name of the silversmith who started a riot against Paul in Ephesus?', 'Demetrius', 'triple', 'open_answer', null),
  ('What city did Paul write the letter to the Romans from, according to most scholars?', 'Corinth', 'triple', 'open_answer', null),
  ('What church did Paul tell to “put on the full armor of God”?', 'The church in Ephesus', 'triple', 'open_answer', null),
  ('What book contains the verse “Faith without works is dead”?', 'James', 'triple', 'open_answer', null),
  ('What New Testament book was written to a man named Theophilus?', 'Luke and Acts', 'triple', 'open_answer', null),
  ('What church in Revelation was told it was “lukewarm”?', 'Laodicea', 'triple', 'open_answer', null),
  ('What city in Revelation was told it had “abandoned the love you had at first”?', 'Ephesus', 'triple', 'open_answer', null),
  ('What does the word Gospel mean?', 'Good News', 'triple', 'open_answer', null),
  ('What are the four living creatures around God’s throne in Revelation commonly described as?', 'A lion, an ox/calf, a man, and a flying eagle', 'home_run', 'open_answer', null),
  ('What are the five books traditionally attributed to John?', 'Gospel of John, 1 John, 2 John, 3 John, Revelation', 'home_run', 'open_answer', null),
  ('What are the seven “I am” statements of Jesus in the Gospel of John?', 'Bread of life, light of the world, gate/door, good shepherd, resurrection and the life, way truth and life, true vine', 'home_run', 'open_answer', null),
  ('Moses led Israel out of Egypt. Who led them into Canaan?', 'Joshua', 'home_run', 'open_answer', null),
  ('David defeated Goliath. Who defeated the prophets of Baal?', 'Elijah', 'home_run', 'open_answer', null),
  ('Who replaced Judas Iscariot among the apostles?', 'Matthias', 'home_run', 'open_answer', null),
  ('What book contains the Sermon on the Mount?', 'Matthew', 'home_run', 'open_answer', null),
  ('What chapter contains the Hall of Faith?', 'Hebrews 11', 'home_run', 'open_answer', null),
  ('What Psalm begins "The Lord is my shepherd"?', 'Psalm 23', 'home_run', 'open_answer', null),
  ('What chapter contains the Love Chapter?', '1 Corinthians 13', 'home_run', 'open_answer', null),
  ('What chapter contains the Fruit of the Spirit?', 'Galatians 5', 'home_run', 'open_answer', null),
  ('Which prophet confronted David about Bathsheba?', 'Nathan', 'home_run', 'open_answer', null),
  ('Which judge defeated Midian with 300 men?', 'Gideon', 'home_run', 'open_answer', null),
  ('Which prophet was taken to heaven in a whirlwind?', 'Elijah', 'home_run', 'open_answer', null),
  ('Which prophet followed Elijah?', 'Elisha', 'home_run', 'open_answer', null),
  ('Which disciple was a tax collector?', 'Matthew', 'home_run', 'open_answer', null),
  ('Which disciple doubted Jesus'' resurrection?', 'Thomas', 'home_run', 'open_answer', null),
  ('Which disciple denied Jesus three times?', 'Peter', 'home_run', 'open_answer', null),
  ('Which disciple betrayed Jesus?', 'Judas Iscariot', 'home_run', 'open_answer', null),
  ('Which king threw Daniel into the lions'' den?', 'Darius', 'home_run', 'open_answer', null),
  ('Which king built the temple?', 'Solomon', 'home_run', 'open_answer', null),
  ('Which queen saved the Jewish people?', 'Esther', 'home_run', 'open_answer', null),
  ('Which governor sentenced Jesus to death?', 'Pontius Pilate', 'home_run', 'open_answer', null),
  ('What city did Jonah preach to?', 'Nineveh', 'home_run', 'open_answer', null),
  ('What city''s walls fell after marching around them?', 'Jericho', 'home_run', 'open_answer', null),
  ('What city was Jesus born in?', 'Bethlehem', 'home_run', 'open_answer', null),
  ('What city did Jesus grow up in?', 'Nazareth', 'home_run', 'open_answer', null),
  ('What mountain did Moses receive the Ten Commandments on?', 'Mount Sinai', 'home_run', 'open_answer', null),
  ('What mountain did Elijah challenge the prophets of Baal on?', 'Mount Carmel', 'home_run', 'open_answer', null),
  ('What river was Jesus baptized in?', 'Jordan River', 'home_run', 'open_answer', null),
  ('What river did Israel cross into the Promised Land?', 'Jordan River', 'home_run', 'open_answer', null),
  ('How many years did Israel wander in the wilderness?', '40', 'home_run', 'open_answer', null),
  ('How many disciples did Jesus choose?', '12', 'home_run', 'open_answer', null),
  ('How many days did Jesus fast in the wilderness?', '40', 'home_run', 'open_answer', null),
  ('How many days was Jonah in the fish?', '3 days and 3 nights', 'home_run', 'open_answer', null),
  ('How many loaves and fish fed the 5,000?', '5 loaves and 2 fish', 'home_run', 'open_answer', null),
  ('How many people were on Noah''s ark from his family?', '8', 'home_run', 'open_answer', null),
  ('What miracle happened at Cana?', 'Water turned into wine', 'home_run', 'open_answer', null),
  ('What happened on the Day of Pentecost?', 'The Holy Spirit came upon believers', 'home_run', 'open_answer', null),
  ('What happened to Saul on the Damascus Road?', 'He encountered Jesus and was blinded', 'home_run', 'open_answer', null),
  ('What happened to Ananias and Sapphira after lying?', 'They died', 'home_run', 'open_answer', null),
  ('What happened to Lazarus after four days in the tomb?', 'Jesus raised him', 'home_run', 'open_answer', null),
  ('Which two commandments did Jesus say were greatest?', 'Love God and Love Your Neighbor', 'home_run', 'open_answer', null),
  ('What are the two ordinances most churches practice?', 'Baptism and Communion', 'home_run', 'open_answer', null),
  ('What are the two parts of the Bible?', 'Old Testament and New Testament', 'home_run', 'open_answer', null),
  ('What are the two greatest themes of the Bible?', 'God''s glory and redemption through Christ', 'home_run', 'open_answer', null)
  returning id, difficulty
)
insert into question_game_uses (question_id, game_type, role)
select id, 'bible_baseball', difficulty from inserted;
