-- v10 migration — True or False Showdown question bank.
-- Feeds the True or False Showdown game (last student standing).
-- Safe to run on live data (idempotent): existing statements are skipped.
--
-- answer = true  => the statement is TRUE.
-- Difficulty mix is ~1:3:1 (easy:medium:hard).

create table if not exists tf_questions (
  id uuid primary key default gen_random_uuid(),
  statement text not null,
  answer boolean not null,                     -- true = the statement is TRUE
  difficulty text not null default 'medium',   -- easy | medium | hard
  testament text,                              -- OT | NT | null
  reference text,                              -- e.g. 'John 3:16'
  explanation text,                            -- the correction / note, for the leader
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Unique statement lets the seed below be re-run safely (on conflict do nothing).
create unique index if not exists tf_questions_statement_key on tf_questions (statement);
create index if not exists tf_questions_active_idx on tf_questions (active, difficulty);

-- RLS disabled to match the other game tables (see gtf_questions / game_prompts).
alter table tf_questions disable row level security;

-- Seed the 200-question bank. Re-running is safe: existing statements are skipped.
insert into tf_questions (statement, answer, difficulty, testament, reference, explanation) values
  ('Jesus was born in Bethlehem.', true, 'easy', 'NT', 'Luke 2:4-7', 'Jesus was born in Bethlehem of Judea.'),
  ('Noah built an ark to survive the great flood.', true, 'easy', 'OT', 'Genesis 6-7', 'God told him to build it.'),
  ('Jonah was swallowed by a great fish.', true, 'easy', 'OT', 'Jonah 1:17', 'He was inside three days and three nights.'),
  ('David defeated Goliath with a sling and a stone.', true, 'easy', 'OT', '1 Samuel 17', 'A single stone struck the giant down.'),
  ('God parted the Red Sea for Moses and the Israelites.', true, 'easy', 'OT', 'Exodus 14', 'They crossed on dry ground.'),
  ('Jesus had twelve disciples.', true, 'easy', 'NT', 'Matthew 10:1-4', 'Twelve were chosen.'),
  ('Jesus turned water into wine.', true, 'easy', 'NT', 'John 2', 'His first miracle, at a wedding in Cana.'),
  ('Daniel was thrown into a den of lions.', true, 'easy', 'OT', 'Daniel 6', 'God shut the lions'' mouths.'),
  ('Joseph was given a coat of many colors by his father.', true, 'easy', 'OT', 'Genesis 37', 'A richly ornamented robe.'),
  ('The Ten Commandments were given to Moses.', true, 'easy', 'OT', 'Exodus 20', 'On Mount Sinai, on tablets of stone.'),
  ('Jesus rose from the dead on the third day.', true, 'easy', 'NT', 'Luke 24', 'The tomb was found empty.'),
  ('Peter denied knowing Jesus three times.', true, 'easy', 'NT', 'Luke 22', 'Before the rooster crowed.'),
  ('Jesus walked on water.', true, 'easy', 'NT', 'Matthew 14', 'On the Sea of Galilee.'),
  ('Jesus fed over 5,000 people with five loaves and two fish.', true, 'easy', 'NT', 'John 6', 'Twelve baskets of leftovers remained.'),
  ('John the Baptist baptized Jesus.', true, 'easy', 'NT', 'Matthew 3', 'In the Jordan River.'),
  ('Solomon was known for his wisdom.', true, 'easy', 'OT', '1 Kings 3', 'He asked God for it.'),
  ('Abraham was willing to sacrifice his son Isaac.', true, 'easy', 'OT', 'Genesis 22', 'God provided a ram instead.'),
  ('The first book of the Bible is Genesis.', true, 'easy', 'OT', 'Genesis 1', '''In the beginning...'''),
  ('Judas Iscariot betrayed Jesus.', true, 'easy', 'NT', 'Matthew 26', 'For thirty pieces of silver.'),
  ('God set a rainbow in the sky as a sign of his promise after the flood.', true, 'easy', 'OT', 'Genesis 9', 'Never again to flood the whole earth.'),
  ('God created the whole world in seven days.', false, 'easy', 'OT', 'Genesis 1-2', 'He created in six days and rested on the seventh.'),
  ('The Bible names the forbidden fruit in Eden as an apple.', false, 'easy', 'OT', 'Genesis 3', 'The fruit is never identified as an apple.'),
  ('Jesus had eleven disciples.', false, 'easy', 'NT', 'Matthew 10:1-4', 'He had twelve.'),
  ('Goliath defeated David in battle.', false, 'easy', 'OT', '1 Samuel 17', 'David defeated Goliath.'),
  ('The Bible says exactly three wise men visited Jesus.', false, 'easy', 'NT', 'Matthew 2', 'The number is never given; only three gifts are named.'),
  ('Peter and John were Jesus'' younger brothers.', false, 'easy', 'NT', 'Matthew 10', 'They were disciples, not his brothers.'),
  ('Jesus was born in a royal palace.', false, 'easy', 'NT', 'Luke 2', 'He was laid in a manger.'),
  ('The last book of the Bible is Genesis.', false, 'easy', 'NT', 'Revelation 22', 'The last book is Revelation.'),
  ('Moses wrote the book of Revelation.', false, 'easy', 'NT', 'Revelation 1', 'It is traditionally attributed to John.'),
  ('Adam and Eve had a son named Goliath.', false, 'easy', 'OT', 'Genesis 4', 'Their sons were Cain, Abel, and Seth.'),
  ('Jesus was baptized by his disciple Peter.', false, 'easy', 'NT', 'Matthew 3', 'He was baptized by John the Baptist.'),
  ('Samson was famous for being the wisest man alive.', false, 'easy', 'OT', 'Judges 16', 'He was famous for his great strength.'),
  ('Noah''s ark came to rest on Mount Sinai.', false, 'easy', 'OT', 'Genesis 8:4', 'It rested on the mountains of Ararat.'),
  ('There were five commandments given to Moses.', false, 'easy', 'OT', 'Exodus 20', 'There were ten.'),
  ('Jonah stayed inside the great fish for three weeks.', false, 'easy', 'OT', 'Jonah 1:17', 'It was three days and three nights.'),
  ('Mary was the mother of Moses.', false, 'easy', 'NT', 'Luke 1', 'Mary was the mother of Jesus.'),
  ('Jesus turned wine into water at a wedding.', false, 'easy', 'NT', 'John 2', 'He turned water into wine.'),
  ('David was the first king of Israel.', false, 'easy', 'OT', '1 Samuel 10', 'Saul was first; David was second.'),
  ('The wise men brought the baby Jesus toys and new clothes.', false, 'easy', 'NT', 'Matthew 2:11', 'They brought gold, frankincense, and myrrh.'),
  ('Jesus was crucified in the town of Bethlehem.', false, 'easy', 'NT', 'John 19', 'He was crucified at Golgotha, near Jerusalem.'),
  ('Methuselah lived longer than anyone else recorded in the Bible.', true, 'medium', 'OT', 'Genesis 5:27', 'He lived 969 years.'),
  ('Saul was the first king of Israel.', true, 'medium', 'OT', '1 Samuel 10', 'David was the second.'),
  ('The walls of Jericho fell after the Israelites marched and shouted.', true, 'medium', 'OT', 'Joshua 6', 'No battering ram was used.'),
  ('Esther became a queen of Persia.', true, 'medium', 'OT', 'Esther 2', 'She later saved her people.'),
  ('Ruth was the great-grandmother of King David.', true, 'medium', 'OT', 'Ruth 4', 'Through her son Obed.'),
  ('Gideon''s army was reduced to just 300 men.', true, 'medium', 'OT', 'Judges 7', 'So the victory would clearly be God''s.'),
  ('Job lost his wealth, his children, and his health.', true, 'medium', 'OT', 'Job 1-2', 'Yet he did not curse God.'),
  ('Zacchaeus climbed a sycamore tree to see Jesus.', true, 'medium', 'NT', 'Luke 19', 'He was short and the crowd was large.'),
  ('Lazarus was raised from the dead by Jesus.', true, 'medium', 'NT', 'John 11', 'After four days in the tomb.'),
  ('Elijah was taken up to heaven in a whirlwind with a chariot of fire.', true, 'medium', 'OT', '2 Kings 2', 'Elisha watched him go.'),
  ('Shadrach, Meshach, and Abednego survived the fiery furnace.', true, 'medium', 'OT', 'Daniel 3', 'A fourth figure appeared with them.'),
  ('The Israelites ate manna in the wilderness.', true, 'medium', 'OT', 'Exodus 16', 'Bread from heaven each morning.'),
  ('Aaron was the brother of Moses.', true, 'medium', 'OT', 'Exodus 4', 'His older brother and spokesman.'),
  ('Jacob had twelve sons.', true, 'medium', 'OT', 'Genesis 35', 'They became the twelve tribes of Israel.'),
  ('Rahab helped hide the Israelite spies in Jericho.', true, 'medium', 'OT', 'Joshua 2', 'She was spared when the city fell.'),
  ('Joshua succeeded Moses as leader of Israel.', true, 'medium', 'OT', 'Joshua 1', 'He led them into the Promised Land.'),
  ('Deborah was a prophetess and a judge of Israel.', true, 'medium', 'OT', 'Judges 4', 'She led alongside Barak.'),
  ('Jesus taught his followers the Lord''s Prayer.', true, 'medium', 'NT', 'Matthew 6', '''Our Father in heaven...'''),
  ('The parable of the Good Samaritan answers the question ''Who is my neighbor?''', true, 'medium', 'NT', 'Luke 10', 'A Samaritan helped a wounded stranger.'),
  ('Thomas doubted that Jesus had risen from the dead.', true, 'medium', 'NT', 'John 20', 'He wanted to see the nail marks.'),
  ('Matthew was a tax collector before following Jesus.', true, 'medium', 'NT', 'Matthew 9', 'Jesus called him from the tax booth.'),
  ('Jesus washed his disciples'' feet at the Last Supper.', true, 'medium', 'NT', 'John 13', 'An example of humble service.'),
  ('Jesus fasted forty days in the wilderness.', true, 'medium', 'NT', 'Matthew 4', 'Before he was tempted.'),
  ('Nebuchadnezzar was the king of Babylon.', true, 'medium', 'OT', 'Daniel 2', 'He had dreams Daniel interpreted.'),
  ('Belshazzar saw a mysterious hand writing on the wall during a feast.', true, 'medium', 'OT', 'Daniel 5', 'Daniel interpreted the writing.'),
  ('Sarah gave birth to Isaac in her old age.', true, 'medium', 'OT', 'Genesis 21', 'She was about ninety.'),
  ('Esau sold his birthright for a bowl of stew.', true, 'medium', 'OT', 'Genesis 25', 'He despised his birthright.'),
  ('Jacob''s name was changed to Israel.', true, 'medium', 'OT', 'Genesis 32', 'After he wrestled with God.'),
  ('Joseph interpreted Pharaoh''s dreams about years of plenty and famine.', true, 'medium', 'OT', 'Genesis 41', 'He became second in command of Egypt.'),
  ('Moses saw a bush that burned but was not consumed.', true, 'medium', 'OT', 'Exodus 3', 'God spoke to him from it.'),
  ('The golden calf was made while Moses was on Mount Sinai.', true, 'medium', 'OT', 'Exodus 32', 'Aaron made it for the impatient people.'),
  ('King David wrote many of the Psalms.', true, 'medium', 'OT', 'Psalms', 'Many are attributed to him.'),
  ('Solomon built the first temple in Jerusalem.', true, 'medium', 'OT', '1 Kings 6', 'A house for the Lord.'),
  ('Jeremiah is often called the ''weeping prophet.''', true, 'medium', 'OT', 'Jeremiah 9', 'He mourned over Judah''s sin.'),
  ('Ezekiel saw a vision of a valley of dry bones.', true, 'medium', 'OT', 'Ezekiel 37', 'The bones came to life.'),
  ('Isaiah prophesied about a coming Messiah.', true, 'medium', 'OT', 'Isaiah 53', 'Centuries before Jesus.'),
  ('Daniel chose vegetables and water over the king''s rich food.', true, 'medium', 'OT', 'Daniel 1', 'He and his friends stayed healthy.'),
  ('The Queen of Sheba visited King Solomon.', true, 'medium', 'OT', '1 Kings 10', 'To test his wisdom.'),
  ('Naaman was healed of leprosy by washing in the Jordan River.', true, 'medium', 'OT', '2 Kings 5', 'Seven times, as the prophet said.'),
  ('The Holy Spirit came upon the believers at Pentecost.', true, 'medium', 'NT', 'Acts 2', 'With wind and tongues of fire.'),
  ('Stephen was the first Christian martyr.', true, 'medium', 'NT', 'Acts 7', 'He was stoned to death.'),
  ('Paul was blinded by a bright light on the road to Damascus.', true, 'medium', 'NT', 'Acts 9', 'He met the risen Jesus.'),
  ('Jesus raised Jairus'' daughter from the dead.', true, 'medium', 'NT', 'Mark 5', '''Little girl, get up.'''),
  ('The parable of the sower describes seed falling on different soils.', true, 'medium', 'NT', 'Matthew 13', 'The seed is the word of God.'),
  ('The woman Jesus spoke with at the well was a Samaritan.', true, 'medium', 'NT', 'John 4', 'He offered her living water.'),
  ('Simeon held the baby Jesus in the temple and praised God.', true, 'medium', 'NT', 'Luke 2', 'He had waited to see the Messiah.'),
  ('At the Transfiguration, Moses and Elijah appeared with Jesus.', true, 'medium', 'NT', 'Matthew 17', 'His face shone like the sun.'),
  ('Judas identified Jesus to the soldiers with a kiss.', true, 'medium', 'NT', 'Matthew 26', 'In the Garden of Gethsemane.'),
  ('Pontius Pilate sentenced Jesus to be crucified.', true, 'medium', 'NT', 'John 19', 'Though he found no fault in him.'),
  ('Jesus ascended to heaven from the Mount of Olives.', true, 'medium', 'NT', 'Acts 1', 'A cloud took him from their sight.'),
  ('Andrew was the brother of Peter.', true, 'medium', 'NT', 'John 1', 'Both were fishermen Jesus called.'),
  ('Cornelius was a Roman centurion who came to faith.', true, 'medium', 'NT', 'Acts 10', 'Peter was sent to him.'),
  ('Paul and Silas sang hymns while in prison.', true, 'medium', 'NT', 'Acts 16', 'An earthquake then opened the doors.'),
  ('Balaam''s donkey spoke to him with a human voice.', true, 'medium', 'OT', 'Numbers 22', 'An angel had blocked the path.'),
  ('Hannah prayed for a son and God gave her Samuel.', true, 'medium', 'OT', '1 Samuel 1', 'She dedicated him to the Lord.'),
  ('Bathsheba became a wife of King David.', true, 'medium', 'OT', '2 Samuel 11-12', 'She was the mother of Solomon.'),
  ('The kingdom of Israel split into two after Solomon died.', true, 'medium', 'OT', '1 Kings 12', 'Into Israel and Judah.'),
  ('Nehemiah led the effort to rebuild the walls of Jerusalem.', true, 'medium', 'OT', 'Nehemiah 2', 'Despite fierce opposition.'),
  ('John the Baptist ate locusts and wild honey.', true, 'medium', 'NT', 'Matthew 3', 'He lived in the wilderness.'),
  ('John the Baptist was beheaded by order of Herod.', true, 'medium', 'NT', 'Mark 6', 'At the request of Herodias'' daughter.'),
  ('Paul was one of Jesus'' original twelve disciples.', false, 'medium', 'NT', 'Acts 9', 'He came later; he was not one of the Twelve.'),
  ('Nicodemus came to Jesus in the middle of the day.', false, 'medium', 'NT', 'John 3', 'He came to Jesus at night.'),
  ('When the prodigal son returned home, his father turned him away.', false, 'medium', 'NT', 'Luke 15', 'His father ran to him and threw a feast.'),
  ('God destroyed the Tower of Babel with fire from heaven.', false, 'medium', 'OT', 'Genesis 11', 'He confused their language and scattered them.'),
  ('Jesus preached the Sermon on the Mount from inside the temple.', false, 'medium', 'NT', 'Matthew 5', 'He taught it on a mountainside.'),
  ('After his conversion, Saul''s name was changed to Peter.', false, 'medium', 'NT', 'Acts 13', 'His name became Paul.'),
  ('Mary Magdalene was the mother of Jesus.', false, 'medium', 'NT', 'John 20', 'Jesus'' mother was Mary of Nazareth, a different Mary.'),
  ('All ten lepers returned to thank Jesus for healing them.', false, 'medium', 'NT', 'Luke 17', 'Only one returned, and he was a Samaritan.'),
  ('Rebekah was the wife of Jacob.', false, 'medium', 'OT', 'Genesis 24', 'She was the wife of Isaac.'),
  ('There were seven plagues on Egypt.', false, 'medium', 'OT', 'Exodus 7-12', 'There were ten plagues.'),
  ('Jonah obeyed God right away and sailed straight to Nineveh.', false, 'medium', 'OT', 'Jonah 1', 'He first fled toward Tarshish.'),
  ('The book of Revelation was written by the apostle Matthew.', false, 'medium', 'NT', 'Revelation 1', 'It is traditionally attributed to John.'),
  ('The rich young ruler gladly gave up his wealth to follow Jesus.', false, 'medium', 'NT', 'Mark 10', 'He went away sad because he was very rich.'),
  ('Martha sat at Jesus'' feet while Mary was busy serving.', false, 'medium', 'NT', 'Luke 10', 'It was reversed: Mary sat, Martha served.'),
  ('The book of Psalms is found in the New Testament.', false, 'medium', 'OT', 'Psalms', 'Psalms is in the Old Testament.'),
  ('The wise men visited Jesus in the stable on the night he was born.', false, 'medium', 'NT', 'Matthew 2', 'They came later and found him in a house.'),
  ('The disciple who walked on the water toward Jesus was John.', false, 'medium', 'NT', 'Matthew 14', 'It was Peter who stepped out of the boat.'),
  ('Isaac''s son was named Ishmael.', false, 'medium', 'OT', 'Genesis 25', 'Isaac''s sons were Jacob and Esau; Ishmael was Abraham''s son.'),
  ('Elijah was the successor of Elisha.', false, 'medium', 'OT', '2 Kings 2', 'Elisha succeeded Elijah, not the other way around.'),
  ('Goliath was an Israelite soldier.', false, 'medium', 'OT', '1 Samuel 17', 'He was a Philistine champion.'),
  ('Samuel was the first king of Israel.', false, 'medium', 'OT', '1 Samuel 10', 'Samuel was a prophet; he anointed Saul as first king.'),
  ('The Ark of the Covenant was carried on the backs of horses.', false, 'medium', 'OT', 'Numbers 4', 'Levites carried it with poles on their shoulders.'),
  ('Moses led Israel across the Jordan into the Promised Land.', false, 'medium', 'OT', 'Joshua 3', 'Moses died first; Joshua led them across.'),
  ('Jesus was born in the town of Nazareth.', false, 'medium', 'NT', 'Luke 2', 'He was born in Bethlehem; he grew up in Nazareth.'),
  ('Peter wrote most of the letters in the New Testament.', false, 'medium', 'NT', 'New Testament', 'Paul wrote the most letters.'),
  ('The prophet Daniel was thrown into a fiery furnace.', false, 'medium', 'OT', 'Daniel 3; 6', 'Daniel was in the lions'' den; his three friends were in the furnace.'),
  ('Cain and Abel were the sons of Noah.', false, 'medium', 'OT', 'Genesis 4', 'They were sons of Adam and Eve.'),
  ('The Israelites wandered in the wilderness for twelve years.', false, 'medium', 'OT', 'Numbers 14', 'They wandered forty years.'),
  ('Solomon was the father of King David.', false, 'medium', 'OT', '2 Samuel 12', 'David was Solomon''s father, not the reverse.'),
  ('The parable of the prodigal son is really about a lost coin.', false, 'medium', 'NT', 'Luke 15', 'It is about a lost son who returns home.'),
  ('Joseph''s brothers welcomed him warmly and never harmed him.', false, 'medium', 'OT', 'Genesis 37', 'They sold him into slavery.'),
  ('Abraham''s wife was named Rachel.', false, 'medium', 'OT', 'Genesis 17', 'Abraham''s wife was Sarah; Rachel was Jacob''s wife.'),
  ('The first Passover took place in the Promised Land.', false, 'medium', 'OT', 'Exodus 12', 'It happened in Egypt, the night before the Exodus.'),
  ('King Herod helped protect the baby Jesus.', false, 'medium', 'NT', 'Matthew 2', 'He tried to have Jesus killed.'),
  ('Jesus personally wrote several books of the New Testament.', false, 'medium', 'NT', 'New Testament', 'Jesus wrote none of them himself.'),
  ('Lot''s wife turned into a pillar of gold.', false, 'medium', 'OT', 'Genesis 19', 'She turned into a pillar of salt.'),
  ('The Ten Commandments were given at the Sea of Galilee.', false, 'medium', 'OT', 'Exodus 20', 'They were given at Mount Sinai.'),
  ('Delilah gave Samson his great strength.', false, 'medium', 'OT', 'Judges 16', 'She betrayed the secret of his strength; his strength was from God.'),
  ('The Holy Spirit came upon the believers at Passover.', false, 'medium', 'NT', 'Acts 2', 'It came at Pentecost.'),
  ('Stephen was beheaded for his faith.', false, 'medium', 'NT', 'Acts 7', 'He was stoned to death.'),
  ('Zacchaeus refused to give back any of the money he had taken.', false, 'medium', 'NT', 'Luke 19', 'He gave half to the poor and repaid those he cheated fourfold.'),
  ('Jesus rode into Jerusalem on a white horse.', false, 'medium', 'NT', 'Matthew 21', 'He rode in humbly on a donkey.'),
  ('Judas betrayed Jesus for forty pieces of gold.', false, 'medium', 'NT', 'Matthew 26', 'It was thirty pieces of silver.'),
  ('When God offered Solomon anything, he asked first for great riches.', false, 'medium', 'OT', '1 Kings 3', 'He asked for wisdom.'),
  ('Ruth was from the land of Egypt.', false, 'medium', 'OT', 'Ruth 1', 'Ruth was a Moabite.'),
  ('Peter walked on the water and never began to sink.', false, 'medium', 'NT', 'Matthew 14', 'He began to sink and cried out to Jesus.'),
  ('The apostle Paul wrote a letter to the Romans.', true, 'medium', 'NT', 'Romans 1', 'The book of Romans is one of his letters.'),
  ('Peter was a fisherman before he followed Jesus.', true, 'medium', 'NT', 'Matthew 4', 'Jesus called him to fish for people.'),
  ('Joseph rose to become a powerful ruler in Egypt.', true, 'medium', 'OT', 'Genesis 41', 'Second in command under Pharaoh.'),
  ('Jesus told the parable of the lost sheep.', true, 'medium', 'NT', 'Luke 15', 'A shepherd leaves ninety-nine to find one.'),
  ('Aaron became the first high priest of Israel.', true, 'medium', 'OT', 'Exodus 28', 'Moses'' brother.'),
  ('David played the harp to soothe King Saul.', true, 'medium', 'OT', '1 Samuel 16', 'His music calmed the troubled king.'),
  ('The angel Gabriel told Mary she would give birth to Jesus.', true, 'medium', 'NT', 'Luke 1', 'The announcement of Jesus'' birth.'),
  ('The book of Exodus is the very first book of the Bible.', false, 'medium', 'OT', 'Genesis 1', 'Genesis is first; Exodus is second.'),
  ('Martha was one of Jesus'' twelve disciples.', false, 'medium', 'NT', 'Luke 10', 'She was a friend and host of Jesus, not one of the Twelve.'),
  ('Noah''s three sons were named Shem, Ham, and Peter.', false, 'medium', 'OT', 'Genesis 6', 'They were Shem, Ham, and Japheth.'),
  ('The Israelites crossed the Jordan River to escape from Egypt.', false, 'medium', 'OT', 'Exodus 14', 'They crossed the Red Sea to escape Egypt.'),
  ('Elijah was fed by ravens sent by King Ahab.', false, 'medium', 'OT', '1 Kings 17', 'God sent the ravens to feed him.'),
  ('The prophet Jonah was sent to preach in the city of Babylon.', false, 'medium', 'OT', 'Jonah 3', 'He was sent to Nineveh.'),
  ('Jesus was crucified alone, with no one beside him.', false, 'medium', 'NT', 'Luke 23', 'He was crucified between two criminals.'),
  ('Methuselah lived 969 years.', true, 'hard', 'OT', 'Genesis 5:27', 'The longest lifespan recorded in Scripture.'),
  ('Enoch did not die but was taken away by God.', true, 'hard', 'OT', 'Genesis 5:24', '''God took him.'''),
  ('Nehemiah''s crew rebuilt the walls of Jerusalem in 52 days.', true, 'hard', 'OT', 'Nehemiah 6:15', 'A remarkably fast rebuild.'),
  ('Ehud was a left-handed judge of Israel.', true, 'hard', 'OT', 'Judges 3', 'He delivered Israel from Moab.'),
  ('Melchizedek was both a king of Salem and a priest of God.', true, 'hard', 'OT', 'Genesis 14', 'He blessed Abraham.'),
  ('Aaron''s staff budded and produced almonds.', true, 'hard', 'OT', 'Numbers 17', 'A sign confirming his priesthood.'),
  ('Moses lifted up a bronze serpent so the snake-bitten could look and live.', true, 'hard', 'OT', 'Numbers 21', 'Jesus later compared himself to it.'),
  ('Caleb and Joshua were the only two spies who gave a faithful report.', true, 'hard', 'OT', 'Numbers 14', 'The other ten spread fear.'),
  ('Absalom was caught by his hair in an oak tree.', true, 'hard', 'OT', '2 Samuel 18', 'It led to his death.'),
  ('Elisha''s servant Gehazi was struck with leprosy for his greed.', true, 'hard', 'OT', '2 Kings 5', 'He secretly took Naaman''s gifts.'),
  ('King Hezekiah was given fifteen more years of life.', true, 'hard', 'OT', '2 Kings 20', 'After he prayed in his illness.'),
  ('Philemon is a short letter about a runaway slave named Onesimus.', true, 'hard', 'NT', 'Philemon', 'Paul appealed for his welcome back.'),
  ('Eutychus fell from a window during Paul''s long sermon and was raised to life.', true, 'hard', 'NT', 'Acts 20', 'He had drifted to sleep.'),
  ('Gamaliel was the respected teacher who trained Paul.', true, 'hard', 'NT', 'Acts 22', 'A leading Pharisee.'),
  ('The prophet Nathan confronted David over Bathsheba.', true, 'hard', 'OT', '2 Samuel 12', '''You are the man!'''),
  ('Rahab is listed in the genealogy of Jesus.', true, 'hard', 'NT', 'Matthew 1:5', 'Among Jesus'' ancestors.'),
  ('King Saul consulted the witch of Endor.', true, 'hard', 'OT', '1 Samuel 28', 'The night before he died in battle.'),
  ('King Uzziah was struck with leprosy for burning incense in the temple.', true, 'hard', 'OT', '2 Chronicles 26', 'He overstepped the priests'' role.'),
  ('Amos was a shepherd before God called him to prophesy.', true, 'hard', 'OT', 'Amos 7:14', 'Also a tender of sycamore figs.'),
  ('Goliath stood over nine feet tall according to many translations.', true, 'hard', 'OT', '1 Samuel 17:4', '''Six cubits and a span.'''),
  ('About 5,000 people were added to the church on the day of Pentecost.', false, 'hard', 'NT', 'Acts 2:41', 'About 3,000 were added that day.'),
  ('Jael killed the enemy commander Sisera with a sword.', false, 'hard', 'OT', 'Judges 4', 'She used a tent peg and a hammer.'),
  ('Samson killed a thousand men with the jawbone of a lion.', false, 'hard', 'OT', 'Judges 15', 'He used the jawbone of a donkey.'),
  ('Elijah defeated the prophets of Baal on Mount Sinai.', false, 'hard', 'OT', '1 Kings 18', 'The contest was on Mount Carmel.'),
  ('Paul was shipwrecked on the island of Cyprus.', false, 'hard', 'NT', 'Acts 28', 'He was shipwrecked on Malta.'),
  ('King Solomon wrote the book of Lamentations.', false, 'hard', 'OT', 'Lamentations', 'It is traditionally attributed to Jeremiah.'),
  ('In the letter to Philemon, Onesimus was the master and Philemon the slave.', false, 'hard', 'NT', 'Philemon', 'Onesimus was the slave; Philemon was the master.'),
  ('Obadiah is the longest book in the Old Testament.', false, 'hard', 'OT', 'Obadiah', 'It is the shortest, at one chapter.'),
  ('The Jordan River caught fire when the priests carrying the ark stepped in.', false, 'hard', 'OT', 'Joshua 3', 'The river stopped flowing so Israel could cross.'),
  ('Korah led a rebellion against Moses and was rewarded by God.', false, 'hard', 'OT', 'Numbers 16', 'The ground opened and swallowed the rebels.'),
  ('Og was the giant king of Egypt.', false, 'hard', 'OT', 'Deuteronomy 3', 'He was king of Bashan.'),
  ('Zerubbabel led the building of the very first temple in Jerusalem.', false, 'hard', 'OT', 'Ezra 3', 'He led the second temple, after the exile; Solomon built the first.'),
  ('The book of Revelation addresses twelve churches in Asia.', false, 'hard', 'NT', 'Revelation 1', 'It addresses seven churches.'),
  ('The prophet Habakkuk was swallowed by a great fish.', false, 'hard', 'OT', 'Jonah 1', 'That was Jonah, not Habakkuk.'),
  ('Priscilla and Aquila were fishermen by trade.', false, 'hard', 'NT', 'Acts 18', 'They were tentmakers, like Paul.'),
  ('Melchizedek is discussed at length in the book of James.', false, 'hard', 'NT', 'Hebrews 7', 'He is discussed in Hebrews.'),
  ('Nehemiah''s main task was to rebuild the temple in Jerusalem.', false, 'hard', 'OT', 'Nehemiah 2', 'He rebuilt the walls; the temple was rebuilt earlier under Zerubbabel.'),
  ('Gideon tested God by laying out a golden fleece.', false, 'hard', 'OT', 'Judges 6', 'It was a wool fleece.'),
  ('The witch of Endor was consulted by King David.', false, 'hard', 'OT', '1 Samuel 28', 'It was King Saul.'),
  ('Elisha received a single portion of Elijah''s spirit.', false, 'hard', 'OT', '2 Kings 2', 'He asked for and received a double portion.')
on conflict (statement) do nothing;
