/* v12_1_prompts.sql
   Hangman / Pictionary / Taboo prompts: fills banned words on the 20 existing prompts, then adds 193 new ones.
   Adds only, nothing deleted. Safe to re-run. Paste the whole file and Run. */

update game_prompts g set banned_words = v.bw::jsonb
from (values
  ('Noah''s Ark',                '["Boat","Flood","Animals","Two","Rain"]'),
  ('Moses',                      '["Egypt","Pharaoh","Red Sea","Commandments","Basket"]'),
  ('David and Goliath',          '["Giant","Sling","Stone","Shepherd","Philistine"]'),
  ('Jonah and the Whale',        '["Fish","Swallowed","Nineveh","Boat","Three days"]'),
  ('The Last Supper',            '["Bread","Wine","Disciples","Passover","Meal"]'),
  ('Jericho',                    '["Walls","March","Trumpets","Joshua","Fall"]'),
  ('Bethlehem',                  '["Jesus","Born","Manger","Star","Town"]'),
  ('Burning Bush',               '["Fire","Moses","Flames","Sandals","Holy ground"]'),
  ('Ten Commandments',           '["Moses","Stone","Tablets","Rules","Sinai"]'),
  ('Good Samaritan',             '["Robbers","Road","Help","Neighbor","Parable"]'),
  ('Fishers of Men',             '["Disciples","Net","Boat","Follow","Peter"]'),
  ('Garden of Eden',             '["Adam","Eve","Fruit","Snake","Tree"]'),
  ('Daniel in the Lions'' Den',  '["Pray","King","Angel","Mouths","Cats"]'),
  ('Prodigal Son',               '["Father","Pigs","Inheritance","Brother","Home"]'),
  ('Manna from Heaven',          '["Bread","Wilderness","Food","Israelites","Sky"]'),
  ('Peter Walks on Water',       '["Boat","Sink","Faith","Storm","Jesus"]'),
  ('The Empty Tomb',             '["Stone","Risen","Easter","Angel","Grave"]'),
  ('Solomon',                    '["Wise","King","Temple","David","Wisdom"]'),
  ('Ruth and Naomi',             '["Boaz","Mother-in-law","Loyal","Grain","Moab"]'),
  ('Nazareth',                   '["Jesus","Grew up","Town","Galilee","Hometown"]')
) as v(t, bw)
where g.text = v.t and g.banned_words is null;

insert into game_prompts (text, category, difficulty, testament, hint, banned_words)
select v.text, v.category, v.difficulty, v.testament, v.hint, v.banned_words::jsonb
from (values
  ('Adam',               'person', 'easy',   'OT', 'First man',                          '["Eve","First","Garden","Man","Rib"]'),
  ('Eve',                'person', 'easy',   'OT', 'First woman',                        '["Adam","First","Woman","Apple","Snake"]'),
  ('Noah',               'person', 'easy',   'OT', 'Built a very big boat',              '["Ark","Flood","Boat","Animals","Rainbow"]'),
  ('Abraham',            'person', 'easy',   'OT', 'Father of many nations',             '["Isaac","Sarah","Father","Nations","Stars"]'),
  ('Jacob',              'person', 'easy',   'OT', 'Wrestled with God; twelve sons',     '["Esau","Ladder","Twelve","Israel","Twin"]'),
  ('Joseph',             'person', 'easy',   'OT', 'Colorful coat, dreams, Egypt',       '["Coat","Dreams","Brothers","Egypt","Pharaoh"]'),
  ('David',              'person', 'easy',   'OT', 'Shepherd boy who became king',       '["Goliath","King","Shepherd","Sling","Psalms"]'),
  ('Goliath',            'person', 'easy',   'OT', 'Nine-foot Philistine',               '["Giant","David","Tall","Sling","Stone"]'),
  ('Jonah',              'person', 'easy',   'OT', 'Ran from God, met a big fish',       '["Fish","Whale","Nineveh","Swallowed","Boat"]'),
  ('Daniel',             'person', 'easy',   'OT', 'Lions couldn''t touch him',          '["Lions","Den","Pray","Babylon","King"]'),
  ('Samson',             'person', 'easy',   'OT', 'Strongest man, long hair',           '["Strong","Hair","Delilah","Philistines","Pillars"]'),
  ('Esther',             'person', 'easy',   'OT', 'Queen who saved her people',         '["Queen","King","Jews","Haman","Mordecai"]'),
  ('Elijah',             'person', 'easy',   'OT', 'Fire from heaven, chariot ride',     '["Prophet","Fire","Chariot","Baal","Ravens"]'),
  ('Jesus',              'person', 'easy',   'NT', 'Son of God',                         '["God","Son","Christ","Savior","Cross"]'),
  ('Mary',               'person', 'easy',   'NT', 'Mother of Jesus',                    '["Jesus","Mother","Joseph","Angel","Baby"]'),
  ('Peter',              'person', 'easy',   'NT', 'Fisherman, denied Jesus 3 times',    '["Disciple","Rock","Denied","Rooster","Fisherman"]'),
  ('Paul',               'person', 'easy',   'NT', 'Wrote a lot of the New Testament',   '["Saul","Letters","Damascus","Missionary","Apostle"]'),
  ('Zacchaeus',          'person', 'easy',   'NT', 'Short man in a tree',                '["Short","Tree","Tax collector","Climb","Sycamore"]'),
  ('Lazarus',            'person', 'easy',   'NT', 'Four days dead, then not',           '["Dead","Tomb","Raised","Mary","Martha"]'),
  ('John the Baptist',   'person', 'easy',   'NT', 'Locusts, honey, river',              '["Baptize","Jordan","Locusts","Honey","Cousin"]'),
  ('Judas',              'person', 'easy',   'NT', 'Thirty pieces of silver',            '["Betray","Silver","Kiss","Disciple","Thirty"]'),
  ('Pharaoh',            'person', 'easy',   'OT', 'King of Egypt',                      '["Egypt","King","Moses","Plagues","Let my people go"]'),
  ('Isaac',              'person', 'easy',   'OT', 'Abraham''s promised son',            '["Abraham","Sarah","Son","Sacrifice","Ram"]'),
  ('Joshua',             'person', 'medium', 'OT', 'Led Israel into the Promised Land',  '["Jericho","Moses","Walls","Promised Land","Leader"]'),
  ('Gideon',             'person', 'medium', 'OT', '300 men, torches and trumpets',      '["300","Fleece","Midianites","Trumpets","Judge"]'),
  ('Deborah',            'person', 'medium', 'OT', 'A woman who judged Israel',          '["Judge","Woman","Barak","Palm tree","Prophetess"]'),
  ('Samuel',             'person', 'medium', 'OT', 'Heard God call his name at night',   '["Hannah","Eli","Prophet","Anoint","Speak Lord"]'),
  ('King Saul',          'person', 'medium', 'OT', 'First king of Israel',               '["First","King","David","Jonathan","Tall"]'),
  ('Nehemiah',           'person', 'medium', 'OT', 'Rebuilt Jerusalem''s wall',          '["Wall","Jerusalem","Cupbearer","Rebuild","52 days"]'),
  ('Elisha',             'person', 'medium', 'OT', 'Elijah''s successor, double portion','["Elijah","Prophet","Naaman","Double","Axe head"]'),
  ('Rahab',              'person', 'medium', 'OT', 'Hid the spies, red rope',            '["Spies","Jericho","Scarlet","Rope","Window"]'),
  ('Hannah',             'person', 'medium', 'OT', 'Prayed for a son',                   '["Samuel","Prayed","Son","Temple","Eli"]'),
  ('Thomas',             'person', 'medium', 'NT', 'Doubting disciple',                  '["Doubt","Disciple","Wounds","Believe","Twin"]'),
  ('Matthew',            'person', 'medium', 'NT', 'Tax collector turned disciple',      '["Tax collector","Gospel","Disciple","Levi","Book"]'),
  ('Martha',             'person', 'medium', 'NT', 'Busy in the kitchen',                '["Mary","Lazarus","Busy","Serving","Sister"]'),
  ('Nicodemus',          'person', 'medium', 'NT', 'Came to Jesus at night',             '["Night","Pharisee","Born again","Teacher","John 3"]'),
  ('Barnabas',           'person', 'medium', 'NT', 'Son of encouragement',               '["Paul","Encouragement","Missionary","Mark","Antioch"]'),
  ('Timothy',            'person', 'medium', 'NT', 'Paul''s young helper',               '["Paul","Young","Letters","Pastor","Helper"]'),
  ('Stephen',            'person', 'medium', 'NT', 'First martyr',                       '["Stoned","Martyr","First","Deacon","Acts"]'),
  ('Pontius Pilate',     'person', 'medium', 'NT', 'Washed his hands',                   '["Governor","Roman","Crucify","Hands","Trial"]'),
  ('King Herod',         'person', 'medium', 'NT', 'Wanted baby Jesus dead',             '["King","Wise men","Baby","Kill","Bethlehem"]'),
  ('Cain',               'person', 'medium', 'OT', 'Killed his brother',                 '["Abel","Brother","Killed","Farmer","Mark"]'),
  ('Abel',               'person', 'medium', 'OT', 'First person to die',                '["Cain","Brother","Sheep","Offering","Killed"]'),
  ('Delilah',            'person', 'medium', 'OT', 'Cut Samson''s hair',                 '["Samson","Hair","Cut","Secret","Philistines"]'),
  ('Boaz',               'person', 'medium', 'OT', 'Married Ruth',                       '["Ruth","Field","Grain","Redeemer","Naomi"]'),
  ('Miriam',             'person', 'medium', 'OT', 'Moses'' sister, sang at the sea',    '["Moses","Sister","Basket","Tambourine","Aaron"]'),
  ('Aaron',              'person', 'medium', 'OT', 'Moses'' brother, first high priest', '["Moses","Brother","Priest","Staff","Golden calf"]'),
  ('Mary Magdalene',     'person', 'medium', 'NT', 'First to see the risen Jesus',       '["Tomb","Easter","Risen","Woman","Garden"]'),
  ('Simon of Cyrene',    'person', 'medium', 'NT', 'Carried the cross',                  '["Cross","Carry","Jesus","Road","Forced"]'),
  ('Andrew',             'person', 'medium', 'NT', 'Brought Peter to Jesus',             '["Peter","Brother","Fisherman","Disciple","Loaves"]'),
  ('Melchizedek',        'person', 'hard',   'OT', 'King and priest who met Abraham',    '["Priest","King","Abraham","Salem","Bread"]'),
  ('Bartimaeus',         'person', 'hard',   'NT', 'Blind beggar near Jericho',          '["Blind","Beggar","Jericho","Son of David","Mercy"]'),
  ('Jairus',             'person', 'hard',   'NT', 'His daughter was raised',            '["Daughter","Raised","Synagogue","Sleeping","Twelve"]'),
  ('Onesimus',           'person', 'hard',   'NT', 'Runaway slave in Philemon',          '["Slave","Philemon","Runaway","Paul","Letter"]'),
  ('Methuselah',         'person', 'hard',   'OT', 'Lived 969 years',                    '["Oldest","969","Years","Old","Noah"]'),
  ('Nebuchadnezzar',     'person', 'hard',   'OT', 'King of Babylon, ate grass',         '["Babylon","King","Statue","Furnace","Grass"]'),
  ('Ezekiel',            'person', 'hard',   'OT', 'Valley of dry bones',                '["Bones","Prophet","Vision","Wheel","Valley"]'),
  ('Balaam',             'person', 'hard',   'OT', 'His donkey talked',                  '["Donkey","Talk","Angel","Curse","Prophet"]'),
  ('Jael',               'person', 'hard',   'OT', 'Tent peg',                           '["Tent","Peg","Sisera","Deborah","Hammer"]'),
  ('Lydia',              'person', 'hard',   'NT', 'Sold purple cloth',                  '["Purple","Cloth","Philippi","Paul","Seller"]'),
  ('Cornelius',          'person', 'hard',   'NT', 'Roman centurion Peter visited',      '["Centurion","Roman","Peter","Vision","Gentile"]'),
  ('Eutychus',           'person', 'hard',   'NT', 'Fell asleep, fell out a window',     '["Window","Fell","Asleep","Paul","Sermon"]'),
  ('Absalom',            'person', 'hard',   'OT', 'Caught by his hair in a tree',       '["Hair","Tree","David","Son","Rebel"]'),
  ('Josiah',             'person', 'hard',   'OT', 'King at age eight',                  '["King","Eight","Boy","Book of the Law","Judah"]'),
  ('Hezekiah',           'person', 'hard',   'OT', 'Got 15 extra years',                 '["King","Fifteen","Years","Sick","Sundial"]'),
  ('Egypt',              'place',  'easy',   'OT', 'Pyramids, Pharaoh, plagues',         '["Pharaoh","Pyramids","Moses","Slaves","Nile"]'),
  ('Jerusalem',          'place',  'easy',   null, 'City of David, the temple',          '["City","Temple","David","Holy","Israel"]'),
  ('Red Sea',            'place',  'easy',   'OT', 'Parted for Israel',                  '["Parted","Moses","Water","Egypt","Walls"]'),
  ('Jordan River',       'place',  'easy',   null, 'Where Jesus was baptized',           '["Baptized","River","Water","John","Cross"]'),
  ('Mount Sinai',        'place',  'easy',   'OT', 'Ten Commandments given here',        '["Mountain","Commandments","Moses","Tablets","Smoke"]'),
  ('Galilee',            'place',  'easy',   'NT', 'Lake where Jesus calmed the storm',  '["Sea","Lake","Boat","Storm","Fishing"]'),
  ('Babylon',            'place',  'medium', 'OT', 'Where Daniel was taken',             '["Daniel","Exile","Nebuchadnezzar","Captive","Tower"]'),
  ('Nineveh',            'place',  'medium', 'OT', 'Jonah''s assignment',                '["Jonah","City","Repent","Preach","Assyria"]'),
  ('Mount of Olives',    'place',  'medium', 'NT', 'Jesus ascended from here',           '["Ascension","Mountain","Trees","Jerusalem","Garden"]'),
  ('Damascus',           'place',  'medium', 'NT', 'Saul saw the light on the way here', '["Saul","Road","Light","Blind","Paul"]'),
  ('Rome',               'place',  'medium', 'NT', 'Paul''s final stop',                 '["Empire","Caesar","Paul","Italy","Letter"]'),
  ('Canaan',             'place',  'medium', 'OT', 'The Promised Land',                  '["Promised","Land","Milk","Honey","Israel"]'),
  ('Sodom',              'place',  'medium', 'OT', 'Lot''s city, destroyed by fire',     '["Lot","Fire","Destroyed","Gomorrah","Salt"]'),
  ('Golgotha',           'place',  'medium', 'NT', 'Place of the skull',                 '["Cross","Skull","Crucified","Hill","Calvary"]'),
  ('Capernaum',          'place',  'medium', 'NT', 'Jesus'' home base by the lake',      '["Jesus","Town","Galilee","Peter","Roof"]'),
  ('Gethsemane',         'place',  'medium', 'NT', 'Garden where Jesus prayed',          '["Garden","Prayed","Arrested","Sweat","Olive"]'),
  ('Patmos',             'place',  'hard',   'NT', 'John''s island',                     '["Island","John","Revelation","Exile","Vision"]'),
  ('Emmaus',             'place',  'hard',   'NT', 'Road where Jesus walked unnoticed',  '["Road","Walk","Bread","Risen","Two"]'),
  ('Antioch',            'place',  'hard',   'NT', 'First called Christians here',       '["Christians","First","Paul","Barnabas","Church"]'),
  ('Ephesus',            'place',  'hard',   'NT', 'Armor of God letter went here',      '["Paul","Letter","Armor","Church","Riot"]'),
  ('Corinth',            'place',  'hard',   'NT', 'Love chapter went here',             '["Paul","Letter","Love","Church","Greece"]'),
  ('Mount Carmel',       'place',  'hard',   'OT', 'Elijah vs. the prophets of Baal',    '["Elijah","Baal","Fire","Altar","Prophets"]'),
  ('Ur',                 'place',  'hard',   'OT', 'Abraham''s hometown',                '["Abraham","Home","Leave","Chaldeans","City"]'),
  ('Philippi',           'place',  'hard',   'NT', 'Paul and Silas jailed here',         '["Jail","Paul","Silas","Earthquake","Lydia"]'),
  ('Ark of the Covenant','object', 'easy',   'OT', 'Gold box with the tablets',          '["Box","Gold","Tablets","Angels","Carry"]'),
  ('Manger',             'object', 'easy',   'NT', 'Baby Jesus'' bed',                   '["Baby","Jesus","Hay","Feed","Stable"]'),
  ('Cross',              'object', 'easy',   'NT', 'Jesus died on it',                   '["Jesus","Died","Wood","Nails","Crucify"]'),
  ('Sling',              'object', 'easy',   'OT', 'David''s weapon',                    '["David","Stone","Goliath","Rock","Throw"]'),
  ('Rainbow',            'object', 'easy',   'OT', 'God''s promise in the sky',          '["Colors","Sky","Promise","Noah","Rain"]'),
  ('Crown of Thorns',    'object', 'easy',   'NT', 'Put on Jesus'' head',                '["Jesus","Head","Sharp","Soldiers","King"]'),
  ('Star of Bethlehem',  'object', 'easy',   'NT', 'The wise men followed it',           '["Wise men","Sky","Follow","Bright","Night"]'),
  ('Donkey',             'object', 'easy',   null, 'Jesus rode one; Balaam''s talked',   '["Ride","Animal","Palm Sunday","Talk","Ears"]'),
  ('Dove',               'object', 'easy',   null, 'Olive leaf; Holy Spirit',            '["Bird","Noah","Spirit","Baptism","White"]'),
  ('Shepherd''s Staff',  'object', 'easy',   null, 'Moses turned one into a snake',      '["Stick","Moses","Snake","Sheep","Rod"]'),
  ('Coat of Many Colors','object', 'medium', 'OT', 'Joseph''s gift from Jacob',          '["Joseph","Jacob","Robe","Brothers","Rainbow"]'),
  ('Jawbone of a Donkey','object', 'medium', 'OT', 'Samson''s weapon',                   '["Samson","Weapon","Bone","Thousand","Philistines"]'),
  ('Fleece',             'object', 'medium', 'OT', 'Gideon''s test',                     '["Gideon","Wool","Wet","Dry","Sign"]'),
  ('Golden Calf',        'object', 'medium', 'OT', 'Idol made at Sinai',                 '["Idol","Aaron","Cow","Gold","Worship"]'),
  ('Fiery Furnace',      'object', 'medium', 'OT', 'Three friends walked out unharmed',  '["Fire","Shadrach","Hot","King","Fourth man"]'),
  ('Widow''s Two Coins', 'object', 'medium', 'NT', 'Small gift, biggest heart',          '["Widow","Money","Offering","Small","Gave"]'),
  ('Palm Branch',        'object', 'medium', 'NT', 'Waved when Jesus rode in',           '["Sunday","Wave","Jesus","Donkey","Hosanna"]'),
  ('Loaves and Fishes',  'object', 'medium', 'NT', 'A boy''s lunch fed thousands',       '["Bread","Fish","5000","Boy","Baskets"]'),
  ('Mustard Seed',       'object', 'medium', 'NT', 'Tiny seed, big faith',               '["Small","Faith","Seed","Tree","Grow"]'),
  ('Chariot of Fire',    'object', 'medium', 'OT', 'Elijah''s ride to heaven',           '["Elijah","Fire","Heaven","Horses","Whirlwind"]'),
  ('Pillar of Salt',     'object', 'medium', 'OT', 'Lot''s wife looked back',            '["Lot","Wife","Looked back","Sodom","Statue"]'),
  ('Jacob''s Ladder',    'object', 'medium', 'OT', 'Angels going up and down',           '["Angels","Dream","Stairs","Heaven","Jacob"]'),
  ('Baby Moses'' Basket','object', 'medium', 'OT', 'Floated on the Nile',                '["River","Nile","Baby","Float","Princess"]'),
  ('Trumpet',            'object', 'medium', null, 'Jericho; the last day',              '["Horn","Blow","Jericho","Loud","Music"]'),
  ('Empty Net',          'object', 'medium', 'NT', 'Then 153 fish',                      '["Fish","Boat","Catch","Other side","Peter"]'),
  ('Bronze Serpent',     'object', 'hard',   'OT', 'Look and live',                      '["Snake","Pole","Moses","Bitten","Look"]'),
  ('Floating Axe Head',  'object', 'hard',   'OT', 'Elisha''s miracle',                  '["Elisha","Water","Iron","Float","Borrowed"]'),
  ('Tent Peg',           'object', 'hard',   'OT', 'Jael''s weapon',                     '["Jael","Sisera","Hammer","Tent","Nail"]'),
  ('Alabaster Jar',      'object', 'hard',   'NT', 'Perfume poured on Jesus',            '["Perfume","Poured","Woman","Feet","Expensive"]'),
  ('Armor of God',       'object', 'hard',   'NT', 'Belt, breastplate, shield, sword',   '["Shield","Sword","Helmet","Ephesians","Fight"]'),
  ('Scarlet Cord',       'object', 'hard',   'OT', 'Rahab''s sign',                      '["Rahab","Red","Rope","Window","Spies"]'),
  ('Frankincense',       'object', 'hard',   'NT', 'A wise man''s gift',                 '["Wise men","Gift","Gold","Myrrh","Smell"]'),
  ('Lampstand',          'object', 'hard',   null, 'Seven branches in the tabernacle',   '["Light","Candle","Seven","Gold","Tabernacle"]'),
  ('Creation',           'story',  'easy',   'OT', 'Seven days',                         '["God","Made","World","Days","Beginning"]'),
  ('The Flood',          'story',  'easy',   'OT', 'Forty days of rain',                 '["Noah","Rain","Ark","Water","Forty"]'),
  ('Parting of the Red Sea','story','easy',  'OT', 'Walls of water',                     '["Moses","Water","Split","Egypt","Dry ground"]'),
  ('Feeding the 5,000',  'story',  'easy',   'NT', 'Five loaves, two fish',              '["Bread","Fish","Crowd","Baskets","Boy"]'),
  ('The Birth of Jesus', 'story',  'easy',   'NT', 'No room at the inn',                 '["Christmas","Manger","Mary","Bethlehem","Baby"]'),
  ('The Resurrection',   'story',  'easy',   'NT', 'Third day',                          '["Easter","Tomb","Risen","Alive","Stone"]'),
  ('Jesus Calms the Storm','story','easy',   'NT', 'Peace, be still',                    '["Boat","Wind","Waves","Sleep","Quiet"]'),
  ('The Lost Sheep',     'story',  'easy',   'NT', 'Ninety-nine left behind',            '["Shepherd","99","Lost","Found","Lamb"]'),
  ('Zacchaeus in the Tree','story','easy',   'NT', 'Come down!',                         '["Short","Climb","Sycamore","Tax","Jesus"]'),
  ('The Ten Plagues',    'story',  'medium', 'OT', 'Frogs, flies, hail, darkness',       '["Egypt","Frogs","Pharaoh","Moses","Locusts"]'),
  ('Tower of Babel',     'story',  'medium', 'OT', 'Languages confused',                 '["Tall","Languages","Build","Sky","Confused"]'),
  ('Samson and Delilah', 'story',  'medium', 'OT', 'The secret of his strength',         '["Hair","Strong","Cut","Secret","Philistines"]'),
  ('Jacob and Esau',     'story',  'medium', 'OT', 'Stew for a birthright',              '["Twins","Stew","Birthright","Hairy","Blessing"]'),
  ('Elijah and the Prophets of Baal','story','medium','OT','Fire fell on the wet altar',  '["Fire","Altar","Water","Carmel","Prophets"]'),
  ('Esther Saves Her People','story','medium','OT', 'If I perish, I perish',             '["Queen","Haman","King","Jews","Banquet"]'),
  ('The Wise Men',       'story',  'medium', 'NT', 'Gold, frankincense, myrrh',          '["Star","Gifts","Three","Kings","East"]'),
  ('Jesus in the Temple as a Boy','story','medium','NT','Twelve years old, lost for 3 days','["Twelve","Lost","Teachers","Jerusalem","Parents"]'),
  ('Water into Wine',    'story',  'medium', 'NT', 'First miracle, at a wedding',        '["Wedding","Cana","Jars","Miracle","Drink"]'),
  ('Palm Sunday',        'story',  'medium', 'NT', 'Hosanna!',                           '["Donkey","Branches","Jerusalem","Hosanna","Coats"]'),
  ('The Lost Coin',      'story',  'medium', 'NT', 'She swept the whole house',          '["Woman","Sweep","Money","Lamp","Found"]'),
  ('The Sower',          'story',  'medium', 'NT', 'Seed on four kinds of ground',       '["Seed","Soil","Farmer","Birds","Thorns"]'),
  ('Wise and Foolish Builders','story','medium','NT','Rock vs. sand',                    '["House","Rock","Sand","Storm","Build"]'),
  ('Doubting Thomas',    'story',  'medium', 'NT', 'Unless I see the nail marks',        '["Thomas","Believe","Wounds","Hands","See"]'),
  ('Road to Damascus',   'story',  'medium', 'NT', 'Saul, why do you persecute me?',     '["Saul","Light","Blind","Road","Paul"]'),
  ('Pentecost',          'story',  'medium', 'NT', 'Wind, fire, languages',              '["Holy Spirit","Fire","Wind","Languages","Peter"]'),
  ('The Transfiguration','story',  'medium', 'NT', 'Jesus shone like the sun',           '["Mountain","Shine","Moses","Elijah","Bright"]'),
  ('The Rich Young Ruler','story', 'medium', 'NT', 'Went away sad',                      '["Rich","Sell","Poor","Sad","Follow"]'),
  ('The Ten Lepers',     'story',  'medium', 'NT', 'Only one said thank you',            '["Healed","Ten","Thank","One","Sick"]'),
  ('The Woman at the Well','story','medium', 'NT', 'Living water',                       '["Water","Samaritan","Well","Husbands","Drink"]'),
  ('Jesus Washes the Disciples'' Feet','story','medium','NT','A towel and a basin',      '["Feet","Towel","Water","Servant","Supper"]'),
  ('The Great Commission','story', 'medium', 'NT', 'Go and make disciples',              '["Go","Nations","Disciples","Baptize","Teach"]'),
  ('Abraham and Isaac',  'story',  'medium', 'OT', 'God provided a ram',                 '["Sacrifice","Ram","Mountain","Son","Knife"]'),
  ('Joseph in Egypt',    'story',  'medium', 'OT', 'From prison to palace',              '["Dreams","Pharaoh","Famine","Brothers","Prison"]'),
  ('Baby Moses in the Nile','story','medium','OT', 'Found by a princess',                '["Basket","River","Princess","Baby","Sister"]'),
  ('Balaam''s Donkey',   'story',  'hard',   'OT', 'The donkey saw the angel first',     '["Donkey","Talk","Angel","Sword","Beat"]'),
  ('The Writing on the Wall','story','hard', 'OT', 'Mene, mene, tekel',                  '["Hand","Wall","King","Feast","Daniel"]'),
  ('The Valley of Dry Bones','story','hard', 'OT', 'Can these bones live?',              '["Bones","Ezekiel","Skeleton","Alive","Army"]'),
  ('Naaman''s Leprosy',  'story',  'hard',   'OT', 'Seven dips in the Jordan',           '["Leprosy","Seven","River","Wash","Elisha"]'),
  ('Solomon and the Two Mothers','story','hard','OT','Cut the baby in half?',            '["Baby","Sword","Wise","Two","Women"]'),
  ('Jacob Wrestles with God','story','hard', 'OT', 'A new name and a limp',              '["Wrestle","Night","Hip","Israel","Bless"]'),
  ('Ananias and Sapphira','story', 'hard',   'NT', 'They lied about the money',          '["Lied","Money","Land","Died","Peter"]'),
  ('Philip and the Ethiopian','story','hard','NT', 'Do you understand what you read?',   '["Chariot","Isaiah","Baptize","Official","Read"]'),
  ('Peter''s Escape from Prison','story','hard','NT','Rhoda left him at the door',       '["Angel","Chains","Rhoda","Door","Herod"]'),
  ('Paul and Silas in Prison','story','hard','NT', 'Singing at midnight, earthquake',    '["Singing","Earthquake","Jailer","Chains","Midnight"]'),
  ('Gideon''s Fleece',   'story',  'hard',   'OT', 'Wet, then dry',                      '["Wool","Wet","Dry","Sign","Dew"]'),
  ('The Sun Stands Still','story', 'hard',   'OT', 'Joshua''s long day',                 '["Joshua","Sun","Moon","Battle","Day"]'),
  ('The Widow''s Oil',   'story',  'hard',   'OT', 'Jars kept filling',                  '["Jars","Oil","Elisha","Widow","Pour"]'),
  ('Forgiveness',        'theme',  'medium', null, 'Seventy times seven',                '["Sorry","Forgive","Sin","Pardon","Let go"]'),
  ('Faith',              'theme',  'medium', null, 'Trusting what you can''t see',       '["Believe","Trust","Hope","Sure","Unseen"]'),
  ('Grace',              'theme',  'medium', null, 'Undeserved favor',                   '["Gift","Free","Deserve","Favor","Saved"]'),
  ('Prayer',             'theme',  'medium', null, 'Talking with God',                   '["Talk","God","Kneel","Ask","Amen"]'),
  ('Baptism',            'theme',  'medium', null, 'Under the water and up',             '["Water","Dunk","Church","Sprinkle","John"]'),
  ('Communion',          'theme',  'medium', 'NT', 'Bread and cup',                      '["Bread","Cup","Juice","Church","Remember"]'),
  ('The Trinity',        'theme',  'medium', null, 'Three in one',                       '["Father","Son","Spirit","Three","One"]'),
  ('The Fruit of the Spirit','theme','medium','NT','Love, joy, peace...',                '["Love","Joy","Peace","Patience","Galatians"]'),
  ('The Golden Rule',    'theme',  'medium', 'NT', 'Do to others...',                    '["Treat","Others","Want","Do unto","Nice"]'),
  ('The Lord''s Prayer', 'theme',  'medium', 'NT', 'Our Father in heaven',               '["Our Father","Heaven","Daily bread","Jesus taught","Amen"]'),
  ('The Beatitudes',     'theme',  'medium', 'NT', 'Blessed are the...',                 '["Blessed","Sermon","Mount","Poor","Meek"]'),
  ('Salvation',          'theme',  'medium', null, 'Being rescued from sin',             '["Saved","Rescue","Jesus","Sin","Heaven"]'),
  ('Heaven',             'theme',  'medium', null, 'Where God lives',                    '["God","Clouds","Sky","Angels","Forever"]'),
  ('Repentance',         'theme',  'medium', null, 'Turning around',                     '["Sorry","Turn","Sin","Change","Confess"]'),
  ('Worship',            'theme',  'medium', null, 'Singing to God',                     '["Sing","Praise","Church","Music","Hands"]'),
  ('Missionary',         'theme',  'medium', null, 'Sent to share the good news',        '["Travel","Preach","Country","Gospel","Sent"]'),
  ('Parable',            'theme',  'medium', 'NT', 'A story with a lesson',              '["Story","Jesus","Lesson","Teach","Meaning"]'),
  ('Miracle',            'theme',  'medium', null, 'Something only God can do',          '["Amazing","Power","Heal","Impossible","Wonder"]'),
  ('Angel',              'theme',  'medium', null, 'God''s messenger',                   '["Wings","Heaven","Messenger","Halo","Gabriel"]'),
  ('Sabbath',            'theme',  'medium', null, 'A day to rest',                      '["Rest","Seventh","Day","Sunday","Saturday"]'),
  ('Temptation',         'theme',  'medium', null, 'Wanting to do wrong',                '["Sin","Devil","Want","Wrong","Resist"]'),
  ('Covenant',           'theme',  'hard',   null, 'A promise between God and people',   '["Promise","Agreement","Rainbow","Sign","Abraham"]'),
  ('Prophet',            'theme',  'hard',   null, 'Speaks God''s message',              '["Message","Future","God","Speak","Isaiah"]'),
  ('Tithe',              'theme',  'hard',   null, 'Ten percent',                        '["Money","Ten","Percent","Give","Offering"]')
) as v(text, category, difficulty, testament, hint, banned_words)
where not exists (select 1 from game_prompts g where g.text = v.text);
