/* v12_4_guess_the_fake.sql
   Guess the Fake: adds 20 easy and 12 hard rounds (statement 3 is always the fake).
   Adds only, nothing deleted. Safe to re-run. Paste the whole file and Run. */

insert into gtf_questions (topic, difficulty, testament, statement_1, statement_2, statement_3, fake_index, explanation, reference, context) values
  ('Jesus Calms the Storm', 'easy', 'NT', 'Jesus was asleep in the boat when the storm hit.', 'Jesus said "Quiet! Be still!" and the wind stopped.', 'The disciples swam to shore to escape the storm.', 3, 'They stayed in the boat; Jesus calmed the storm.', 'Mark 4:35-41', 'A sudden storm on the Sea of Galilee terrifies experienced fishermen.'),
  ('Baby Moses', 'easy', 'OT', 'Moses'' mother hid him in a basket on the Nile River.', 'Pharaoh''s daughter found him and raised him as her son.', 'Moses was found floating in a wooden boat on the Red Sea.', 3, 'It was a basket on the Nile, not a boat on the Red Sea.', 'Exodus 2:1-10', 'Pharaoh has ordered Hebrew baby boys killed.'),
  ('The Red Sea Crossing', 'easy', 'OT', 'God parted the sea and Israel crossed on dry ground.', 'Pharaoh''s army drowned when the water came back.', 'The Israelites crossed the sea in boats that Noah built.', 3, 'No boats; they walked through on dry ground.', 'Exodus 14', 'Israel is trapped between Pharaoh''s army and the sea.'),
  ('The Lost Coin', 'easy', 'NT', 'A woman lost one of her ten silver coins.', 'She lit a lamp and swept the house until she found it.', 'She gave up and went out to buy a new coin.', 3, 'She searched until she found it, then threw a party.', 'Luke 15:8-10', 'One of three "lost" parables Jesus told in a row.'),
  ('The Shepherds at Christmas', 'easy', 'NT', 'An angel told the shepherds that a Savior had been born.', 'A huge crowd of angels praised God saying "Glory to God in the highest."', 'The shepherds brought baby Jesus a lamb as a present.', 3, 'The Bible never mentions the shepherds bringing a gift.', 'Luke 2:8-20', 'Night shift in the fields outside Bethlehem.'),
  ('Jesus and the Children', 'easy', 'NT', 'Jesus said "Let the little children come to me."', 'The disciples tried to send the children away.', 'Jesus said children had to wait until they were grown up to come to him.', 3, 'He welcomed them and said the kingdom belongs to such as these.', 'Mark 10:13-16', 'Parents bring their kids to Jesus for a blessing.'),
  ('Peter Walks on Water', 'easy', 'NT', 'Peter got out of the boat and walked toward Jesus on the water.', 'Peter started to sink when he looked at the wind and waves.', 'Peter walked all the way to shore without getting wet.', 3, 'He sank and Jesus caught him.', 'Matthew 14:22-33', 'Late at night, the disciples see Jesus walking on the lake.'),
  ('The Widow''s Two Coins', 'easy', 'NT', 'A poor widow put two tiny coins into the temple offering.', 'Jesus said she gave more than all the rich people.', 'Jesus told her to take her coins back because they were too small.', 3, 'He praised her; she gave everything she had.', 'Mark 12:41-44', 'Jesus watches people drop money into the offering box.'),
  ('Water into Wine', 'easy', 'NT', 'Jesus'' first miracle happened at a wedding in Cana.', 'Servants filled six stone jars with water.', 'At the end of the party Jesus turned the wine back into water.', 3, 'The wine stayed wine, and it was the best of the night.', 'John 2:1-11', 'The wedding host has run out of wine.'),
  ('Jesus in the Temple as a Boy', 'easy', 'NT', 'Jesus was twelve when his parents lost track of him in Jerusalem.', 'They found him in the temple talking with the teachers.', 'Jesus had run off to join a fishing boat on the lake.', 3, 'He was in the temple, "in my Father''s house."', 'Luke 2:41-52', 'The family is heading home after Passover.'),
  ('The Lord''s Prayer', 'easy', 'NT', 'Jesus taught his disciples to pray "Our Father in heaven."', 'The prayer includes "Give us today our daily bread."', 'The prayer ends with "and please give us lots of money."', 3, 'Nothing about money; it asks for forgiveness and protection.', 'Matthew 6:9-13', 'The disciples ask Jesus to teach them to pray.'),
  ('Elijah and the Ravens', 'easy', 'OT', 'Ravens brought Elijah bread and meat every morning and evening.', 'Elijah drank water from a brook.', 'Elijah lived in a cave with a friendly lion.', 3, 'Birds fed him; no lion.', '1 Kings 17:1-6', 'Elijah is hiding during a drought he announced.'),
  ('The Good Shepherd', 'easy', 'NT', 'Jesus said "I am the good shepherd."', 'The good shepherd lays down his life for the sheep.', 'Jesus said the good shepherd sells the sheep when they get sick.', 3, 'He protects them; a hired hand runs away.', 'John 10:11-15', 'Jesus explains how he cares for his people.'),
  ('The Twelve Spies', 'easy', 'OT', 'Moses sent twelve spies into the Promised Land.', 'They carried back a cluster of grapes so big it took two men.', 'All twelve spies said "Let''s go take the land right now!"', 3, 'Only Joshua and Caleb trusted God; the other ten were afraid.', 'Numbers 13-14', 'Israel is on the edge of Canaan.'),
  ('David the Shepherd Boy', 'easy', 'OT', 'David was the youngest of Jesse''s sons.', 'David killed a lion and a bear while protecting his sheep.', 'David was chosen as king because he was the tallest.', 3, 'God looks at the heart, not the outside.', '1 Samuel 16-17', 'Samuel visits Bethlehem to anoint a new king.'),
  ('The Angel Visits Mary', 'easy', 'NT', 'The angel Gabriel told Mary she would have a son named Jesus.', 'Mary answered, "I am the Lord''s servant."', 'The angel told Mary to name the baby Joseph Junior.', 3, 'The name was Jesus.', 'Luke 1:26-38', 'Mary is a young woman engaged to Joseph in Nazareth.'),
  ('God Makes People', 'easy', 'OT', 'God formed the first man from the dust of the ground.', 'God made the first woman while Adam was in a deep sleep.', 'God made people on the third day of creation.', 3, 'People were made on the sixth day.', 'Genesis 1:26-27; 2:7-22', 'The last thing God makes before resting.'),
  ('The Great Commission', 'easy', 'NT', 'Jesus told his followers to go and make disciples of all nations.', 'Jesus promised, "I am with you always."', 'Jesus told them to stay in Jerusalem forever and never travel.', 3, 'He sent them to the whole world.', 'Matthew 28:18-20', 'Jesus'' last instructions before returning to heaven.'),
  ('Samuel Hears God', 'easy', 'OT', 'Young Samuel heard a voice calling his name at night.', 'Eli told him to answer, "Speak, Lord, your servant is listening."', 'The voice turned out to be Eli playing a prank.', 3, 'It was God, calling Samuel to be a prophet.', '1 Samuel 3', 'Samuel is a boy serving in the tabernacle.'),
  ('The Burning Bush', 'easy', 'OT', 'God spoke to Moses from a bush that was on fire but did not burn up.', 'God told Moses to take off his sandals because the ground was holy.', 'The bush burned to ashes as soon as God finished speaking.', 3, 'The bush was never consumed.', 'Exodus 3', 'Moses is a shepherd in Midian, 40 years after fleeing Egypt.'),
  ('Absalom', 'hard', 'OT', 'Absalom was David''s son and led a rebellion against him.', 'Absalom got caught by his hair in a tree while riding a mule.', 'David killed Absalom himself in battle.', 3, 'Joab killed him; David wept when he heard.', '2 Samuel 15-18', 'A handsome prince steals the hearts of Israel.'),
  ('Hezekiah', 'hard', 'OT', 'God added fifteen years to Hezekiah''s life when he was dying.', 'As a sign, the shadow on the stairway went backward ten steps.', 'Hezekiah was king of the northern kingdom of Israel.', 3, 'He was king of Judah, in Jerusalem.', '2 Kings 20:1-11', 'A good king gets sick while Assyria threatens.'),
  ('Josiah', 'hard', 'OT', 'Josiah became king when he was eight years old.', 'The Book of the Law was found while the temple was being repaired in his reign.', 'Josiah tore down the temple and built a palace in its place.', 3, 'He repaired the temple and led a revival.', '2 Kings 22-23', 'A boy king in a nation that has forgotten God.'),
  ('Hosea', 'hard', 'OT', 'God told the prophet Hosea to marry a woman named Gomer.', 'Hosea''s marriage was a picture of God''s love for unfaithful Israel.', 'Hosea was swallowed by a great fish.', 3, 'That was Jonah.', 'Hosea 1-3', 'A prophet whose own life becomes the sermon.'),
  ('Elijah on the Mountain', 'hard', 'OT', 'Elijah ran from Queen Jezebel all the way to Mount Horeb.', 'God was not in the wind, earthquake, or fire, but spoke in a gentle whisper.', 'Elijah stayed on the mountain for the rest of his life.', 3, 'God sent him back with a job to do.', '1 Kings 19', 'Right after the victory on Mount Carmel, Elijah is exhausted and afraid.'),
  ('Joseph and Potiphar', 'hard', 'OT', 'Potiphar''s wife falsely accused Joseph.', 'In prison, Joseph explained the dreams of the cupbearer and the baker.', 'Potiphar was the Pharaoh of Egypt.', 3, 'Potiphar was an officer, captain of the guard.', 'Genesis 39-40', 'Joseph is a slave in a rich man''s house.'),
  ('The Bronze Serpent', 'hard', 'OT', 'Moses made a bronze snake and put it on a pole.', 'Anyone who was bitten and looked at it lived.', 'Jesus said people should worship the bronze snake.', 3, 'Jesus compared himself to it being lifted up; Hezekiah later destroyed it because people worshiped it.', 'Numbers 21:4-9; John 3:14', 'Poisonous snakes are biting the grumbling Israelites.'),
  ('Paul''s Shipwreck', 'hard', 'NT', 'Paul was shipwrecked on the island of Malta.', 'A viper bit Paul and he shook it off unharmed.', 'Paul was sailing to Rome on vacation.', 3, 'He was a prisoner being taken to appeal to Caesar.', 'Acts 27-28', 'Two weeks of storm in the Mediterranean.'),
  ('Peter''s Escape', 'hard', 'NT', 'An angel freed Peter from prison the night before Herod planned to kill him.', 'The servant girl Rhoda was so excited she left Peter standing at the door.', 'Peter dug his way out of prison with a spoon.', 3, 'The chains fell off and the gate opened by itself.', 'Acts 12:1-17', 'James has just been executed; the church is praying all night.'),
  ('Solomon''s Wise Judgment', 'hard', 'OT', 'Two women each claimed the same living baby was theirs.', 'Solomon suggested cutting the baby in two.', 'Solomon kept the baby and raised him in the palace.', 3, 'The real mother gave up her claim to save the child, so Solomon gave him to her.', '1 Kings 3:16-28', 'Solomon has just asked God for wisdom.'),
  ('The Seven Churches', 'hard', 'NT', 'Revelation opens with letters to seven churches.', 'The church in Laodicea was called "lukewarm."', 'One of the seven letters was written to the church in Jerusalem.', 3, 'All seven were in Asia Minor (modern Turkey).', 'Revelation 2-3', 'John is in exile on Patmos.'),
  ('Enoch', 'hard', 'OT', 'Enoch walked with God, and God took him without dying.', 'Enoch was the father of Methuselah.', 'Enoch built the first city in the Bible.', 3, 'Cain built the first city; Enoch is known for walking with God.', 'Genesis 5:21-24', 'One of only two people in the Bible who never died.')
on conflict (topic) do nothing;
