/* v12_3_price_is_right.sql
   Price Is Right: adds 40 kid-sized questions in a new category, Everyday Bible Numbers.
   Adds only, nothing deleted. Safe to re-run. Paste the whole file and Run. */

insert into pir_questions (question, host_answer, accepted_answer, numeric_target, unit, category, background, reference_1, fact_type)
select * from (values
  ('How many plagues did God send on Egypt?',                                                  '10',            'Exact: 10',          10,   'plagues',        'Everyday Bible Numbers', 'Blood, frogs, gnats, flies, livestock, boils, hail, locusts, darkness, death of the firstborn.', 'Exodus 7-12',       'Bible count'),
  ('How many books are in the whole Bible?',                                                   '66',            'Exact: 66',          66,   'books',          'Everyday Bible Numbers', '39 in the Old Testament, 27 in the New.',                                                   'Table of contents', 'Bible count'),
  ('How many sons did Jacob have?',                                                            '12',            'Exact: 12',          12,   'sons',           'Everyday Bible Numbers', 'They became the twelve tribes of Israel.',                                                  'Genesis 35:22-26',  'Bible count'),
  ('How many smooth stones did David pick up before facing Goliath?',                          '5',             'Exact: 5',           5,    'stones',         'Everyday Bible Numbers', 'He only needed one.',                                                                        '1 Samuel 17:40',    'Bible count'),
  ('How many lepers did Jesus heal at once, with only one coming back to say thank you?',      '10',            'Exact: 10',          10,   'lepers',         'Everyday Bible Numbers', 'The one who returned was a Samaritan.',                                                     'Luke 17:11-19',     'Bible count'),
  ('Jesus said to forgive not seven times but seventy times seven. What number is that?',      '490',           'Accept 490 (or 77 in some translations)', 490, 'times',      'Everyday Bible Numbers', 'The point is: stop counting.',                                                              'Matthew 18:22',     'Bible count'),
  ('How many years did Jacob work for Laban to marry Rachel?',                                 '14',            'Exact: 14',          14,   'years',          'Everyday Bible Numbers', 'Seven years, then tricked into marrying Leah, then seven more.',                            'Genesis 29:18-30',  'Bible count'),
  ('How many chapters are in the book of Psalms?',                                             '150',           'Exact: 150',         150,  'chapters',       'Everyday Bible Numbers', 'The longest book in the Bible by chapters.',                                                'Psalms',            'Bible count'),
  ('How many pieces of silver did Judas receive for betraying Jesus?',                         '30',            'Exact: 30',          30,   'pieces of silver','Everyday Bible Numbers','The price of a slave in Exodus 21:32.',                                                     'Matthew 26:15',     'Bible count'),
  ('How many spies did Moses send into Canaan?',                                               '12',            'Exact: 12',          12,   'spies',          'Everyday Bible Numbers', 'One from each tribe. Only Joshua and Caleb trusted God.',                                   'Numbers 13',        'Bible count'),
  ('How many years did it take Solomon to build the temple?',                                  '7',             'Exact: 7',           7,    'years',          'Everyday Bible Numbers', 'His own palace took 13 years.',                                                             '1 Kings 6:38',      'Bible count'),
  ('How old was Josiah when he became king?',                                                  '8',             'Exact: 8',           8,    'years old',      'Everyday Bible Numbers', 'He reigned 31 years and led a huge revival.',                                               '2 Kings 22:1',      'Bible count'),
  ('How old was Jesus when his parents found him talking with the teachers in the temple?',    '12',            'Exact: 12',          12,   'years old',      'Everyday Bible Numbers', 'They had been searching for three days.',                                                   'Luke 2:42-46',      'Bible count'),
  ('About how old was Jesus when he began his public ministry?',                               '30',            '29-31',              30,   'years old',      'Everyday Bible Numbers', 'Luke says "about thirty."',                                                                  'Luke 3:23',         'Bible count'),
  ('How old was Abraham when Isaac was born?',                                                 '100',           'Exact: 100',         100,  'years old',      'Everyday Bible Numbers', 'Sarah was 90.',                                                                              'Genesis 21:5',      'Bible count'),
  ('How old was Sarah when Isaac was born?',                                                   '90',            'Exact: 90',          90,   'years old',      'Everyday Bible Numbers', 'She laughed when she first heard the promise.',                                             'Genesis 17:17',     'Bible count'),
  ('How many fish were in the net the disciples hauled in after the resurrection?',            '153',           'Exact: 153',         153,  'fish',           'Everyday Bible Numbers', 'And the net did not tear.',                                                                 'John 21:11',        'Bible count'),
  ('How many days after his resurrection did Jesus ascend into heaven?',                       '40',            'Exact: 40',          40,   'days',           'Everyday Bible Numbers', 'He appeared to his followers during those days.',                                           'Acts 1:3',          'Bible count'),
  ('About how many believers were gathered when Matthias was chosen to replace Judas?',        'about 120',     '110-130',            120,  'people',         'Everyday Bible Numbers', 'This was before Pentecost.',                                                                'Acts 1:15',         'Bible count'),
  ('How many disciples did Jesus send out two by two in Luke 10?',                             '72',            'Accept 70 or 72 (translations differ)', 72, 'disciples',   'Everyday Bible Numbers', 'Some manuscripts say seventy.',                                                             'Luke 10:1',         'Bible count'),
  ('How many bridesmaids were in Jesus'' parable of the lamps?',                                '10',            'Exact: 10',          10,   'bridesmaids',    'Everyday Bible Numbers', 'Five wise, five foolish.',                                                                  'Matthew 25:1',      'Bible count'),
  ('How many sheep did the shepherd leave behind to look for the one that was lost?',          '99',            'Exact: 99',          99,   'sheep',          'Everyday Bible Numbers', 'Out of one hundred.',                                                                        'Luke 15:4',         'Bible count'),
  ('How many churches received letters at the start of Revelation?',                           '7',             'Exact: 7',           7,    'churches',       'Everyday Bible Numbers', 'Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, Laodicea.',                      'Revelation 1:11',   'Bible count'),
  ('How many gates does the New Jerusalem have?',                                              '12',            'Exact: 12',          12,   'gates',          'Everyday Bible Numbers', 'Each one made of a single pearl.',                                                          'Revelation 21:12-21','Bible count'),
  ('How many stone tablets were the Ten Commandments written on?',                             '2',             'Exact: 2',           2,    'tablets',        'Everyday Bible Numbers', 'Written by the finger of God.',                                                             'Exodus 31:18',      'Bible count'),
  ('How many days was Saul blind after meeting Jesus on the road to Damascus?',                '3',             'Exact: 3',           3,    'days',           'Everyday Bible Numbers', 'He did not eat or drink until Ananias came.',                                               'Acts 9:9',          'Bible count'),
  ('How many years did the Israelites live in Egypt before the Exodus?',                       '430',           '400-430',            430,  'years',          'Everyday Bible Numbers', 'Genesis 15 rounds it to 400.',                                                              'Exodus 12:40',      'Bible count'),
  ('How many years was Judah in exile in Babylon?',                                            '70',            'Exact: 70',          70,   'years',          'Everyday Bible Numbers', 'Jeremiah predicted it.',                                                                    'Jeremiah 25:11',    'Bible count'),
  ('How many prophets of Baal did Elijah face on Mount Carmel?',                               '450',           'Exact: 450',         450,  'prophets',       'Everyday Bible Numbers', 'Plus 400 prophets of Asherah were invited.',                                                '1 Kings 18:22',     'Bible count'),
  ('How many husbands had the Samaritan woman at the well had?',                               '5',             'Exact: 5',           5,    'husbands',       'Everyday Bible Numbers', 'And the man she lived with was not her husband.',                                           'John 4:18',         'Bible count'),
  ('How many years had the man at the pool of Bethesda been unable to walk?',                  '38',            'Exact: 38',          38,   'years',          'Everyday Bible Numbers', 'Jesus asked him, "Do you want to get well?"',                                               'John 5:5',          'Bible count'),
  ('How many years had the woman who touched Jesus'' cloak been bleeding?',                     '12',            'Exact: 12',          12,   'years',          'Everyday Bible Numbers', 'She had spent everything on doctors.',                                                      'Mark 5:25',         'Bible count'),
  ('How many hours of darkness covered the land while Jesus was on the cross?',                '3',             'Exact: 3',           3,    'hours',          'Everyday Bible Numbers', 'From noon until three in the afternoon.',                                                   'Matthew 27:45',     'Bible count'),
  ('How many rivers flowed out of the Garden of Eden?',                                        '4',             'Exact: 4',           4,    'rivers',         'Everyday Bible Numbers', 'Pishon, Gihon, Tigris, Euphrates.',                                                         'Genesis 2:10-14',   'Bible count'),
  ('How many pairs of each CLEAN animal did Noah take on the ark?',                            '7',             'Exact: 7',           7,    'pairs',          'Everyday Bible Numbers', 'Only one pair of the unclean animals.',                                                     'Genesis 7:2',       'Bible count'),
  ('How old was Joseph when his brothers sold him?',                                           '17',            'Exact: 17',          17,   'years old',      'Everyday Bible Numbers', 'He was 30 when he stood before Pharaoh.',                                                   'Genesis 37:2',      'Bible count'),
  ('How old was Moses when he stood before Pharaoh and said "Let my people go"?',              '80',            'Exact: 80',          80,   'years old',      'Everyday Bible Numbers', 'Aaron was 83.',                                                                             'Exodus 7:7',        'Bible count'),
  ('How old was Noah when the flood came?',                                                    '600',           'Exact: 600',         600,  'years old',      'Everyday Bible Numbers', 'He lived 350 more years after it.',                                                         'Genesis 7:6',       'Bible count'),
  ('How many verses are in Psalm 119, the longest chapter in the Bible?',                      '176',           'Exact: 176',         176,  'verses',         'Everyday Bible Numbers', 'It is an acrostic: 22 sections, one per Hebrew letter.',                                    'Psalm 119',         'Bible count'),
  ('How many times in total did Israel march around Jericho over the seven days?',             '13',            'Exact: 13',          13,   'laps',           'Everyday Bible Numbers', 'Once a day for six days, then seven times on day seven.',                                   'Joshua 6:3-4',      'Bible count')
) as v(question, host_answer, accepted_answer, numeric_target, unit, category, background, reference_1, fact_type)
where not exists (select 1 from pir_questions p where p.question = v.question);
