-- v8 migration — Guess the Fake question bank (two truths and a lie).
-- Feeds the Guess the Fake game. Safe to run on live data (idempotent).
--
-- statement_1 & statement_2 are TRUE, statement_3 is the FAKE (fake_index = 3).
-- The app shuffles the three statements each time it shows a round.

create table if not exists gtf_questions (
  id uuid primary key default gen_random_uuid(),
  topic text not null,
  difficulty text not null default 'medium',   -- easy | medium | hard
  testament text,                              -- OT | NT | null
  statement_1 text not null,
  statement_2 text not null,
  statement_3 text not null,
  fake_index int not null default 3,           -- which statement is the lie (1, 2, or 3)
  explanation text,                            -- the correction, for the leader
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Unique topic lets the seed below be re-run safely (on conflict do nothing).
create unique index if not exists gtf_questions_topic_key on gtf_questions (topic);
create index if not exists gtf_questions_active_idx on gtf_questions (active, difficulty);

-- RLS disabled to match the other game tables (see game_prompts).
alter table gtf_questions disable row level security;

-- Seed the 85-round bank. Re-running is safe: existing topics are skipped.
insert into gtf_questions (topic, difficulty, testament, statement_1, statement_2, statement_3, fake_index, explanation) values
  ('Noah', 'easy', 'OT', 'Noah brought his three sons — Shem, Ham, and Japheth — onto the ark.', 'God set a rainbow in the sky as the sign of his promise after the flood.', 'The flood rain lasted exactly 100 days and 100 nights.', 3, 'It rained 40 days and 40 nights, not 100.'),
  ('Creation', 'easy', 'OT', 'God created light on the first day.', 'God rested on the seventh day.', 'God created the sun, moon, and stars on the second day.', 3, 'The sun, moon, and stars were made on the fourth day.'),
  ('David & Goliath', 'easy', 'OT', 'David defeated the giant Goliath with a sling and a stone.', 'David played the harp to calm King Saul.', 'David built the temple in Jerusalem.', 3, 'His son Solomon built the temple, not David.'),
  ('Jonah', 'easy', 'OT', 'Jonah was swallowed by a great fish and stayed inside three days and nights.', 'God told Jonah to preach to the city of Nineveh.', 'Jonah gladly obeyed God and sailed straight to Nineveh.', 3, 'Jonah ran the opposite way, sailing toward Tarshish.'),
  ('Jesus'' Birth', 'easy', 'NT', 'Jesus was born in Bethlehem.', 'An angel announced the good news to shepherds in the fields.', 'The Bible says exactly three wise men visited Jesus.', 3, 'The number of wise men is never given — only three gifts are named.'),
  ('Adam & Eve', 'easy', 'OT', 'God placed Adam and Eve in the Garden of Eden.', 'A serpent tempted Eve to eat the forbidden fruit.', 'The Bible clearly says the forbidden fruit was an apple.', 3, 'The fruit is never identified as an apple.'),
  ('Daniel', 'easy', 'OT', 'Daniel was thrown into a den of lions and was unharmed.', 'Daniel chose to eat vegetables and water instead of the king''s rich food.', 'Daniel interpreted dreams for Pharaoh in Egypt.', 3, 'That was Joseph. Daniel served kings of Babylon and Persia.'),
  ('Ten Commandments', 'easy', 'OT', 'God gave Moses the commandments on Mount Sinai.', 'The commandments were written on tablets of stone.', 'There were twelve commandments, one for each tribe of Israel.', 3, 'There were ten commandments.'),
  ('Jesus'' Miracles', 'easy', 'NT', 'Jesus fed over 5,000 people with five loaves and two fish.', 'Jesus turned water into wine at a wedding in Cana.', 'Jesus'' very first miracle was healing a blind man.', 3, 'His first miracle was turning water into wine at Cana.'),
  ('The Resurrection', 'easy', 'NT', 'Jesus rose from the dead on the third day.', 'An angel rolled the stone away from the tomb.', 'After rising, Jesus first appeared to Pontius Pilate.', 3, 'He first appeared to Mary Magdalene and the women, not Pilate.'),
  ('Samson', 'easy', 'OT', 'Samson''s great strength was connected to his uncut hair.', 'Delilah discovered the secret of Samson''s strength.', 'Samson defeated an army using the jawbone of a lion.', 3, 'He used the jawbone of a donkey.'),
  ('Joseph', 'easy', 'OT', 'Joseph''s brothers sold him into slavery in Egypt.', 'Joseph interpreted Pharaoh''s dreams about seven years of plenty and famine.', 'Joseph''s father gave him a coat made of solid gold.', 3, 'It was a coat of many colors (a richly ornamented robe).'),
  ('Moses', 'easy', 'OT', 'As a baby, Moses was placed in a basket on the Nile and found by Pharaoh''s daughter.', 'Moses saw a bush that was burning but was not burned up.', 'Moses himself led the people across the Jordan into the Promised Land.', 3, 'Moses died first; Joshua led them across the Jordan.'),
  ('Palm Sunday', 'easy', 'NT', 'Jesus rode into Jerusalem on a donkey.', 'Crowds spread palm branches and cloaks on the road.', 'Jesus rode in on a white horse leading an army.', 3, 'He came humbly on a donkey, not a war horse.'),
  ('The Good Samaritan', 'easy', 'NT', 'A man was beaten by robbers and left on the road.', 'A Samaritan stopped to help him after others passed by.', 'Jesus told this story to explain the best way to catch fish.', 3, 'The parable answers the question ''Who is my neighbor?'''),
  ('Wise & Foolish Builders', 'easy', 'NT', 'The wise man built his house on the rock.', 'The foolish man built his house on the sand.', 'Both houses stood firm through the storm.', 3, 'The house on sand collapsed when the storm came.'),
  ('The Lost Sheep', 'easy', 'NT', 'The shepherd left the ninety-nine to search for one lost sheep.', 'He rejoiced and carried it home when he found it.', 'The shepherd gave up and never found the lost sheep.', 3, 'He searched until he found it, then celebrated.'),
  ('Peter', 'medium', 'NT', 'Peter denied knowing Jesus three times before the rooster crowed.', 'Peter walked on water toward Jesus before he began to sink.', 'Peter was the short tax collector Jesus called down from a sycamore tree.', 3, 'That was Zacchaeus, not Peter.'),
  ('John the Baptist', 'medium', 'NT', 'John baptized people in the Jordan River.', 'John ate locusts and wild honey.', 'John the Baptist was Jesus'' twin brother.', 3, 'John was a relative of Jesus, not his twin.'),
  ('Abraham', 'medium', 'OT', 'God promised Abraham descendants as numerous as the stars.', 'Abraham was willing to sacrifice his son Isaac before God stopped him.', 'Sarah gave birth to Isaac while she was in her twenties.', 3, 'Sarah was about 90 when Isaac was born.'),
  ('Paul', 'medium', 'NT', 'Paul was blinded by a bright light on the road to Damascus.', 'Paul wrote many of the letters found in the New Testament.', 'Paul was one of Jesus'' original twelve disciples.', 3, 'Paul (formerly Saul) was not one of the Twelve; he came later.'),
  ('Tower of Babel', 'medium', 'OT', 'The people built a tall tower to try to reach the heavens.', 'God confused their language so they couldn''t understand each other.', 'God destroyed the tower with fire and lightning.', 3, 'God scattered the people by confusing their language; no fire.'),
  ('Queen Esther', 'medium', 'OT', 'Esther became queen of Persia.', 'Esther risked her life to save her people, the Jews.', 'Esther led the Israelite army into battle against Egypt.', 3, 'Esther saved her people through courage before the king, not battle.'),
  ('Solomon', 'medium', 'OT', 'Solomon asked God for wisdom.', 'Solomon built the first temple in Jerusalem.', 'Solomon defeated Goliath as a young shepherd.', 3, 'That was his father David.'),
  ('The Plagues of Egypt', 'medium', 'OT', 'One plague turned the Nile River to blood.', 'The final plague was the death of the firstborn.', 'One of the plagues was a swarm of giant spiders.', 3, 'The plagues included frogs, gnats, flies, and locusts — no spiders.'),
  ('Jesus'' Disciples', 'medium', 'NT', 'Jesus chose twelve disciples.', 'Several of Jesus'' disciples were fishermen.', 'The disciple Matthew betrayed Jesus for thirty pieces of silver.', 3, 'Judas Iscariot was the betrayer, not Matthew.'),
  ('The Exodus', 'medium', 'OT', 'The Israelites ate manna in the wilderness.', 'God led them with a pillar of cloud by day and fire by night.', 'The Israelites wandered in the wilderness for twelve years.', 3, 'They wandered for forty years.'),
  ('The Fall of Jericho', 'medium', 'OT', 'The Israelites marched around Jericho once a day for six days.', 'On the seventh day they marched around it seven times.', 'They knocked the walls down with a giant battering ram.', 3, 'The walls fell after the people shouted and blew trumpets.'),
  ('Ruth', 'medium', 'OT', 'Ruth was a Moabite who stayed loyal to her mother-in-law Naomi.', 'Ruth gleaned grain in the fields of Boaz.', 'Ruth was the mother of King Saul.', 3, 'Ruth was the great-grandmother of King David.'),
  ('Cain & Abel', 'medium', 'OT', 'Cain and Abel were the first sons of Adam and Eve.', 'Cain became jealous and killed his brother Abel.', 'Abel was a farmer and Cain was a shepherd.', 3, 'It''s reversed: Abel kept flocks and Cain worked the soil.'),
  ('Joseph''s Dreams', 'medium', 'OT', 'Joseph dreamed the sun, moon, and eleven stars bowed down to him.', 'Joseph''s brothers threw him into a pit.', 'Joseph stayed a shepherd boy in Canaan and never left home.', 3, 'He was sold into Egypt and rose to second-in-command.'),
  ('Baptism of Jesus', 'medium', 'NT', 'John baptized Jesus in the Jordan River.', 'The Holy Spirit descended on Jesus like a dove.', 'Right after his baptism, Jesus immediately turned water into wine.', 3, 'After his baptism Jesus went into the wilderness to be tempted.'),
  ('Temptation of Jesus', 'medium', 'NT', 'Jesus fasted forty days in the wilderness.', 'Satan tempted Jesus three times.', 'Jesus turned stones into bread when he grew hungry.', 3, 'Jesus refused to turn stones into bread.'),
  ('Lazarus', 'medium', 'NT', 'Jesus wept before raising Lazarus.', 'Lazarus had been in the tomb four days.', 'Lazarus was raised by the apostle Peter, not Jesus.', 3, 'Jesus himself called Lazarus out of the tomb.'),
  ('Sermon on the Mount', 'medium', 'NT', 'Jesus taught the Beatitudes (''Blessed are...'').', 'Jesus taught the Lord''s Prayer.', 'Jesus preached this whole sermon from inside the temple in Jerusalem.', 3, 'He preached it on a mountainside, which is why it''s the Sermon on the Mount.'),
  ('Zacchaeus', 'medium', 'NT', 'Zacchaeus was a wealthy tax collector.', 'Zacchaeus climbed a sycamore tree to see Jesus.', 'Zacchaeus refused to give any of his money back.', 3, 'He gave half to the poor and repaid those he cheated four times over.'),
  ('The Prodigal Son', 'medium', 'NT', 'The younger son demanded his inheritance early.', 'He wasted it and ended up feeding pigs.', 'When he returned home, his father turned him away.', 3, 'His father ran to him and threw a celebration feast.'),
  ('Feeding the 5,000', 'medium', 'NT', 'A boy''s five loaves and two fish were used in the miracle.', 'Twelve baskets of leftovers were gathered afterward.', 'Only the women and children were counted in the 5,000.', 3, 'It was 5,000 men, besides women and children.'),
  ('Nicodemus', 'medium', 'NT', 'Nicodemus was a Pharisee who came to Jesus at night.', 'Jesus told him he must be ''born again.''', 'Nicodemus was one of the twelve disciples.', 3, 'Nicodemus was a Pharisee and ruler of the Jews, not one of the Twelve.'),
  ('Gideon', 'medium', 'OT', 'Gideon tested God with a wool fleece.', 'Gideon''s army was reduced to just 300 men.', 'Gideon''s men attacked at noon with swords and shields.', 3, 'They attacked at night with trumpets, torches, and clay jars.'),
  ('Job', 'medium', 'OT', 'Job lost his children, wealth, and health.', 'Job''s friends came to comfort him but ended up accusing him.', 'In the end God restored Job with half of what he had before.', 3, 'God restored Job with double what he had before.'),
  ('Mary & Martha', 'medium', 'NT', 'Martha was busy serving while Mary sat at Jesus'' feet.', 'Jesus said Mary had chosen what is better.', 'Jesus scolded Mary for being lazy and sent her to help in the kitchen.', 3, 'Jesus defended Mary''s choice to listen to him.'),
  ('The Sower', 'medium', 'NT', 'Some seed fell on the path and the birds ate it.', 'Some seed fell on good soil and produced a crop.', 'Jesus said the seed represents money.', 3, 'The seed represents the word of God.'),
  ('The Last Supper', 'medium', 'NT', 'Jesus shared bread and wine with his disciples.', 'Jesus washed the disciples'' feet.', 'Jesus announced that Peter would betray him for silver.', 3, 'Judas was the betrayer; Peter would deny knowing Jesus.'),
  ('The Crucifixion', 'medium', 'NT', 'Jesus was crucified between two criminals.', 'Darkness covered the land for three hours.', 'Jesus was crucified at a place called Bethlehem.', 3, 'He was crucified at Golgotha, ''the place of the skull.'''),
  ('Doubting Thomas', 'medium', 'NT', 'Thomas doubted that Jesus had risen.', 'Thomas wanted to see the nail marks in Jesus'' hands.', 'Jesus refused to appear to Thomas because of his doubt.', 3, 'Jesus appeared and invited Thomas to touch his wounds.'),
  ('Saul''s Conversion', 'medium', 'NT', 'Before his conversion, Saul persecuted Christians.', 'He heard Jesus ask, ''Why do you persecute me?''', 'After conversion, Saul''s name was changed to Peter.', 3, 'His name became Paul.'),
  ('The Fiery Furnace', 'medium', 'OT', 'Shadrach, Meshach, and Abednego refused to bow to the golden statue.', 'They were thrown into a blazing furnace.', 'They were burned to ashes the instant they went in.', 3, 'They walked out unharmed, joined by a mysterious fourth figure.'),
  ('The Golden Calf', 'medium', 'OT', 'The Israelites made a golden calf to worship.', 'Moses broke the stone tablets in anger.', 'God rewarded the people with extra manna for making the calf.', 3, 'It was a grave sin that brought judgment, not reward.'),
  ('The Wise Men', 'medium', 'NT', 'The wise men followed a star from the east.', 'They brought gold, frankincense, and myrrh.', 'They visited Jesus in the stable on the night he was born.', 3, 'They came later and found the child in a house, not the stable.'),
  ('The Woman at the Well', 'medium', 'NT', 'Jesus spoke with a Samaritan woman at a well.', 'Jesus offered her ''living water.''', 'Jesus asked the woman to build him a boat.', 3, 'Jesus asked her for a drink of water.'),
  ('The Rich Young Ruler', 'medium', 'NT', 'A rich young man asked Jesus how to gain eternal life.', 'Jesus told him to sell his possessions and give to the poor.', 'The young man joyfully sold everything and followed Jesus.', 3, 'He went away sad because he had great wealth.'),
  ('Mary Magdalene', 'medium', 'NT', 'Mary Magdalene came to the tomb on Easter morning.', 'She was one of the first to see the risen Jesus.', 'Mary Magdalene was Jesus'' mother.', 3, 'Jesus'' mother was Mary of Nazareth, a different Mary.'),
  ('The Ten Lepers', 'medium', 'NT', 'Jesus healed ten men who had leprosy.', 'Only one of them returned to thank Jesus.', 'The one who came back to give thanks was a Pharisee.', 3, 'The thankful one was a Samaritan.'),
  ('The Paralyzed Man', 'medium', 'NT', 'Friends lowered a paralyzed man through a roof to reach Jesus.', 'Jesus forgave the man''s sins and healed him.', 'Jesus told the man to stay lying on his mat forever.', 3, 'Jesus told him to take up his mat and walk.'),
  ('Jacob & Esau', 'medium', 'OT', 'Esau sold his birthright for a bowl of stew.', 'Jacob tricked his father Isaac to steal the blessing.', 'Jacob was the older of the twin brothers.', 3, 'Esau was born first; Jacob was the younger twin.'),
  ('Isaac', 'medium', 'OT', 'Isaac was the son God promised to Abraham and Sarah.', 'Isaac married Rebekah.', 'Isaac''s only son was named Ishmael.', 3, 'Isaac had twin sons, Jacob and Esau; Ishmael was Abraham''s son.'),
  ('Aaron', 'medium', 'OT', 'Aaron was the first high priest of Israel.', 'Aaron made a golden calf while Moses was on the mountain.', 'Aaron was Moses'' cousin.', 3, 'Aaron was Moses'' older brother.'),
  ('Methuselah', 'hard', 'OT', 'Methuselah lived 969 years, longer than anyone else in the Bible.', 'Enoch was taken by God and did not see death.', 'Adam lived to be exactly 1,000 years old.', 3, 'Adam lived 930 years.'),
  ('Kings of Israel', 'hard', 'OT', 'Saul was the first king of Israel.', 'After Solomon died, the kingdom split into Israel and Judah.', 'David was Israel''s very first king.', 3, 'Saul was the first king; David was the second.'),
  ('The Prophets', 'hard', 'OT', 'Isaiah prophesied about a coming Messiah.', 'Jeremiah is known as the ''weeping prophet.''', 'Ezekiel was swallowed by a great fish.', 3, 'It was Jonah who was swallowed by the fish.'),
  ('The Ark of the Covenant', 'hard', 'OT', 'The ark held the stone tablets of the commandments.', 'It also contained Aaron''s rod that budded and a jar of manna.', 'The ark was carried on the backs of horses.', 3, 'It was carried by Levites using poles on their shoulders.'),
  ('The Twelve Tribes', 'hard', 'OT', 'The twelve tribes came from the sons of Jacob.', 'Jacob''s name was changed to Israel.', 'The tribe of Judah descended from Joseph.', 3, 'The tribe of Judah descended from Judah, another son of Jacob.'),
  ('Pentecost', 'hard', 'NT', 'The Holy Spirit came at Pentecost with a sound like rushing wind.', 'What looked like tongues of fire rested on the believers.', 'Peter''s sermon that day added about 30 people to the church.', 3, 'About 3,000 people were added that day.'),
  ('Stephen', 'hard', 'NT', 'Stephen was the first Christian martyr.', 'Stephen was stoned to death.', 'Stephen was beheaded by King Herod.', 3, 'Stephen was stoned; he was not beheaded.'),
  ('Philip & the Ethiopian', 'hard', 'NT', 'Philip explained the Scriptures to an Ethiopian official.', 'Philip baptized the Ethiopian.', 'Philip was then swallowed by a whale.', 3, 'The Spirit carried Philip away to another town — no whale.'),
  ('Deborah', 'hard', 'OT', 'Deborah was a prophetess and a judge of Israel.', 'Deborah led Israel to victory alongside the commander Barak.', 'Deborah killed the giant Goliath with a tent peg.', 3, 'It was Jael who killed the enemy commander Sisera with a tent peg.'),
  ('Joshua', 'hard', 'OT', 'Joshua took over as leader of Israel after Moses.', 'God made the sun stand still during one of Joshua''s battles.', 'Joshua parted the Red Sea to escape from Egypt.', 3, 'Moses parted the Red Sea; Joshua later crossed the Jordan River.'),
  ('The Talents', 'hard', 'NT', 'Three servants were entrusted with talents to invest.', 'The servant who buried his talent was rebuked.', 'Each servant was given exactly the same amount.', 3, 'They received five, two, and one talent — different amounts.'),
  ('The Transfiguration', 'hard', 'NT', 'Jesus'' face and clothes shone with dazzling light on the mountain.', 'A voice from the cloud said, ''This is my Son; listen to him.''', 'Abraham and David appeared and spoke with Jesus.', 3, 'Moses and Elijah appeared with Jesus, not Abraham and David.'),
  ('The Garden of Gethsemane', 'hard', 'NT', 'Jesus prayed so intensely his sweat was like drops of blood.', 'The disciples kept falling asleep while Jesus prayed.', 'Judas identified Jesus to the soldiers with a handshake.', 3, 'Judas identified Jesus with a kiss.'),
  ('The Road to Emmaus', 'hard', 'NT', 'Two followers walked to Emmaus after the resurrection.', 'Jesus walked with them but they didn''t recognize him at first.', 'They finally recognized him when he healed a blind beggar.', 3, 'They recognized him when he broke the bread.'),
  ('The Ascension', 'hard', 'NT', 'Jesus was taken up into heaven in a cloud.', 'Angels said he would return the same way he left.', 'Jesus ascended while walking on water on the Sea of Galilee.', 3, 'He ascended from the Mount of Olives near Bethany.'),
  ('Belshazzar''s Feast', 'hard', 'OT', 'A mysterious hand wrote words on the wall during a royal feast.', 'Daniel was called in to interpret the writing.', 'The words were written in flaming letters that never faded.', 3, 'A hand wrote on the plaster wall; there''s no mention of flames.'),
  ('Nebuchadnezzar', 'hard', 'OT', 'Nebuchadnezzar had a dream of a great statue made of different metals.', 'He was humbled and lived like a wild animal, eating grass.', 'Nebuchadnezzar was the king of Egypt.', 3, 'He was the king of Babylon.'),
  ('Rebekah', 'hard', 'OT', 'Rebekah drew water for Abraham''s servant and his camels.', 'Rebekah became the wife of Isaac.', 'Rebekah was the mother of Joseph.', 3, 'Rebekah was the mother of the twins Jacob and Esau.'),
  ('Jacob''s Ladder', 'hard', 'OT', 'Jacob dreamed of a ladder or stairway reaching up to heaven.', 'Angels were going up and down on it.', 'Jacob had this dream while living in Pharaoh''s palace.', 3, 'He dreamed it in the wilderness, using a stone as a pillow, while fleeing Esau.'),
  ('Miriam', 'hard', 'OT', 'Miriam was the sister of Moses and Aaron.', 'Miriam led the women in song after crossing the Red Sea.', 'Miriam was swallowed by the earth for rebelling against Moses.', 3, 'That was Korah; Miriam was struck with temporary leprosy.'),
  ('Balaam', 'hard', 'OT', 'Balaam''s donkey spoke to him with a human voice.', 'An angel with a drawn sword blocked Balaam''s path.', 'Balaam was a humble fisherman from Galilee.', 3, 'Balaam was a diviner hired to curse Israel.'),
  ('Nehemiah', 'hard', 'OT', 'Nehemiah led the effort to rebuild the walls of Jerusalem.', 'The workers built with a tool in one hand and a weapon in the other.', 'It took Nehemiah forty years to finish the walls.', 3, 'The walls were finished in just 52 days.'),
  ('Ezra', 'hard', 'OT', 'Ezra was a scribe who taught the people God''s law.', 'Ezra read the law aloud to the assembled people.', 'Ezra wrote the Gospel of John.', 3, 'Ezra lived centuries before the Gospels; he didn''t write them.'),
  ('Simeon & Anna', 'hard', 'NT', 'Simeon held the baby Jesus in the temple and praised God.', 'Anna was an elderly prophetess who gave thanks for the child.', 'Simeon was the innkeeper who had no room for Mary and Joseph.', 3, 'Simeon was a devout man in the temple, not an innkeeper.'),
  ('Blind Bartimaeus', 'hard', 'NT', 'Bartimaeus was a blind beggar sitting by the road.', 'He cried out, ''Jesus, Son of David, have mercy on me!''', 'Jesus healed him by covering his eyes with gold coins.', 3, 'Jesus healed him and said his faith had made him well.'),
  ('Jairus'' Daughter', 'hard', 'NT', 'Jairus begged Jesus to come heal his dying daughter.', 'Jesus said the girl was only sleeping.', 'Jesus arrived too late and could not help the girl.', 3, 'Jesus raised her, saying, ''Little girl, get up.'''),
  ('Elisha', 'hard', 'OT', 'Elisha received a double portion of Elijah''s spirit.', 'Elisha made a lost axe head float to the surface of the water.', 'Elisha was eaten by lions for mocking a group of children.', 3, 'It was youths who mocked Elisha, and bears (not lions) that came out.')
on conflict (topic) do nothing;
