-- v9 migration — add Bible reference + one-line context to Guess the Fake.
-- Additive and idempotent. Run this after v8 (safe to re-run).
--
-- 'context' is scene-setting only — it never reveals which statement is fake.

alter table gtf_questions add column if not exists reference text;
alter table gtf_questions add column if not exists context text;

update gtf_questions g set reference = v.reference, context = v.context
from (values
  ('Noah', 'Genesis 6-9', 'God sends a flood but rescues one faithful family.'),
  ('Creation', 'Genesis 1', 'God forms the world and everything in it, step by step.'),
  ('David & Goliath', '1 Samuel 17', 'A shepherd boy steps onto the battlefield against a giant.'),
  ('Jonah', 'Jonah 1-4', 'God calls a prophet to carry a message to the city of Nineveh.'),
  ('Jesus'' Birth', 'Luke 2; Matthew 2', 'The night Jesus is born and those who come to see him.'),
  ('Adam & Eve', 'Genesis 2-3', 'The first people and their choice in the Garden of Eden.'),
  ('Daniel', 'Daniel 1; 6', 'A faithful young man stays true to God in a foreign royal court.'),
  ('Ten Commandments', 'Exodus 20', 'God gives his people the laws they are to live by.'),
  ('Jesus'' Miracles', 'John 2; Matthew 14', 'A look at some of the signs and wonders Jesus performed.'),
  ('The Resurrection', 'Matthew 28; John 20', 'Easter morning, when the tomb is found empty.'),
  ('Samson', 'Judges 13-16', 'A judge of Israel set apart with extraordinary strength.'),
  ('Joseph', 'Genesis 37-45', 'Jacob''s favored son, betrayed by his brothers, rises in Egypt.'),
  ('Moses', 'Exodus 2-3; Deuteronomy 34', 'The leader God chose to free Israel from Egypt.'),
  ('Palm Sunday', 'Matthew 21', 'Jesus arrives in Jerusalem to the cheers of the crowds.'),
  ('The Good Samaritan', 'Luke 10', 'A parable about a traveler left hurt on a dangerous road.'),
  ('Wise & Foolish Builders', 'Matthew 7', 'A short parable about two builders and where they build.'),
  ('The Lost Sheep', 'Luke 15', 'A parable about a shepherd missing one of his flock.'),
  ('Peter', 'Matthew 14; 26', 'One of Jesus'' twelve disciples and their frequent spokesman.'),
  ('John the Baptist', 'Matthew 3; Luke 1', 'The prophet who prepared the way for Jesus.'),
  ('Abraham', 'Genesis 15-22', 'God''s promise to make a great nation from one man.'),
  ('Paul', 'Acts 9', 'A leading apostle who carried the gospel across the world.'),
  ('Tower of Babel', 'Genesis 11', 'People unite to build a tower reaching to the heavens.'),
  ('Queen Esther', 'Esther 4-7', 'A queen faces a deadly plot against her people.'),
  ('Solomon', '1 Kings 3-6', 'One of Israel''s greatest kings, the son of David.'),
  ('The Plagues of Egypt', 'Exodus 7-12', 'God sends a series of plagues to free his people.'),
  ('Jesus'' Disciples', 'Matthew 10; 26', 'The twelve men Jesus chose to follow him closely.'),
  ('The Exodus', 'Exodus 16; Numbers 14', 'Israel''s long journey through the wilderness.'),
  ('The Fall of Jericho', 'Joshua 6', 'Israel''s first battle in the Promised Land.'),
  ('Ruth', 'Ruth 1-4', 'A loyal widow''s story from the days of the judges.'),
  ('Cain & Abel', 'Genesis 4', 'The first two brothers and their offerings to God.'),
  ('Joseph''s Dreams', 'Genesis 37', 'The dreams of a young man that stir his brothers'' anger.'),
  ('Baptism of Jesus', 'Matthew 3; Mark 1', 'The day Jesus is baptized as his ministry begins.'),
  ('Temptation of Jesus', 'Matthew 4; Luke 4', 'Jesus is tested in the wilderness.'),
  ('Lazarus', 'John 11', 'Two sisters grieve their brother and send for Jesus.'),
  ('Sermon on the Mount', 'Matthew 5-7', 'Jesus'' most famous block of teaching to his followers.'),
  ('Zacchaeus', 'Luke 19', 'A tax collector climbs to catch a glimpse of Jesus.'),
  ('The Prodigal Son', 'Luke 15', 'A parable about a son who leaves home with his inheritance.'),
  ('Feeding the 5,000', 'Matthew 14; John 6', 'Jesus feeds a huge crowd from a small lunch.'),
  ('Nicodemus', 'John 3', 'A man comes to Jesus at night with deep questions.'),
  ('Gideon', 'Judges 6-7', 'God calls an unlikely hero to rescue Israel.'),
  ('Job', 'Job 1-2; 42', 'A blameless man loses everything and is tested.'),
  ('Mary & Martha', 'Luke 10', 'Jesus visits the home of two sisters.'),
  ('The Sower', 'Matthew 13', 'A parable about a farmer scattering seed on different ground.'),
  ('The Last Supper', 'Matthew 26; John 13', 'Jesus shares a final meal with his disciples.'),
  ('The Crucifixion', 'Matthew 27; John 19', 'The hours of Jesus'' death on the cross.'),
  ('Doubting Thomas', 'John 20', 'One disciple struggles to believe the others'' news.'),
  ('Saul''s Conversion', 'Acts 9', 'A fierce enemy of the church meets Jesus on the road.'),
  ('The Fiery Furnace', 'Daniel 3', 'Three friends refuse to bow to a king''s golden statue.'),
  ('The Golden Calf', 'Exodus 32', 'While Moses is on the mountain, the people grow restless.'),
  ('The Wise Men', 'Matthew 2', 'Visitors from the east follow a star to find Jesus.'),
  ('The Woman at the Well', 'John 4', 'Jesus stops to talk with a woman drawing water.'),
  ('The Rich Young Ruler', 'Mark 10', 'A wealthy man asks Jesus about eternal life.'),
  ('Mary Magdalene', 'John 20', 'One of the women closest to Jesus during his ministry.'),
  ('The Ten Lepers', 'Luke 17', 'Ten sick men cry out to Jesus for healing.'),
  ('The Paralyzed Man', 'Mark 2', 'Friends go to great lengths to bring a man to Jesus.'),
  ('Jacob & Esau', 'Genesis 25; 27', 'Twin brothers struggle over blessing and birthright.'),
  ('Isaac', 'Genesis 21-24', 'The long-promised son of Abraham and Sarah.'),
  ('Aaron', 'Exodus 4; 32', 'Moses'' right-hand man during the exodus.'),
  ('Methuselah', 'Genesis 5', 'The long genealogy from Adam through the early generations.'),
  ('Kings of Israel', '1 Samuel 8-10', 'How Israel first came to have kings.'),
  ('The Prophets', 'Old Testament prophets', 'A quick tour of several Old Testament prophets.'),
  ('The Ark of the Covenant', 'Exodus 25; Numbers 4', 'The sacred golden chest at the center of Israel''s worship.'),
  ('The Twelve Tribes', 'Genesis 49', 'The sons of Jacob who became the tribes of Israel.'),
  ('Pentecost', 'Acts 2', 'The Holy Spirit comes on the believers in Jerusalem.'),
  ('Stephen', 'Acts 6-7', 'The first follower of Jesus to die for his faith.'),
  ('Philip & the Ethiopian', 'Acts 8', 'Philip meets a foreign official reading Scripture on a road.'),
  ('Deborah', 'Judges 4-5', 'A prophetess leads Israel in a time of danger.'),
  ('Joshua', 'Joshua 3; 10', 'Moses'' successor leads Israel into the Promised Land.'),
  ('The Talents', 'Matthew 25', 'A parable about servants entrusted with their master''s money.'),
  ('The Transfiguration', 'Matthew 17', 'Jesus is revealed in glory on a mountaintop.'),
  ('The Garden of Gethsemane', 'Matthew 26', 'Jesus prays in a garden on the night he is arrested.'),
  ('The Road to Emmaus', 'Luke 24', 'Two followers meet a stranger on the road after Easter.'),
  ('The Ascension', 'Acts 1', 'Jesus'' final moments with his disciples before heaven.'),
  ('Belshazzar''s Feast', 'Daniel 5', 'A king''s banquet is interrupted by a strange sign.'),
  ('Nebuchadnezzar', 'Daniel 2; 4', 'A powerful king has troubling dreams and is humbled.'),
  ('Rebekah', 'Genesis 24-25', 'The wife chosen for Isaac at a well.'),
  ('Jacob''s Ladder', 'Genesis 28', 'Jacob falls asleep and dreams of heaven.'),
  ('Miriam', 'Exodus 15; Numbers 12', 'The sister of Moses and a leader among Israel''s women.'),
  ('Balaam', 'Numbers 22', 'On his journey, this man encounters far more than he expected.'),
  ('Nehemiah', 'Nehemiah 2-6', 'Rebuilding the broken-down walls of Jerusalem.'),
  ('Ezra', 'Ezra 7; Nehemiah 8', 'A scribe helps God''s people return to his law.'),
  ('Simeon & Anna', 'Luke 2', 'Two devout elders who had long awaited the Messiah.'),
  ('Blind Bartimaeus', 'Mark 10', 'A blind beggar calls out to Jesus by the roadside.'),
  ('Jairus'' Daughter', 'Mark 5', 'A desperate father begs Jesus to help his sick child.'),
  ('Elisha', '2 Kings 2-6', 'The prophet who took up Elijah''s mantle.')
) as v(topic, reference, context)
where g.topic = v.topic;
