// Guess the Fake — Bible "two truths and a lie" content.
// This is the OFFLINE FALLBACK. When the `gtf_questions` Supabase table has
// rows, the game loads from there instead (run supabase/v8_guess_the_fake.sql).
// Statement order is shuffled at play time, so the fake is never in a fixed spot.
export type Difficulty = "easy" | "medium" | "hard";
export type FakeStatement = { text: string; fake: boolean };
export type FakeRound = {
  topic: string;
  difficulty: Difficulty;
  testament: "OT" | "NT" | null;
  statements: FakeStatement[];
  explanation: string;
};

export const GUESS_THE_FAKE_ROUNDS: FakeRound[] = [
  {
    topic: "Noah",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "Noah brought his three sons — Shem, Ham, and Japheth — onto the ark.", fake: false },
      { text: "God set a rainbow in the sky as the sign of his promise after the flood.", fake: false },
      { text: "The flood rain lasted exactly 100 days and 100 nights.", fake: true },
    ],
    explanation: "It rained 40 days and 40 nights, not 100.",
  },
  {
    topic: "Creation",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "God created light on the first day.", fake: false },
      { text: "God rested on the seventh day.", fake: false },
      { text: "God created the sun, moon, and stars on the second day.", fake: true },
    ],
    explanation: "The sun, moon, and stars were made on the fourth day.",
  },
  {
    topic: "David & Goliath",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "David defeated the giant Goliath with a sling and a stone.", fake: false },
      { text: "David played the harp to calm King Saul.", fake: false },
      { text: "David built the temple in Jerusalem.", fake: true },
    ],
    explanation: "His son Solomon built the temple, not David.",
  },
  {
    topic: "Jonah",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "Jonah was swallowed by a great fish and stayed inside three days and nights.", fake: false },
      { text: "God told Jonah to preach to the city of Nineveh.", fake: false },
      { text: "Jonah gladly obeyed God and sailed straight to Nineveh.", fake: true },
    ],
    explanation: "Jonah ran the opposite way, sailing toward Tarshish.",
  },
  {
    topic: "Jesus' Birth",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "Jesus was born in Bethlehem.", fake: false },
      { text: "An angel announced the good news to shepherds in the fields.", fake: false },
      { text: "The Bible says exactly three wise men visited Jesus.", fake: true },
    ],
    explanation: "The number of wise men is never given — only three gifts are named.",
  },
  {
    topic: "Adam & Eve",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "God placed Adam and Eve in the Garden of Eden.", fake: false },
      { text: "A serpent tempted Eve to eat the forbidden fruit.", fake: false },
      { text: "The Bible clearly says the forbidden fruit was an apple.", fake: true },
    ],
    explanation: "The fruit is never identified as an apple.",
  },
  {
    topic: "Daniel",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "Daniel was thrown into a den of lions and was unharmed.", fake: false },
      { text: "Daniel chose to eat vegetables and water instead of the king's rich food.", fake: false },
      { text: "Daniel interpreted dreams for Pharaoh in Egypt.", fake: true },
    ],
    explanation: "That was Joseph. Daniel served kings of Babylon and Persia.",
  },
  {
    topic: "Ten Commandments",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "God gave Moses the commandments on Mount Sinai.", fake: false },
      { text: "The commandments were written on tablets of stone.", fake: false },
      { text: "There were twelve commandments, one for each tribe of Israel.", fake: true },
    ],
    explanation: "There were ten commandments.",
  },
  {
    topic: "Jesus' Miracles",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "Jesus fed over 5,000 people with five loaves and two fish.", fake: false },
      { text: "Jesus turned water into wine at a wedding in Cana.", fake: false },
      { text: "Jesus' very first miracle was healing a blind man.", fake: true },
    ],
    explanation: "His first miracle was turning water into wine at Cana.",
  },
  {
    topic: "The Resurrection",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "Jesus rose from the dead on the third day.", fake: false },
      { text: "An angel rolled the stone away from the tomb.", fake: false },
      { text: "After rising, Jesus first appeared to Pontius Pilate.", fake: true },
    ],
    explanation: "He first appeared to Mary Magdalene and the women, not Pilate.",
  },
  {
    topic: "Samson",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "Samson's great strength was connected to his uncut hair.", fake: false },
      { text: "Delilah discovered the secret of Samson's strength.", fake: false },
      { text: "Samson defeated an army using the jawbone of a lion.", fake: true },
    ],
    explanation: "He used the jawbone of a donkey.",
  },
  {
    topic: "Joseph",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "Joseph's brothers sold him into slavery in Egypt.", fake: false },
      { text: "Joseph interpreted Pharaoh's dreams about seven years of plenty and famine.", fake: false },
      { text: "Joseph's father gave him a coat made of solid gold.", fake: true },
    ],
    explanation: "It was a coat of many colors (a richly ornamented robe).",
  },
  {
    topic: "Moses",
    difficulty: "easy",
    testament: "OT",
    statements: [
      { text: "As a baby, Moses was placed in a basket on the Nile and found by Pharaoh's daughter.", fake: false },
      { text: "Moses saw a bush that was burning but was not burned up.", fake: false },
      { text: "Moses himself led the people across the Jordan into the Promised Land.", fake: true },
    ],
    explanation: "Moses died first; Joshua led them across the Jordan.",
  },
  {
    topic: "Palm Sunday",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "Jesus rode into Jerusalem on a donkey.", fake: false },
      { text: "Crowds spread palm branches and cloaks on the road.", fake: false },
      { text: "Jesus rode in on a white horse leading an army.", fake: true },
    ],
    explanation: "He came humbly on a donkey, not a war horse.",
  },
  {
    topic: "The Good Samaritan",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "A man was beaten by robbers and left on the road.", fake: false },
      { text: "A Samaritan stopped to help him after others passed by.", fake: false },
      { text: "Jesus told this story to explain the best way to catch fish.", fake: true },
    ],
    explanation: "The parable answers the question 'Who is my neighbor?'",
  },
  {
    topic: "Wise & Foolish Builders",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "The wise man built his house on the rock.", fake: false },
      { text: "The foolish man built his house on the sand.", fake: false },
      { text: "Both houses stood firm through the storm.", fake: true },
    ],
    explanation: "The house on sand collapsed when the storm came.",
  },
  {
    topic: "The Lost Sheep",
    difficulty: "easy",
    testament: "NT",
    statements: [
      { text: "The shepherd left the ninety-nine to search for one lost sheep.", fake: false },
      { text: "He rejoiced and carried it home when he found it.", fake: false },
      { text: "The shepherd gave up and never found the lost sheep.", fake: true },
    ],
    explanation: "He searched until he found it, then celebrated.",
  },
  {
    topic: "Peter",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Peter denied knowing Jesus three times before the rooster crowed.", fake: false },
      { text: "Peter walked on water toward Jesus before he began to sink.", fake: false },
      { text: "Peter was the short tax collector Jesus called down from a sycamore tree.", fake: true },
    ],
    explanation: "That was Zacchaeus, not Peter.",
  },
  {
    topic: "John the Baptist",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "John baptized people in the Jordan River.", fake: false },
      { text: "John ate locusts and wild honey.", fake: false },
      { text: "John the Baptist was Jesus' twin brother.", fake: true },
    ],
    explanation: "John was a relative of Jesus, not his twin.",
  },
  {
    topic: "Abraham",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "God promised Abraham descendants as numerous as the stars.", fake: false },
      { text: "Abraham was willing to sacrifice his son Isaac before God stopped him.", fake: false },
      { text: "Sarah gave birth to Isaac while she was in her twenties.", fake: true },
    ],
    explanation: "Sarah was about 90 when Isaac was born.",
  },
  {
    topic: "Paul",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Paul was blinded by a bright light on the road to Damascus.", fake: false },
      { text: "Paul wrote many of the letters found in the New Testament.", fake: false },
      { text: "Paul was one of Jesus' original twelve disciples.", fake: true },
    ],
    explanation: "Paul (formerly Saul) was not one of the Twelve; he came later.",
  },
  {
    topic: "Tower of Babel",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "The people built a tall tower to try to reach the heavens.", fake: false },
      { text: "God confused their language so they couldn't understand each other.", fake: false },
      { text: "God destroyed the tower with fire and lightning.", fake: true },
    ],
    explanation: "God scattered the people by confusing their language; no fire.",
  },
  {
    topic: "Queen Esther",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Esther became queen of Persia.", fake: false },
      { text: "Esther risked her life to save her people, the Jews.", fake: false },
      { text: "Esther led the Israelite army into battle against Egypt.", fake: true },
    ],
    explanation: "Esther saved her people through courage before the king, not battle.",
  },
  {
    topic: "Solomon",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Solomon asked God for wisdom.", fake: false },
      { text: "Solomon built the first temple in Jerusalem.", fake: false },
      { text: "Solomon defeated Goliath as a young shepherd.", fake: true },
    ],
    explanation: "That was his father David.",
  },
  {
    topic: "The Plagues of Egypt",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "One plague turned the Nile River to blood.", fake: false },
      { text: "The final plague was the death of the firstborn.", fake: false },
      { text: "One of the plagues was a swarm of giant spiders.", fake: true },
    ],
    explanation: "The plagues included frogs, gnats, flies, and locusts — no spiders.",
  },
  {
    topic: "Jesus' Disciples",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus chose twelve disciples.", fake: false },
      { text: "Several of Jesus' disciples were fishermen.", fake: false },
      { text: "The disciple Matthew betrayed Jesus for thirty pieces of silver.", fake: true },
    ],
    explanation: "Judas Iscariot was the betrayer, not Matthew.",
  },
  {
    topic: "The Exodus",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "The Israelites ate manna in the wilderness.", fake: false },
      { text: "God led them with a pillar of cloud by day and fire by night.", fake: false },
      { text: "The Israelites wandered in the wilderness for twelve years.", fake: true },
    ],
    explanation: "They wandered for forty years.",
  },
  {
    topic: "The Fall of Jericho",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "The Israelites marched around Jericho once a day for six days.", fake: false },
      { text: "On the seventh day they marched around it seven times.", fake: false },
      { text: "They knocked the walls down with a giant battering ram.", fake: true },
    ],
    explanation: "The walls fell after the people shouted and blew trumpets.",
  },
  {
    topic: "Ruth",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Ruth was a Moabite who stayed loyal to her mother-in-law Naomi.", fake: false },
      { text: "Ruth gleaned grain in the fields of Boaz.", fake: false },
      { text: "Ruth was the mother of King Saul.", fake: true },
    ],
    explanation: "Ruth was the great-grandmother of King David.",
  },
  {
    topic: "Cain & Abel",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Cain and Abel were the first sons of Adam and Eve.", fake: false },
      { text: "Cain became jealous and killed his brother Abel.", fake: false },
      { text: "Abel was a farmer and Cain was a shepherd.", fake: true },
    ],
    explanation: "It's reversed: Abel kept flocks and Cain worked the soil.",
  },
  {
    topic: "Joseph's Dreams",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Joseph dreamed the sun, moon, and eleven stars bowed down to him.", fake: false },
      { text: "Joseph's brothers threw him into a pit.", fake: false },
      { text: "Joseph stayed a shepherd boy in Canaan and never left home.", fake: true },
    ],
    explanation: "He was sold into Egypt and rose to second-in-command.",
  },
  {
    topic: "Baptism of Jesus",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "John baptized Jesus in the Jordan River.", fake: false },
      { text: "The Holy Spirit descended on Jesus like a dove.", fake: false },
      { text: "Right after his baptism, Jesus immediately turned water into wine.", fake: true },
    ],
    explanation: "After his baptism Jesus went into the wilderness to be tempted.",
  },
  {
    topic: "Temptation of Jesus",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus fasted forty days in the wilderness.", fake: false },
      { text: "Satan tempted Jesus three times.", fake: false },
      { text: "Jesus turned stones into bread when he grew hungry.", fake: true },
    ],
    explanation: "Jesus refused to turn stones into bread.",
  },
  {
    topic: "Lazarus",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus wept before raising Lazarus.", fake: false },
      { text: "Lazarus had been in the tomb four days.", fake: false },
      { text: "Lazarus was raised by the apostle Peter, not Jesus.", fake: true },
    ],
    explanation: "Jesus himself called Lazarus out of the tomb.",
  },
  {
    topic: "Sermon on the Mount",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus taught the Beatitudes ('Blessed are...').", fake: false },
      { text: "Jesus taught the Lord's Prayer.", fake: false },
      { text: "Jesus preached this whole sermon from inside the temple in Jerusalem.", fake: true },
    ],
    explanation: "He preached it on a mountainside, which is why it's the Sermon on the Mount.",
  },
  {
    topic: "Zacchaeus",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Zacchaeus was a wealthy tax collector.", fake: false },
      { text: "Zacchaeus climbed a sycamore tree to see Jesus.", fake: false },
      { text: "Zacchaeus refused to give any of his money back.", fake: true },
    ],
    explanation: "He gave half to the poor and repaid those he cheated four times over.",
  },
  {
    topic: "The Prodigal Son",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "The younger son demanded his inheritance early.", fake: false },
      { text: "He wasted it and ended up feeding pigs.", fake: false },
      { text: "When he returned home, his father turned him away.", fake: true },
    ],
    explanation: "His father ran to him and threw a celebration feast.",
  },
  {
    topic: "Feeding the 5,000",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "A boy's five loaves and two fish were used in the miracle.", fake: false },
      { text: "Twelve baskets of leftovers were gathered afterward.", fake: false },
      { text: "Only the women and children were counted in the 5,000.", fake: true },
    ],
    explanation: "It was 5,000 men, besides women and children.",
  },
  {
    topic: "Nicodemus",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Nicodemus was a Pharisee who came to Jesus at night.", fake: false },
      { text: "Jesus told him he must be 'born again.'", fake: false },
      { text: "Nicodemus was one of the twelve disciples.", fake: true },
    ],
    explanation: "Nicodemus was a Pharisee and ruler of the Jews, not one of the Twelve.",
  },
  {
    topic: "Gideon",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Gideon tested God with a wool fleece.", fake: false },
      { text: "Gideon's army was reduced to just 300 men.", fake: false },
      { text: "Gideon's men attacked at noon with swords and shields.", fake: true },
    ],
    explanation: "They attacked at night with trumpets, torches, and clay jars.",
  },
  {
    topic: "Job",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Job lost his children, wealth, and health.", fake: false },
      { text: "Job's friends came to comfort him but ended up accusing him.", fake: false },
      { text: "In the end God restored Job with half of what he had before.", fake: true },
    ],
    explanation: "God restored Job with double what he had before.",
  },
  {
    topic: "Mary & Martha",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Martha was busy serving while Mary sat at Jesus' feet.", fake: false },
      { text: "Jesus said Mary had chosen what is better.", fake: false },
      { text: "Jesus scolded Mary for being lazy and sent her to help in the kitchen.", fake: true },
    ],
    explanation: "Jesus defended Mary's choice to listen to him.",
  },
  {
    topic: "The Sower",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Some seed fell on the path and the birds ate it.", fake: false },
      { text: "Some seed fell on good soil and produced a crop.", fake: false },
      { text: "Jesus said the seed represents money.", fake: true },
    ],
    explanation: "The seed represents the word of God.",
  },
  {
    topic: "The Last Supper",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus shared bread and wine with his disciples.", fake: false },
      { text: "Jesus washed the disciples' feet.", fake: false },
      { text: "Jesus announced that Peter would betray him for silver.", fake: true },
    ],
    explanation: "Judas was the betrayer; Peter would deny knowing Jesus.",
  },
  {
    topic: "The Crucifixion",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus was crucified between two criminals.", fake: false },
      { text: "Darkness covered the land for three hours.", fake: false },
      { text: "Jesus was crucified at a place called Bethlehem.", fake: true },
    ],
    explanation: "He was crucified at Golgotha, 'the place of the skull.'",
  },
  {
    topic: "Doubting Thomas",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Thomas doubted that Jesus had risen.", fake: false },
      { text: "Thomas wanted to see the nail marks in Jesus' hands.", fake: false },
      { text: "Jesus refused to appear to Thomas because of his doubt.", fake: true },
    ],
    explanation: "Jesus appeared and invited Thomas to touch his wounds.",
  },
  {
    topic: "Saul's Conversion",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Before his conversion, Saul persecuted Christians.", fake: false },
      { text: "He heard Jesus ask, 'Why do you persecute me?'", fake: false },
      { text: "After conversion, Saul's name was changed to Peter.", fake: true },
    ],
    explanation: "His name became Paul.",
  },
  {
    topic: "The Fiery Furnace",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Shadrach, Meshach, and Abednego refused to bow to the golden statue.", fake: false },
      { text: "They were thrown into a blazing furnace.", fake: false },
      { text: "They were burned to ashes the instant they went in.", fake: true },
    ],
    explanation: "They walked out unharmed, joined by a mysterious fourth figure.",
  },
  {
    topic: "The Golden Calf",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "The Israelites made a golden calf to worship.", fake: false },
      { text: "Moses broke the stone tablets in anger.", fake: false },
      { text: "God rewarded the people with extra manna for making the calf.", fake: true },
    ],
    explanation: "It was a grave sin that brought judgment, not reward.",
  },
  {
    topic: "The Wise Men",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "The wise men followed a star from the east.", fake: false },
      { text: "They brought gold, frankincense, and myrrh.", fake: false },
      { text: "They visited Jesus in the stable on the night he was born.", fake: true },
    ],
    explanation: "They came later and found the child in a house, not the stable.",
  },
  {
    topic: "The Woman at the Well",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus spoke with a Samaritan woman at a well.", fake: false },
      { text: "Jesus offered her 'living water.'", fake: false },
      { text: "Jesus asked the woman to build him a boat.", fake: true },
    ],
    explanation: "Jesus asked her for a drink of water.",
  },
  {
    topic: "The Rich Young Ruler",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "A rich young man asked Jesus how to gain eternal life.", fake: false },
      { text: "Jesus told him to sell his possessions and give to the poor.", fake: false },
      { text: "The young man joyfully sold everything and followed Jesus.", fake: true },
    ],
    explanation: "He went away sad because he had great wealth.",
  },
  {
    topic: "Mary Magdalene",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Mary Magdalene came to the tomb on Easter morning.", fake: false },
      { text: "She was one of the first to see the risen Jesus.", fake: false },
      { text: "Mary Magdalene was Jesus' mother.", fake: true },
    ],
    explanation: "Jesus' mother was Mary of Nazareth, a different Mary.",
  },
  {
    topic: "The Ten Lepers",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Jesus healed ten men who had leprosy.", fake: false },
      { text: "Only one of them returned to thank Jesus.", fake: false },
      { text: "The one who came back to give thanks was a Pharisee.", fake: true },
    ],
    explanation: "The thankful one was a Samaritan.",
  },
  {
    topic: "The Paralyzed Man",
    difficulty: "medium",
    testament: "NT",
    statements: [
      { text: "Friends lowered a paralyzed man through a roof to reach Jesus.", fake: false },
      { text: "Jesus forgave the man's sins and healed him.", fake: false },
      { text: "Jesus told the man to stay lying on his mat forever.", fake: true },
    ],
    explanation: "Jesus told him to take up his mat and walk.",
  },
  {
    topic: "Jacob & Esau",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Esau sold his birthright for a bowl of stew.", fake: false },
      { text: "Jacob tricked his father Isaac to steal the blessing.", fake: false },
      { text: "Jacob was the older of the twin brothers.", fake: true },
    ],
    explanation: "Esau was born first; Jacob was the younger twin.",
  },
  {
    topic: "Isaac",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Isaac was the son God promised to Abraham and Sarah.", fake: false },
      { text: "Isaac married Rebekah.", fake: false },
      { text: "Isaac's only son was named Ishmael.", fake: true },
    ],
    explanation: "Isaac had twin sons, Jacob and Esau; Ishmael was Abraham's son.",
  },
  {
    topic: "Aaron",
    difficulty: "medium",
    testament: "OT",
    statements: [
      { text: "Aaron was the first high priest of Israel.", fake: false },
      { text: "Aaron made a golden calf while Moses was on the mountain.", fake: false },
      { text: "Aaron was Moses' cousin.", fake: true },
    ],
    explanation: "Aaron was Moses' older brother.",
  },
  {
    topic: "Methuselah",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Methuselah lived 969 years, longer than anyone else in the Bible.", fake: false },
      { text: "Enoch was taken by God and did not see death.", fake: false },
      { text: "Adam lived to be exactly 1,000 years old.", fake: true },
    ],
    explanation: "Adam lived 930 years.",
  },
  {
    topic: "Kings of Israel",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Saul was the first king of Israel.", fake: false },
      { text: "After Solomon died, the kingdom split into Israel and Judah.", fake: false },
      { text: "David was Israel's very first king.", fake: true },
    ],
    explanation: "Saul was the first king; David was the second.",
  },
  {
    topic: "The Prophets",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Isaiah prophesied about a coming Messiah.", fake: false },
      { text: "Jeremiah is known as the 'weeping prophet.'", fake: false },
      { text: "Ezekiel was swallowed by a great fish.", fake: true },
    ],
    explanation: "It was Jonah who was swallowed by the fish.",
  },
  {
    topic: "The Ark of the Covenant",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "The ark held the stone tablets of the commandments.", fake: false },
      { text: "It also contained Aaron's rod that budded and a jar of manna.", fake: false },
      { text: "The ark was carried on the backs of horses.", fake: true },
    ],
    explanation: "It was carried by Levites using poles on their shoulders.",
  },
  {
    topic: "The Twelve Tribes",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "The twelve tribes came from the sons of Jacob.", fake: false },
      { text: "Jacob's name was changed to Israel.", fake: false },
      { text: "The tribe of Judah descended from Joseph.", fake: true },
    ],
    explanation: "The tribe of Judah descended from Judah, another son of Jacob.",
  },
  {
    topic: "Pentecost",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "The Holy Spirit came at Pentecost with a sound like rushing wind.", fake: false },
      { text: "What looked like tongues of fire rested on the believers.", fake: false },
      { text: "Peter's sermon that day added about 30 people to the church.", fake: true },
    ],
    explanation: "About 3,000 people were added that day.",
  },
  {
    topic: "Stephen",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Stephen was the first Christian martyr.", fake: false },
      { text: "Stephen was stoned to death.", fake: false },
      { text: "Stephen was beheaded by King Herod.", fake: true },
    ],
    explanation: "Stephen was stoned; he was not beheaded.",
  },
  {
    topic: "Philip & the Ethiopian",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Philip explained the Scriptures to an Ethiopian official.", fake: false },
      { text: "Philip baptized the Ethiopian.", fake: false },
      { text: "Philip was then swallowed by a whale.", fake: true },
    ],
    explanation: "The Spirit carried Philip away to another town — no whale.",
  },
  {
    topic: "Deborah",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Deborah was a prophetess and a judge of Israel.", fake: false },
      { text: "Deborah led Israel to victory alongside the commander Barak.", fake: false },
      { text: "Deborah killed the giant Goliath with a tent peg.", fake: true },
    ],
    explanation: "It was Jael who killed the enemy commander Sisera with a tent peg.",
  },
  {
    topic: "Joshua",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Joshua took over as leader of Israel after Moses.", fake: false },
      { text: "God made the sun stand still during one of Joshua's battles.", fake: false },
      { text: "Joshua parted the Red Sea to escape from Egypt.", fake: true },
    ],
    explanation: "Moses parted the Red Sea; Joshua later crossed the Jordan River.",
  },
  {
    topic: "The Talents",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Three servants were entrusted with talents to invest.", fake: false },
      { text: "The servant who buried his talent was rebuked.", fake: false },
      { text: "Each servant was given exactly the same amount.", fake: true },
    ],
    explanation: "They received five, two, and one talent — different amounts.",
  },
  {
    topic: "The Transfiguration",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Jesus' face and clothes shone with dazzling light on the mountain.", fake: false },
      { text: "A voice from the cloud said, 'This is my Son; listen to him.'", fake: false },
      { text: "Abraham and David appeared and spoke with Jesus.", fake: true },
    ],
    explanation: "Moses and Elijah appeared with Jesus, not Abraham and David.",
  },
  {
    topic: "The Garden of Gethsemane",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Jesus prayed so intensely his sweat was like drops of blood.", fake: false },
      { text: "The disciples kept falling asleep while Jesus prayed.", fake: false },
      { text: "Judas identified Jesus to the soldiers with a handshake.", fake: true },
    ],
    explanation: "Judas identified Jesus with a kiss.",
  },
  {
    topic: "The Road to Emmaus",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Two followers walked to Emmaus after the resurrection.", fake: false },
      { text: "Jesus walked with them but they didn't recognize him at first.", fake: false },
      { text: "They finally recognized him when he healed a blind beggar.", fake: true },
    ],
    explanation: "They recognized him when he broke the bread.",
  },
  {
    topic: "The Ascension",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Jesus was taken up into heaven in a cloud.", fake: false },
      { text: "Angels said he would return the same way he left.", fake: false },
      { text: "Jesus ascended while walking on water on the Sea of Galilee.", fake: true },
    ],
    explanation: "He ascended from the Mount of Olives near Bethany.",
  },
  {
    topic: "Belshazzar's Feast",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "A mysterious hand wrote words on the wall during a royal feast.", fake: false },
      { text: "Daniel was called in to interpret the writing.", fake: false },
      { text: "The words were written in flaming letters that never faded.", fake: true },
    ],
    explanation: "A hand wrote on the plaster wall; there's no mention of flames.",
  },
  {
    topic: "Nebuchadnezzar",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Nebuchadnezzar had a dream of a great statue made of different metals.", fake: false },
      { text: "He was humbled and lived like a wild animal, eating grass.", fake: false },
      { text: "Nebuchadnezzar was the king of Egypt.", fake: true },
    ],
    explanation: "He was the king of Babylon.",
  },
  {
    topic: "Rebekah",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Rebekah drew water for Abraham's servant and his camels.", fake: false },
      { text: "Rebekah became the wife of Isaac.", fake: false },
      { text: "Rebekah was the mother of Joseph.", fake: true },
    ],
    explanation: "Rebekah was the mother of the twins Jacob and Esau.",
  },
  {
    topic: "Jacob's Ladder",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Jacob dreamed of a ladder or stairway reaching up to heaven.", fake: false },
      { text: "Angels were going up and down on it.", fake: false },
      { text: "Jacob had this dream while living in Pharaoh's palace.", fake: true },
    ],
    explanation: "He dreamed it in the wilderness, using a stone as a pillow, while fleeing Esau.",
  },
  {
    topic: "Miriam",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Miriam was the sister of Moses and Aaron.", fake: false },
      { text: "Miriam led the women in song after crossing the Red Sea.", fake: false },
      { text: "Miriam was swallowed by the earth for rebelling against Moses.", fake: true },
    ],
    explanation: "That was Korah; Miriam was struck with temporary leprosy.",
  },
  {
    topic: "Balaam",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Balaam's donkey spoke to him with a human voice.", fake: false },
      { text: "An angel with a drawn sword blocked Balaam's path.", fake: false },
      { text: "Balaam was a humble fisherman from Galilee.", fake: true },
    ],
    explanation: "Balaam was a diviner hired to curse Israel.",
  },
  {
    topic: "Nehemiah",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Nehemiah led the effort to rebuild the walls of Jerusalem.", fake: false },
      { text: "The workers built with a tool in one hand and a weapon in the other.", fake: false },
      { text: "It took Nehemiah forty years to finish the walls.", fake: true },
    ],
    explanation: "The walls were finished in just 52 days.",
  },
  {
    topic: "Ezra",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Ezra was a scribe who taught the people God's law.", fake: false },
      { text: "Ezra read the law aloud to the assembled people.", fake: false },
      { text: "Ezra wrote the Gospel of John.", fake: true },
    ],
    explanation: "Ezra lived centuries before the Gospels; he didn't write them.",
  },
  {
    topic: "Simeon & Anna",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Simeon held the baby Jesus in the temple and praised God.", fake: false },
      { text: "Anna was an elderly prophetess who gave thanks for the child.", fake: false },
      { text: "Simeon was the innkeeper who had no room for Mary and Joseph.", fake: true },
    ],
    explanation: "Simeon was a devout man in the temple, not an innkeeper.",
  },
  {
    topic: "Blind Bartimaeus",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Bartimaeus was a blind beggar sitting by the road.", fake: false },
      { text: "He cried out, 'Jesus, Son of David, have mercy on me!'", fake: false },
      { text: "Jesus healed him by covering his eyes with gold coins.", fake: true },
    ],
    explanation: "Jesus healed him and said his faith had made him well.",
  },
  {
    topic: "Jairus' Daughter",
    difficulty: "hard",
    testament: "NT",
    statements: [
      { text: "Jairus begged Jesus to come heal his dying daughter.", fake: false },
      { text: "Jesus said the girl was only sleeping.", fake: false },
      { text: "Jesus arrived too late and could not help the girl.", fake: true },
    ],
    explanation: "Jesus raised her, saying, 'Little girl, get up.'",
  },
  {
    topic: "Elisha",
    difficulty: "hard",
    testament: "OT",
    statements: [
      { text: "Elisha received a double portion of Elijah's spirit.", fake: false },
      { text: "Elisha made a lost axe head float to the surface of the water.", fake: false },
      { text: "Elisha was eaten by lions for mocking a group of children.", fake: true },
    ],
    explanation: "It was youths who mocked Elisha, and bears (not lions) that came out.",
  },
];
