// True or False Showdown — Bible true/false statement bank.
// This is the OFFLINE FALLBACK. When the `tf_questions` Supabase table has rows,
// the game loads from there instead (run supabase/v10_true_or_false.sql).
//
// Difficulty mix is roughly 1 : 3 : 1 (easy : medium : hard), so most rounds sit
// in the middle and the game ramps up as the crowd thins out.
export type TFDifficulty = "easy" | "medium" | "hard";
export type TFQuestion = {
  statement: string;      // read this out loud
  answer: boolean;        // true  => the statement is TRUE
  difficulty: TFDifficulty;
  testament: "OT" | "NT" | null;
  reference: string;      // where it's found, for the leader
  explanation: string;    // the note / correction, for the leader
};

export const TRUE_FALSE_QUESTIONS: TFQuestion[] = [
  { statement: `Jesus was born in Bethlehem.`, answer: true, difficulty: "easy", testament: "NT", reference: `Luke 2:4-7`, explanation: `Jesus was born in Bethlehem of Judea.` },
  { statement: `Noah built an ark to survive the great flood.`, answer: true, difficulty: "easy", testament: "OT", reference: `Genesis 6-7`, explanation: `God told him to build it.` },
  { statement: `Jonah was swallowed by a great fish.`, answer: true, difficulty: "easy", testament: "OT", reference: `Jonah 1:17`, explanation: `He was inside three days and three nights.` },
  { statement: `David defeated Goliath with a sling and a stone.`, answer: true, difficulty: "easy", testament: "OT", reference: `1 Samuel 17`, explanation: `A single stone struck the giant down.` },
  { statement: `God parted the Red Sea for Moses and the Israelites.`, answer: true, difficulty: "easy", testament: "OT", reference: `Exodus 14`, explanation: `They crossed on dry ground.` },
  { statement: `Jesus had twelve disciples.`, answer: true, difficulty: "easy", testament: "NT", reference: `Matthew 10:1-4`, explanation: `Twelve were chosen.` },
  { statement: `Jesus turned water into wine.`, answer: true, difficulty: "easy", testament: "NT", reference: `John 2`, explanation: `His first miracle, at a wedding in Cana.` },
  { statement: `Daniel was thrown into a den of lions.`, answer: true, difficulty: "easy", testament: "OT", reference: `Daniel 6`, explanation: `God shut the lions' mouths.` },
  { statement: `Joseph was given a coat of many colors by his father.`, answer: true, difficulty: "easy", testament: "OT", reference: `Genesis 37`, explanation: `A richly ornamented robe.` },
  { statement: `The Ten Commandments were given to Moses.`, answer: true, difficulty: "easy", testament: "OT", reference: `Exodus 20`, explanation: `On Mount Sinai, on tablets of stone.` },
  { statement: `Jesus rose from the dead on the third day.`, answer: true, difficulty: "easy", testament: "NT", reference: `Luke 24`, explanation: `The tomb was found empty.` },
  { statement: `Peter denied knowing Jesus three times.`, answer: true, difficulty: "easy", testament: "NT", reference: `Luke 22`, explanation: `Before the rooster crowed.` },
  { statement: `Jesus walked on water.`, answer: true, difficulty: "easy", testament: "NT", reference: `Matthew 14`, explanation: `On the Sea of Galilee.` },
  { statement: `Jesus fed over 5,000 people with five loaves and two fish.`, answer: true, difficulty: "easy", testament: "NT", reference: `John 6`, explanation: `Twelve baskets of leftovers remained.` },
  { statement: `John the Baptist baptized Jesus.`, answer: true, difficulty: "easy", testament: "NT", reference: `Matthew 3`, explanation: `In the Jordan River.` },
  { statement: `Solomon was known for his wisdom.`, answer: true, difficulty: "easy", testament: "OT", reference: `1 Kings 3`, explanation: `He asked God for it.` },
  { statement: `Abraham was willing to sacrifice his son Isaac.`, answer: true, difficulty: "easy", testament: "OT", reference: `Genesis 22`, explanation: `God provided a ram instead.` },
  { statement: `The first book of the Bible is Genesis.`, answer: true, difficulty: "easy", testament: "OT", reference: `Genesis 1`, explanation: `'In the beginning...'` },
  { statement: `Judas Iscariot betrayed Jesus.`, answer: true, difficulty: "easy", testament: "NT", reference: `Matthew 26`, explanation: `For thirty pieces of silver.` },
  { statement: `God set a rainbow in the sky as a sign of his promise after the flood.`, answer: true, difficulty: "easy", testament: "OT", reference: `Genesis 9`, explanation: `Never again to flood the whole earth.` },
  { statement: `God created the whole world in seven days.`, answer: false, difficulty: "easy", testament: "OT", reference: `Genesis 1-2`, explanation: `He created in six days and rested on the seventh.` },
  { statement: `The Bible names the forbidden fruit in Eden as an apple.`, answer: false, difficulty: "easy", testament: "OT", reference: `Genesis 3`, explanation: `The fruit is never identified as an apple.` },
  { statement: `Jesus had eleven disciples.`, answer: false, difficulty: "easy", testament: "NT", reference: `Matthew 10:1-4`, explanation: `He had twelve.` },
  { statement: `Goliath defeated David in battle.`, answer: false, difficulty: "easy", testament: "OT", reference: `1 Samuel 17`, explanation: `David defeated Goliath.` },
  { statement: `The Bible says exactly three wise men visited Jesus.`, answer: false, difficulty: "easy", testament: "NT", reference: `Matthew 2`, explanation: `The number is never given; only three gifts are named.` },
  { statement: `Peter and John were Jesus' younger brothers.`, answer: false, difficulty: "easy", testament: "NT", reference: `Matthew 10`, explanation: `They were disciples, not his brothers.` },
  { statement: `Jesus was born in a royal palace.`, answer: false, difficulty: "easy", testament: "NT", reference: `Luke 2`, explanation: `He was laid in a manger.` },
  { statement: `The last book of the Bible is Genesis.`, answer: false, difficulty: "easy", testament: "NT", reference: `Revelation 22`, explanation: `The last book is Revelation.` },
  { statement: `Moses wrote the book of Revelation.`, answer: false, difficulty: "easy", testament: "NT", reference: `Revelation 1`, explanation: `It is traditionally attributed to John.` },
  { statement: `Adam and Eve had a son named Goliath.`, answer: false, difficulty: "easy", testament: "OT", reference: `Genesis 4`, explanation: `Their sons were Cain, Abel, and Seth.` },
  { statement: `Jesus was baptized by his disciple Peter.`, answer: false, difficulty: "easy", testament: "NT", reference: `Matthew 3`, explanation: `He was baptized by John the Baptist.` },
  { statement: `Samson was famous for being the wisest man alive.`, answer: false, difficulty: "easy", testament: "OT", reference: `Judges 16`, explanation: `He was famous for his great strength.` },
  { statement: `Noah's ark came to rest on Mount Sinai.`, answer: false, difficulty: "easy", testament: "OT", reference: `Genesis 8:4`, explanation: `It rested on the mountains of Ararat.` },
  { statement: `There were five commandments given to Moses.`, answer: false, difficulty: "easy", testament: "OT", reference: `Exodus 20`, explanation: `There were ten.` },
  { statement: `Jonah stayed inside the great fish for three weeks.`, answer: false, difficulty: "easy", testament: "OT", reference: `Jonah 1:17`, explanation: `It was three days and three nights.` },
  { statement: `Mary was the mother of Moses.`, answer: false, difficulty: "easy", testament: "NT", reference: `Luke 1`, explanation: `Mary was the mother of Jesus.` },
  { statement: `Jesus turned wine into water at a wedding.`, answer: false, difficulty: "easy", testament: "NT", reference: `John 2`, explanation: `He turned water into wine.` },
  { statement: `David was the first king of Israel.`, answer: false, difficulty: "easy", testament: "OT", reference: `1 Samuel 10`, explanation: `Saul was first; David was second.` },
  { statement: `The wise men brought the baby Jesus toys and new clothes.`, answer: false, difficulty: "easy", testament: "NT", reference: `Matthew 2:11`, explanation: `They brought gold, frankincense, and myrrh.` },
  { statement: `Jesus was crucified in the town of Bethlehem.`, answer: false, difficulty: "easy", testament: "NT", reference: `John 19`, explanation: `He was crucified at Golgotha, near Jerusalem.` },
  { statement: `Methuselah lived longer than anyone else recorded in the Bible.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 5:27`, explanation: `He lived 969 years.` },
  { statement: `Saul was the first king of Israel.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Samuel 10`, explanation: `David was the second.` },
  { statement: `The walls of Jericho fell after the Israelites marched and shouted.`, answer: true, difficulty: "medium", testament: "OT", reference: `Joshua 6`, explanation: `No battering ram was used.` },
  { statement: `Esther became a queen of Persia.`, answer: true, difficulty: "medium", testament: "OT", reference: `Esther 2`, explanation: `She later saved her people.` },
  { statement: `Ruth was the great-grandmother of King David.`, answer: true, difficulty: "medium", testament: "OT", reference: `Ruth 4`, explanation: `Through her son Obed.` },
  { statement: `Gideon's army was reduced to just 300 men.`, answer: true, difficulty: "medium", testament: "OT", reference: `Judges 7`, explanation: `So the victory would clearly be God's.` },
  { statement: `Job lost his wealth, his children, and his health.`, answer: true, difficulty: "medium", testament: "OT", reference: `Job 1-2`, explanation: `Yet he did not curse God.` },
  { statement: `Zacchaeus climbed a sycamore tree to see Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Luke 19`, explanation: `He was short and the crowd was large.` },
  { statement: `Lazarus was raised from the dead by Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 11`, explanation: `After four days in the tomb.` },
  { statement: `Elijah was taken up to heaven in a whirlwind with a chariot of fire.`, answer: true, difficulty: "medium", testament: "OT", reference: `2 Kings 2`, explanation: `Elisha watched him go.` },
  { statement: `Shadrach, Meshach, and Abednego survived the fiery furnace.`, answer: true, difficulty: "medium", testament: "OT", reference: `Daniel 3`, explanation: `A fourth figure appeared with them.` },
  { statement: `The Israelites ate manna in the wilderness.`, answer: true, difficulty: "medium", testament: "OT", reference: `Exodus 16`, explanation: `Bread from heaven each morning.` },
  { statement: `Aaron was the brother of Moses.`, answer: true, difficulty: "medium", testament: "OT", reference: `Exodus 4`, explanation: `His older brother and spokesman.` },
  { statement: `Jacob had twelve sons.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 35`, explanation: `They became the twelve tribes of Israel.` },
  { statement: `Rahab helped hide the Israelite spies in Jericho.`, answer: true, difficulty: "medium", testament: "OT", reference: `Joshua 2`, explanation: `She was spared when the city fell.` },
  { statement: `Joshua succeeded Moses as leader of Israel.`, answer: true, difficulty: "medium", testament: "OT", reference: `Joshua 1`, explanation: `He led them into the Promised Land.` },
  { statement: `Deborah was a prophetess and a judge of Israel.`, answer: true, difficulty: "medium", testament: "OT", reference: `Judges 4`, explanation: `She led alongside Barak.` },
  { statement: `Jesus taught his followers the Lord's Prayer.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 6`, explanation: `'Our Father in heaven...'` },
  { statement: `The parable of the Good Samaritan answers the question 'Who is my neighbor?'`, answer: true, difficulty: "medium", testament: "NT", reference: `Luke 10`, explanation: `A Samaritan helped a wounded stranger.` },
  { statement: `Thomas doubted that Jesus had risen from the dead.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 20`, explanation: `He wanted to see the nail marks.` },
  { statement: `Matthew was a tax collector before following Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 9`, explanation: `Jesus called him from the tax booth.` },
  { statement: `Jesus washed his disciples' feet at the Last Supper.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 13`, explanation: `An example of humble service.` },
  { statement: `Jesus fasted forty days in the wilderness.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 4`, explanation: `Before he was tempted.` },
  { statement: `Nebuchadnezzar was the king of Babylon.`, answer: true, difficulty: "medium", testament: "OT", reference: `Daniel 2`, explanation: `He had dreams Daniel interpreted.` },
  { statement: `Belshazzar saw a mysterious hand writing on the wall during a feast.`, answer: true, difficulty: "medium", testament: "OT", reference: `Daniel 5`, explanation: `Daniel interpreted the writing.` },
  { statement: `Sarah gave birth to Isaac in her old age.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 21`, explanation: `She was about ninety.` },
  { statement: `Esau sold his birthright for a bowl of stew.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 25`, explanation: `He despised his birthright.` },
  { statement: `Jacob's name was changed to Israel.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 32`, explanation: `After he wrestled with God.` },
  { statement: `Joseph interpreted Pharaoh's dreams about years of plenty and famine.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 41`, explanation: `He became second in command of Egypt.` },
  { statement: `Moses saw a bush that burned but was not consumed.`, answer: true, difficulty: "medium", testament: "OT", reference: `Exodus 3`, explanation: `God spoke to him from it.` },
  { statement: `The golden calf was made while Moses was on Mount Sinai.`, answer: true, difficulty: "medium", testament: "OT", reference: `Exodus 32`, explanation: `Aaron made it for the impatient people.` },
  { statement: `King David wrote many of the Psalms.`, answer: true, difficulty: "medium", testament: "OT", reference: `Psalms`, explanation: `Many are attributed to him.` },
  { statement: `Solomon built the first temple in Jerusalem.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Kings 6`, explanation: `A house for the Lord.` },
  { statement: `Jeremiah is often called the 'weeping prophet.'`, answer: true, difficulty: "medium", testament: "OT", reference: `Jeremiah 9`, explanation: `He mourned over Judah's sin.` },
  { statement: `Ezekiel saw a vision of a valley of dry bones.`, answer: true, difficulty: "medium", testament: "OT", reference: `Ezekiel 37`, explanation: `The bones came to life.` },
  { statement: `Isaiah prophesied about a coming Messiah.`, answer: true, difficulty: "medium", testament: "OT", reference: `Isaiah 53`, explanation: `Centuries before Jesus.` },
  { statement: `Daniel chose vegetables and water over the king's rich food.`, answer: true, difficulty: "medium", testament: "OT", reference: `Daniel 1`, explanation: `He and his friends stayed healthy.` },
  { statement: `The Queen of Sheba visited King Solomon.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Kings 10`, explanation: `To test his wisdom.` },
  { statement: `Naaman was healed of leprosy by washing in the Jordan River.`, answer: true, difficulty: "medium", testament: "OT", reference: `2 Kings 5`, explanation: `Seven times, as the prophet said.` },
  { statement: `The Holy Spirit came upon the believers at Pentecost.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 2`, explanation: `With wind and tongues of fire.` },
  { statement: `Stephen was the first Christian martyr.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 7`, explanation: `He was stoned to death.` },
  { statement: `Paul was blinded by a bright light on the road to Damascus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 9`, explanation: `He met the risen Jesus.` },
  { statement: `Jesus raised Jairus' daughter from the dead.`, answer: true, difficulty: "medium", testament: "NT", reference: `Mark 5`, explanation: `'Little girl, get up.'` },
  { statement: `The parable of the sower describes seed falling on different soils.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 13`, explanation: `The seed is the word of God.` },
  { statement: `The woman Jesus spoke with at the well was a Samaritan.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 4`, explanation: `He offered her living water.` },
  { statement: `Simeon held the baby Jesus in the temple and praised God.`, answer: true, difficulty: "medium", testament: "NT", reference: `Luke 2`, explanation: `He had waited to see the Messiah.` },
  { statement: `At the Transfiguration, Moses and Elijah appeared with Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 17`, explanation: `His face shone like the sun.` },
  { statement: `Judas identified Jesus to the soldiers with a kiss.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 26`, explanation: `In the Garden of Gethsemane.` },
  { statement: `Pontius Pilate sentenced Jesus to be crucified.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 19`, explanation: `Though he found no fault in him.` },
  { statement: `Jesus ascended to heaven from the Mount of Olives.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 1`, explanation: `A cloud took him from their sight.` },
  { statement: `Andrew was the brother of Peter.`, answer: true, difficulty: "medium", testament: "NT", reference: `John 1`, explanation: `Both were fishermen Jesus called.` },
  { statement: `Cornelius was a Roman centurion who came to faith.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 10`, explanation: `Peter was sent to him.` },
  { statement: `Paul and Silas sang hymns while in prison.`, answer: true, difficulty: "medium", testament: "NT", reference: `Acts 16`, explanation: `An earthquake then opened the doors.` },
  { statement: `Balaam's donkey spoke to him with a human voice.`, answer: true, difficulty: "medium", testament: "OT", reference: `Numbers 22`, explanation: `An angel had blocked the path.` },
  { statement: `Hannah prayed for a son and God gave her Samuel.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Samuel 1`, explanation: `She dedicated him to the Lord.` },
  { statement: `Bathsheba became a wife of King David.`, answer: true, difficulty: "medium", testament: "OT", reference: `2 Samuel 11-12`, explanation: `She was the mother of Solomon.` },
  { statement: `The kingdom of Israel split into two after Solomon died.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Kings 12`, explanation: `Into Israel and Judah.` },
  { statement: `Nehemiah led the effort to rebuild the walls of Jerusalem.`, answer: true, difficulty: "medium", testament: "OT", reference: `Nehemiah 2`, explanation: `Despite fierce opposition.` },
  { statement: `John the Baptist ate locusts and wild honey.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 3`, explanation: `He lived in the wilderness.` },
  { statement: `John the Baptist was beheaded by order of Herod.`, answer: true, difficulty: "medium", testament: "NT", reference: `Mark 6`, explanation: `At the request of Herodias' daughter.` },
  { statement: `Paul was one of Jesus' original twelve disciples.`, answer: false, difficulty: "medium", testament: "NT", reference: `Acts 9`, explanation: `He came later; he was not one of the Twelve.` },
  { statement: `Nicodemus came to Jesus in the middle of the day.`, answer: false, difficulty: "medium", testament: "NT", reference: `John 3`, explanation: `He came to Jesus at night.` },
  { statement: `When the prodigal son returned home, his father turned him away.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 15`, explanation: `His father ran to him and threw a feast.` },
  { statement: `God destroyed the Tower of Babel with fire from heaven.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 11`, explanation: `He confused their language and scattered them.` },
  { statement: `Jesus preached the Sermon on the Mount from inside the temple.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 5`, explanation: `He taught it on a mountainside.` },
  { statement: `After his conversion, Saul's name was changed to Peter.`, answer: false, difficulty: "medium", testament: "NT", reference: `Acts 13`, explanation: `His name became Paul.` },
  { statement: `Mary Magdalene was the mother of Jesus.`, answer: false, difficulty: "medium", testament: "NT", reference: `John 20`, explanation: `Jesus' mother was Mary of Nazareth, a different Mary.` },
  { statement: `All ten lepers returned to thank Jesus for healing them.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 17`, explanation: `Only one returned, and he was a Samaritan.` },
  { statement: `Rebekah was the wife of Jacob.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 24`, explanation: `She was the wife of Isaac.` },
  { statement: `There were seven plagues on Egypt.`, answer: false, difficulty: "medium", testament: "OT", reference: `Exodus 7-12`, explanation: `There were ten plagues.` },
  { statement: `Jonah obeyed God right away and sailed straight to Nineveh.`, answer: false, difficulty: "medium", testament: "OT", reference: `Jonah 1`, explanation: `He first fled toward Tarshish.` },
  { statement: `The book of Revelation was written by the apostle Matthew.`, answer: false, difficulty: "medium", testament: "NT", reference: `Revelation 1`, explanation: `It is traditionally attributed to John.` },
  { statement: `The rich young ruler gladly gave up his wealth to follow Jesus.`, answer: false, difficulty: "medium", testament: "NT", reference: `Mark 10`, explanation: `He went away sad because he was very rich.` },
  { statement: `Martha sat at Jesus' feet while Mary was busy serving.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 10`, explanation: `It was reversed: Mary sat, Martha served.` },
  { statement: `The book of Psalms is found in the New Testament.`, answer: false, difficulty: "medium", testament: "OT", reference: `Psalms`, explanation: `Psalms is in the Old Testament.` },
  { statement: `The wise men visited Jesus in the stable on the night he was born.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 2`, explanation: `They came later and found him in a house.` },
  { statement: `The disciple who walked on the water toward Jesus was John.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 14`, explanation: `It was Peter who stepped out of the boat.` },
  { statement: `Isaac's son was named Ishmael.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 25`, explanation: `Isaac's sons were Jacob and Esau; Ishmael was Abraham's son.` },
  { statement: `Elijah was the successor of Elisha.`, answer: false, difficulty: "medium", testament: "OT", reference: `2 Kings 2`, explanation: `Elisha succeeded Elijah, not the other way around.` },
  { statement: `Goliath was an Israelite soldier.`, answer: false, difficulty: "medium", testament: "OT", reference: `1 Samuel 17`, explanation: `He was a Philistine champion.` },
  { statement: `Samuel was the first king of Israel.`, answer: false, difficulty: "medium", testament: "OT", reference: `1 Samuel 10`, explanation: `Samuel was a prophet; he anointed Saul as first king.` },
  { statement: `The Ark of the Covenant was carried on the backs of horses.`, answer: false, difficulty: "medium", testament: "OT", reference: `Numbers 4`, explanation: `Levites carried it with poles on their shoulders.` },
  { statement: `Moses led Israel across the Jordan into the Promised Land.`, answer: false, difficulty: "medium", testament: "OT", reference: `Joshua 3`, explanation: `Moses died first; Joshua led them across.` },
  { statement: `Jesus was born in the town of Nazareth.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 2`, explanation: `He was born in Bethlehem; he grew up in Nazareth.` },
  { statement: `Peter wrote most of the letters in the New Testament.`, answer: false, difficulty: "medium", testament: "NT", reference: `New Testament`, explanation: `Paul wrote the most letters.` },
  { statement: `The prophet Daniel was thrown into a fiery furnace.`, answer: false, difficulty: "medium", testament: "OT", reference: `Daniel 3; 6`, explanation: `Daniel was in the lions' den; his three friends were in the furnace.` },
  { statement: `Cain and Abel were the sons of Noah.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 4`, explanation: `They were sons of Adam and Eve.` },
  { statement: `The Israelites wandered in the wilderness for twelve years.`, answer: false, difficulty: "medium", testament: "OT", reference: `Numbers 14`, explanation: `They wandered forty years.` },
  { statement: `Solomon was the father of King David.`, answer: false, difficulty: "medium", testament: "OT", reference: `2 Samuel 12`, explanation: `David was Solomon's father, not the reverse.` },
  { statement: `The parable of the prodigal son is really about a lost coin.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 15`, explanation: `It is about a lost son who returns home.` },
  { statement: `Joseph's brothers welcomed him warmly and never harmed him.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 37`, explanation: `They sold him into slavery.` },
  { statement: `Abraham's wife was named Rachel.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 17`, explanation: `Abraham's wife was Sarah; Rachel was Jacob's wife.` },
  { statement: `The first Passover took place in the Promised Land.`, answer: false, difficulty: "medium", testament: "OT", reference: `Exodus 12`, explanation: `It happened in Egypt, the night before the Exodus.` },
  { statement: `King Herod helped protect the baby Jesus.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 2`, explanation: `He tried to have Jesus killed.` },
  { statement: `Jesus personally wrote several books of the New Testament.`, answer: false, difficulty: "medium", testament: "NT", reference: `New Testament`, explanation: `Jesus wrote none of them himself.` },
  { statement: `Lot's wife turned into a pillar of gold.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 19`, explanation: `She turned into a pillar of salt.` },
  { statement: `The Ten Commandments were given at the Sea of Galilee.`, answer: false, difficulty: "medium", testament: "OT", reference: `Exodus 20`, explanation: `They were given at Mount Sinai.` },
  { statement: `Delilah gave Samson his great strength.`, answer: false, difficulty: "medium", testament: "OT", reference: `Judges 16`, explanation: `She betrayed the secret of his strength; his strength was from God.` },
  { statement: `The Holy Spirit came upon the believers at Passover.`, answer: false, difficulty: "medium", testament: "NT", reference: `Acts 2`, explanation: `It came at Pentecost.` },
  { statement: `Stephen was beheaded for his faith.`, answer: false, difficulty: "medium", testament: "NT", reference: `Acts 7`, explanation: `He was stoned to death.` },
  { statement: `Zacchaeus refused to give back any of the money he had taken.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 19`, explanation: `He gave half to the poor and repaid those he cheated fourfold.` },
  { statement: `Jesus rode into Jerusalem on a white horse.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 21`, explanation: `He rode in humbly on a donkey.` },
  { statement: `Judas betrayed Jesus for forty pieces of gold.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 26`, explanation: `It was thirty pieces of silver.` },
  { statement: `When God offered Solomon anything, he asked first for great riches.`, answer: false, difficulty: "medium", testament: "OT", reference: `1 Kings 3`, explanation: `He asked for wisdom.` },
  { statement: `Ruth was from the land of Egypt.`, answer: false, difficulty: "medium", testament: "OT", reference: `Ruth 1`, explanation: `Ruth was a Moabite.` },
  { statement: `Peter walked on the water and never began to sink.`, answer: false, difficulty: "medium", testament: "NT", reference: `Matthew 14`, explanation: `He began to sink and cried out to Jesus.` },
  { statement: `The apostle Paul wrote a letter to the Romans.`, answer: true, difficulty: "medium", testament: "NT", reference: `Romans 1`, explanation: `The book of Romans is one of his letters.` },
  { statement: `Peter was a fisherman before he followed Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Matthew 4`, explanation: `Jesus called him to fish for people.` },
  { statement: `Joseph rose to become a powerful ruler in Egypt.`, answer: true, difficulty: "medium", testament: "OT", reference: `Genesis 41`, explanation: `Second in command under Pharaoh.` },
  { statement: `Jesus told the parable of the lost sheep.`, answer: true, difficulty: "medium", testament: "NT", reference: `Luke 15`, explanation: `A shepherd leaves ninety-nine to find one.` },
  { statement: `Aaron became the first high priest of Israel.`, answer: true, difficulty: "medium", testament: "OT", reference: `Exodus 28`, explanation: `Moses' brother.` },
  { statement: `David played the harp to soothe King Saul.`, answer: true, difficulty: "medium", testament: "OT", reference: `1 Samuel 16`, explanation: `His music calmed the troubled king.` },
  { statement: `The angel Gabriel told Mary she would give birth to Jesus.`, answer: true, difficulty: "medium", testament: "NT", reference: `Luke 1`, explanation: `The announcement of Jesus' birth.` },
  { statement: `The book of Exodus is the very first book of the Bible.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 1`, explanation: `Genesis is first; Exodus is second.` },
  { statement: `Martha was one of Jesus' twelve disciples.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 10`, explanation: `She was a friend and host of Jesus, not one of the Twelve.` },
  { statement: `Noah's three sons were named Shem, Ham, and Peter.`, answer: false, difficulty: "medium", testament: "OT", reference: `Genesis 6`, explanation: `They were Shem, Ham, and Japheth.` },
  { statement: `The Israelites crossed the Jordan River to escape from Egypt.`, answer: false, difficulty: "medium", testament: "OT", reference: `Exodus 14`, explanation: `They crossed the Red Sea to escape Egypt.` },
  { statement: `Elijah was fed by ravens sent by King Ahab.`, answer: false, difficulty: "medium", testament: "OT", reference: `1 Kings 17`, explanation: `God sent the ravens to feed him.` },
  { statement: `The prophet Jonah was sent to preach in the city of Babylon.`, answer: false, difficulty: "medium", testament: "OT", reference: `Jonah 3`, explanation: `He was sent to Nineveh.` },
  { statement: `Jesus was crucified alone, with no one beside him.`, answer: false, difficulty: "medium", testament: "NT", reference: `Luke 23`, explanation: `He was crucified between two criminals.` },
  { statement: `Methuselah lived 969 years.`, answer: true, difficulty: "hard", testament: "OT", reference: `Genesis 5:27`, explanation: `The longest lifespan recorded in Scripture.` },
  { statement: `Enoch did not die but was taken away by God.`, answer: true, difficulty: "hard", testament: "OT", reference: `Genesis 5:24`, explanation: `'God took him.'` },
  { statement: `Nehemiah's crew rebuilt the walls of Jerusalem in 52 days.`, answer: true, difficulty: "hard", testament: "OT", reference: `Nehemiah 6:15`, explanation: `A remarkably fast rebuild.` },
  { statement: `Ehud was a left-handed judge of Israel.`, answer: true, difficulty: "hard", testament: "OT", reference: `Judges 3`, explanation: `He delivered Israel from Moab.` },
  { statement: `Melchizedek was both a king of Salem and a priest of God.`, answer: true, difficulty: "hard", testament: "OT", reference: `Genesis 14`, explanation: `He blessed Abraham.` },
  { statement: `Aaron's staff budded and produced almonds.`, answer: true, difficulty: "hard", testament: "OT", reference: `Numbers 17`, explanation: `A sign confirming his priesthood.` },
  { statement: `Moses lifted up a bronze serpent so the snake-bitten could look and live.`, answer: true, difficulty: "hard", testament: "OT", reference: `Numbers 21`, explanation: `Jesus later compared himself to it.` },
  { statement: `Caleb and Joshua were the only two spies who gave a faithful report.`, answer: true, difficulty: "hard", testament: "OT", reference: `Numbers 14`, explanation: `The other ten spread fear.` },
  { statement: `Absalom was caught by his hair in an oak tree.`, answer: true, difficulty: "hard", testament: "OT", reference: `2 Samuel 18`, explanation: `It led to his death.` },
  { statement: `Elisha's servant Gehazi was struck with leprosy for his greed.`, answer: true, difficulty: "hard", testament: "OT", reference: `2 Kings 5`, explanation: `He secretly took Naaman's gifts.` },
  { statement: `King Hezekiah was given fifteen more years of life.`, answer: true, difficulty: "hard", testament: "OT", reference: `2 Kings 20`, explanation: `After he prayed in his illness.` },
  { statement: `Philemon is a short letter about a runaway slave named Onesimus.`, answer: true, difficulty: "hard", testament: "NT", reference: `Philemon`, explanation: `Paul appealed for his welcome back.` },
  { statement: `Eutychus fell from a window during Paul's long sermon and was raised to life.`, answer: true, difficulty: "hard", testament: "NT", reference: `Acts 20`, explanation: `He had drifted to sleep.` },
  { statement: `Gamaliel was the respected teacher who trained Paul.`, answer: true, difficulty: "hard", testament: "NT", reference: `Acts 22`, explanation: `A leading Pharisee.` },
  { statement: `The prophet Nathan confronted David over Bathsheba.`, answer: true, difficulty: "hard", testament: "OT", reference: `2 Samuel 12`, explanation: `'You are the man!'` },
  { statement: `Rahab is listed in the genealogy of Jesus.`, answer: true, difficulty: "hard", testament: "NT", reference: `Matthew 1:5`, explanation: `Among Jesus' ancestors.` },
  { statement: `King Saul consulted the witch of Endor.`, answer: true, difficulty: "hard", testament: "OT", reference: `1 Samuel 28`, explanation: `The night before he died in battle.` },
  { statement: `King Uzziah was struck with leprosy for burning incense in the temple.`, answer: true, difficulty: "hard", testament: "OT", reference: `2 Chronicles 26`, explanation: `He overstepped the priests' role.` },
  { statement: `Amos was a shepherd before God called him to prophesy.`, answer: true, difficulty: "hard", testament: "OT", reference: `Amos 7:14`, explanation: `Also a tender of sycamore figs.` },
  { statement: `Goliath stood over nine feet tall according to many translations.`, answer: true, difficulty: "hard", testament: "OT", reference: `1 Samuel 17:4`, explanation: `'Six cubits and a span.'` },
  { statement: `About 5,000 people were added to the church on the day of Pentecost.`, answer: false, difficulty: "hard", testament: "NT", reference: `Acts 2:41`, explanation: `About 3,000 were added that day.` },
  { statement: `Jael killed the enemy commander Sisera with a sword.`, answer: false, difficulty: "hard", testament: "OT", reference: `Judges 4`, explanation: `She used a tent peg and a hammer.` },
  { statement: `Samson killed a thousand men with the jawbone of a lion.`, answer: false, difficulty: "hard", testament: "OT", reference: `Judges 15`, explanation: `He used the jawbone of a donkey.` },
  { statement: `Elijah defeated the prophets of Baal on Mount Sinai.`, answer: false, difficulty: "hard", testament: "OT", reference: `1 Kings 18`, explanation: `The contest was on Mount Carmel.` },
  { statement: `Paul was shipwrecked on the island of Cyprus.`, answer: false, difficulty: "hard", testament: "NT", reference: `Acts 28`, explanation: `He was shipwrecked on Malta.` },
  { statement: `King Solomon wrote the book of Lamentations.`, answer: false, difficulty: "hard", testament: "OT", reference: `Lamentations`, explanation: `It is traditionally attributed to Jeremiah.` },
  { statement: `In the letter to Philemon, Onesimus was the master and Philemon the slave.`, answer: false, difficulty: "hard", testament: "NT", reference: `Philemon`, explanation: `Onesimus was the slave; Philemon was the master.` },
  { statement: `Obadiah is the longest book in the Old Testament.`, answer: false, difficulty: "hard", testament: "OT", reference: `Obadiah`, explanation: `It is the shortest, at one chapter.` },
  { statement: `The Jordan River caught fire when the priests carrying the ark stepped in.`, answer: false, difficulty: "hard", testament: "OT", reference: `Joshua 3`, explanation: `The river stopped flowing so Israel could cross.` },
  { statement: `Korah led a rebellion against Moses and was rewarded by God.`, answer: false, difficulty: "hard", testament: "OT", reference: `Numbers 16`, explanation: `The ground opened and swallowed the rebels.` },
  { statement: `Og was the giant king of Egypt.`, answer: false, difficulty: "hard", testament: "OT", reference: `Deuteronomy 3`, explanation: `He was king of Bashan.` },
  { statement: `Zerubbabel led the building of the very first temple in Jerusalem.`, answer: false, difficulty: "hard", testament: "OT", reference: `Ezra 3`, explanation: `He led the second temple, after the exile; Solomon built the first.` },
  { statement: `The book of Revelation addresses twelve churches in Asia.`, answer: false, difficulty: "hard", testament: "NT", reference: `Revelation 1`, explanation: `It addresses seven churches.` },
  { statement: `The prophet Habakkuk was swallowed by a great fish.`, answer: false, difficulty: "hard", testament: "OT", reference: `Jonah 1`, explanation: `That was Jonah, not Habakkuk.` },
  { statement: `Priscilla and Aquila were fishermen by trade.`, answer: false, difficulty: "hard", testament: "NT", reference: `Acts 18`, explanation: `They were tentmakers, like Paul.` },
  { statement: `Melchizedek is discussed at length in the book of James.`, answer: false, difficulty: "hard", testament: "NT", reference: `Hebrews 7`, explanation: `He is discussed in Hebrews.` },
  { statement: `Nehemiah's main task was to rebuild the temple in Jerusalem.`, answer: false, difficulty: "hard", testament: "OT", reference: `Nehemiah 2`, explanation: `He rebuilt the walls; the temple was rebuilt earlier under Zerubbabel.` },
  { statement: `Gideon tested God by laying out a golden fleece.`, answer: false, difficulty: "hard", testament: "OT", reference: `Judges 6`, explanation: `It was a wool fleece.` },
  { statement: `The witch of Endor was consulted by King David.`, answer: false, difficulty: "hard", testament: "OT", reference: `1 Samuel 28`, explanation: `It was King Saul.` },
  { statement: `Elisha received a single portion of Elijah's spirit.`, answer: false, difficulty: "hard", testament: "OT", reference: `2 Kings 2`, explanation: `He asked for and received a double portion.` },
];
